### ISSUE TITLE
Not working for a type

### ISSUE THREAD

**Issue by crsmithdev** [vektra/mockery#10]
```
mockery -dir=$GOPATH/src/github.com/Shopify/sarama -name=AsyncProducer
Generating mock for: AsyncProducer
Unable to generated mock for 'AsyncProducer': unable to handle type: &ast.ChanType{Begin:1463, Arrow:1467, Dir:1, Value:(*ast.StarExpr)(0x2083eea40)}
```

**Comment by evanphx** [comment]
Fixed! Thanks for the report!

**Comment by crsmithdev** [comment]
Sweet!  Working now and thanks for the super-fast turnaround.  Great tool.

**Comment by evanphx** [comment]
Thanks! My Pleasure!

On Tue, Mar 17, 2015 at 3:40 PM, Chris Smith <notifications@github.com>
wrote:

> Sweet! Working now and thanks for the super-fast turnaround. Great tool.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vektra/mockery/issues/10#issuecomment-82629823>.
>



-- 
Evan Phoenix // evan@vektra.com
