### ISSUE TITLE
Fails when package name is aliased because of name conflict

### ISSUE THREAD

**Issue by vikashvverma** [vektra/mockery#103]
Say there are two packages: `github.com/vikashvverma/demo/models` and `github.com/vikashvverma/demo/common/models`.

When both packages are imported like:

```
import (
        'github.com/vikashvverma/demo/models'
        md  'github.com/vikashvverma/demo/common/models'
)
```

`mockery` fails to generate mock for methods using `md`

**Comment by jabalsad** [comment]
Can confirm I am seeing a similar problem. This is painful because we have to edit the mock manually after generation to fix all the type mismatches.

**Comment by andymc904** [comment]
There currently is a test for this very thing here

https://github.com/vektra/mockery/blob/master/mockery/fixtures/same_name_imports.go

This integration target in the makefile will generate a mock for that class.

Can you provide a more specific example?

**Comment by evanphx** [comment]
Please reopen if this is still an issue.
