### ISSUE TITLE
Mockery appears to not respect build tags

### ISSUE THREAD

**Issue by jirwin** [vektra/mockery#109]
I have an interface that has different implementations per operating system(unix, windows). When trying to mock this interface I get errors about functions being defined more than once.

```
$ mockery --name=Client --name=Server
svcrpc_windows.go:5:6: NewClient redeclared in this block
svcrpc_unix.go:11:6: 	other declaration of NewClient
svcrpc_windows.go:9:6: NewServer redeclared in this block
svcrpc_unix.go:20:6: 	other declaration of NewServer
Error parsing file:  couldn't load packages due to errors:
```

It'd be great to be able to pass an additional flag to parse and respect build tags.

**Comment by evanphx** [comment]
I'm not sure at all how to handle this, because mockery is parsing the files as requested. I'm not sure I want to implement the full build tag logic.

**Comment by jmalloc** [comment]
I've hit the same issue trying to generate mocks for Docker's client interfaces. In this case it's totally unrelated to the interface, but is causing the same kind of error as above:

```
client_windows.go:4:7: DefaultDockerHost redeclared in this block
client_unix.go:6:7: 	other declaration of DefaultDockerHost
```

Short of implementing the build tag logic, perhaps a `-file` argument, analogous to `-dir`, could serve as a workaround?

**Comment by codeactual** [comment]
I'll take a look at this one.

**Comment by codeactual** [comment]
@jmalloc #145 is available for testing in https://github.com/codeactual/mockery branch `build_tags`

**Comment by jmalloc** [comment]
I'll try this out asap :)

**Comment by jmalloc** [comment]
:+1: Looks good for my use case:

```console
$ /tmp/mockery -print -dir ./vendor/github.com/docker/docker/client/ -name CommonAPIClient | tail

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, filters.Args) error); ok {
		r1 = rf(ctx, pruneFilter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
```
