### ISSUE TITLE
import cycle

### ISSUE THREAD

**Issue by tejasmanohar** [vektra/mockery#110]
```
$ pwd
/Users/tejas/dev/src/github.com/NetSys/quilt/cluster/provider
$ mockery -name=EC2Client
Generating mock for: EC2Client
$ tree
.
├── amazon_test.go
├── awsSpot.go
├── cloud_config.go
├── constraint.go
├── gce.go
├── mocks
│   └── EC2Client.go
├── provider.go
├── provider_test.go
├── vagrant.go
└── vagrant_api.go

1 directory, 10 files

```

`mocks/EC2Client.go` is the generated file. That file is shown [here](https://gist.github.com/tejasmanohar/3c59bed42f3d46adba411c006e03bf42#file-go-L288). The last line `var _ provider.EC2Client = (*EC2Client)(nil)` causes an import cycle

```
$ go test ./cluster/provider
# github.com/NetSys/quilt/cluster/provider
import cycle not allowed in test
package github.com/NetSys/quilt/cluster/provider (test)
        imports github.com/NetSys/quilt/cluster/provider/mocks
        imports github.com/NetSys/quilt/cluster/provider

FAIL    github.com/NetSys/quilt/cluster/provider [setup failed]
```

I assume this line is to test that the interface is satisfied by the mock. That seems like a good idea, but do you have any suggestions on how to avoid to import cycle? Should the default be changed from generating in `./mocks`?

**Comment by IvanMalison** [comment]
> I assume this line is to test that the interface is satisfied by the mock. That seems like a good idea, but do you have any suggestions on how to avoid to import cycle? Should the default be changed from generating in ./mocks?

Yeah I added that to ensure that the mock satisfies the interface, so that if you do end up changing something, you will get very obvious output when you try to compile and you will know that you need to regenerate the mock.

I'm assuming that the reason you're getting an import cycle here is because provider_test.go import mocks, my recommendation would be to change your packaging scheme so that your test files all use the test suffix. This way the tests live in a separate package.

I know there is a page in the official docs page but this is the closest I could find https://splice.com/blog/lesser-known-features-go-test/

**Comment by IvanMalison** [comment]
Also, whatever solves #106 will likely resolve this issue as well.

**Comment by tejasmanohar** [comment]
>I'm assuming that the reason you're getting an import cycle here is because provider_test.go import mocks, my recommendation would be to change your packaging scheme so that your test files all use the test suffix. This way the tests live in a separate package.

I'm slightly confused. `amazon_test.go` imports the mocks, but even if `provider_test.go` imported the mock, wouldn't that be using the aforementioned "test suffix"?

**Comment by bogdanovich** [comment]
This should be fixed or at least have a command line flag to disable this check.
Otherwise it's not possible to use mockery with white-box testing

**Comment by IvanMalison** [comment]
@tejasmanohar 
its not about the file name, but the package that the import is declared in. What is the package statement in amazon_test.go?

**Comment by IvanMalison** [comment]
> This should be fixed or at least have a command line flag to disable this check.
> Otherwise it's not possible to use mockery with white-box testing

Agreed. Ideally we just handle the error and optimistically try to keep going.

**Comment by bogdanovich** [comment]
@tejasmanohar This is also breaks backwards compatibility. A lot of existing repositories use the same layout as the topic starter and now all their builds will break after mockery upgrade. Moreover they would need to reimplement their tests from white-box to black-box style.

**Comment by tejasmanohar** [comment]
I like the interface assertion. I'd rather us "handle the error and optimistically try to keep going"

**Comment by bogdanovich** [comment]
@IvanMalison @tejasmanohar What do you guys mean by "handle error"? The import cycle error  will be   faced as soon as you try to import your mock into your test file. The mock generation step does not have any errors by itself.

**Comment by bogdanovich** [comment]
Check the `mockgen` package as  well. They don't have interface assertion checks inside the mock code for the same obvious reason.

**Comment by tejasmanohar** [comment]
@IvanMalison I'm also confused what you mean by "Ideally we just handle the error and optimistically try to keep going.". Won't this error come from `go test`, go build`, etc. and not Mockery itself?

**Comment by tejasmanohar** [comment]
Also, moving tests into a separate package isn't always the best solution since it means you can't test private functions independently. I think Mockery should support both strategies, especially because _test.go files in the same package are very common.

**Comment by mmcloughlin** [comment]
Upgrading mockery an regenerating mocks just broke all our tests. Please make the assertion optional.

**Comment by tejasmanohar** [comment]
I just made mockery generaet the mocks in the same package btw

**Comment by mmcloughlin** [comment]
I am reverting to `c73497f29faa7c577018524932932636afe0d4e3`.

**Comment by natdm** [comment]
Same. Reverting to an older version.

**Comment by bogdanovich** [comment]
it was already merged separately

**Comment by romanws** [comment]
So what was the actual solution to this?

**Comment by adamward459** [comment]
> So what was the actual solution to this?

use `--inpackage` option
