### ISSUE TITLE
-output flag doesn't allow you to specify a file name

### ISSUE THREAD

**Issue by esco** [vektra/mockery#114]
The `-output` flag only accepts a base dir. It'd be useful if we could also provide basedir+filename. If the value ends in .go, it could use that as the full output path. Happy to make a pull request if this is something thats wanted.

**Comment by rayzyar** [comment]
I think it is because it supports generating multiple files at a time, I hope that the generated file could have a .mock.go suffix for tools to recognize it easily

**Comment by evanphx** [comment]
Please go ahead and write up the PR.
