### ISSUE TITLE
Cannot generate mock for interface: string literal not terminated

### ISSUE THREAD

**Issue by yuderekyu** [vektra/mockery#119]
I've been trying to generate mock interfaces, but have been running into issues.

My interface (SubscriptionI) builds just fine, but fails when trying to generate a mock. 

```golang
type SubscriptionI interface {
	GetByID(string) (*models.Subscription, error)
	GetAll(int, int) ([]*models.Subscription, error)
	GetByRoaster(string, int, int) ([]*models.Subscription, error)
	GetByUser(string, int, int) ([]*models.Subscription, error)
	Insert(*models.Subscription) error
	Update(string, *models.Subscription) error
	SetStatus(string, models.SubscriptionStatus) error
	Delete(string) error
}
```
I get the error:
>Generating mock for: SubscriptionI
>Error walking SubscriptionI: mock.go:3:16: string literal not terminated (and 9 more errors)

Is it possible there is some parsing error?

**Comment by codeactual** [comment]
Hi @yuderekyu,

I feel like I've seen that error before but I can't recall what triggered it. Can you provide the CLI flags that were used, golang version, and the partially generated mock (if one was output)?

**Comment by yuderekyu** [comment]
CLI flags: `mockery -dir=helpers -name=SubscriptionI -output=./_mocks/handlers`
Version: `go1.7.3 windows/amd64`

Mockery generates a blank `SubscriptionI` in the desired output folder, `_mocks/handlers`.

**Comment by codeactual** [comment]
Thanks for the info.

> Is it possible there is some parsing error?

I think that's correct and may be related to what's reported in #14. `imports` is used to fix the imports just before the mock is written to file, on [generator.go L552](https://github.com/vektra/mockery/blob/53e21da5f9d000ffafde06fec5e5ab169a5c42c6/mockery/generator.go#L552), but `imports` encounters bad syntax that `mockery` generated.

I wasn't able to reproduce the problem on `go1.8rc3 linux/amd64` with the provided flags/code and a `models` package with empty structs. My guess is that it's a Windows-specific issue.

It would help to know what [g.buf.String() in Write()](https://github.com/vektra/mockery/blob/53e21da5f9d000ffafde06fec5e5ab169a5c42c6/mockery/generator.go#L550) looks like on Windows in order to know how to fix the syntax.

**Comment by codeactual** [comment]
@yuderekyu In case you have time to test a patch, #124 may fix address your parsing error.

**Comment by codeactual** [comment]
@yuderekyu Thanks.

> Updated mockery.

To `vektra:master@HEAD` or `codeactual:fix_win_import_paths@HEAD`?

`vektra:master@HEAD` does not yet contain the #124 patch.

If it's `codeactual:fix_win_import_paths@HEAD`, then I still need more help to reproduce the issue. Specifically, I need to know the string content of `g.buf` produced in [Generator.Write()](https://github.com/vektra/mockery/blob/53e21da5f9d000ffafde06fec5e5ab169a5c42c6/mockery/generator.go#L550) just before the error occurs.

Can you add the output of `g.buf.String()` to this thread?

**Comment by yuderekyu** [comment]
Apologies for the lengthy delay. I've tested that patch after it was merged into `vektra:master@HEAD` and am still receiving the error. I've tried printing `g.buf.String` but after compiling, I don't receive a `g.buf.String` output when generating a mock using my previous commands. Does this error, `Error walking SubscriptionI: mock.go:5:16: string literal not terminated (and 9 more errors)` within [Walk](https://github.com/vektra/mockery/blob/master/mockery/walker.go#L30) get thrown before [Write](https://github.com/vektra/mockery/blob/master/mockery/generator.go#L628) is called then? Otherwise I'm misunderstanding the print statement.  
<img width="351" alt="generator" src="https://cloud.githubusercontent.com/assets/14063284/25026683/3eff780a-206d-11e7-9a78-e41da7eaf44a.PNG">

**Comment by codeactual** [comment]
@yuderekyu No problem.

> Does this error, Error walking SubscriptionI: mock.go:5:16: string literal not terminated (and 9 more errors) within Walk get thrown before Write is called then?

Yes, I think that `imports.Process` returns an error and triggers a `return err` before `Write` is called.

[This PR](https://github.com/vektra/mockery/pull/149/commits/f830326fc897c3981eaf8079ca0cf1b3ab232887) what I've been doing to print the `mock.go` source.

**Comment by yuderekyu** [comment]
@codeactual The output of `g.buf.String()` within `Write` is never reached. I don't think `imports.Process` returns the error - isn't the error returned within [parse](https://github.com/vektra/mockery/blob/master/mockery/parse.go#L101) and outputted within [Walk](https://github.com/vektra/mockery/blob/master/mockery/walker.go#L28)?

**Comment by codeactual** [comment]
@yuderekyu 

I think the error message is produced [10 lines later](https://github.com/vektra/mockery/blob/master/mockery/walker.go#L40). Note how L30 would not include the interface name in the message.

Also, it looks like the only function that references `mock.go` is `Generator.Write`.

> The output of g.buf.String() within Write is never reached.

Did you use the code from [the PR](https://github.com/vektra/mockery/pull/149/commits/f830326fc897c3981eaf8079ca0cf1b3ab232887)?

[g.printf](https://cloud.githubusercontent.com/assets/14063284/25026683/3eff780a-206d-11e7-9a78-e41da7eaf44a.PNG) can't be used to print the output. It effectively duplicates the source going into `imports.Process` as `theBytes` and ensuring an error will occur.
