### ISSUE TITLE
get get fails

### ISSUE THREAD

**Issue by m00sey** [vektra/mockery#120]
Hey,

I'm trying to pulling mockery for the first time, and I get the following error:

` go get github.com/vektra/mockery/.../`

```
# github.com/vektra/mockery/mockery
src/github.com/vektra/mockery/mockery/parse.go:39: conf.TypeChecker.Importer undefined (type "golang.org/x/tools/go/types".Config has no field or method Importer)
src/github.com/vektra/mockery/mockery/parse.go:77: cannot use pkgInfo.Pkg (type *"golang.org/x/tools/go/types".Package) as type *"go/types".Package in append
```

`go version go1.6.2 linux/amd64`

**Comment by m00sey** [comment]
Something conflicting in the existing project I guess, pulled into an empty work space fine.

**Comment by jwilander** [comment]
For anyone running into this issue, I had an old copy of `golang.org/x/tools/go/type` hanging around. Removing that fixed it
