### ISSUE TITLE
Panic from zero-arg function call

### ISSUE THREAD

**Issue by buchanae** [vektra/mockery#122]
The interface is something like:
```go
type Database interface {
  CheckWorkers() error
}
```

The code generated is:
```go
func (_m *Database) CheckWorkers() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
```

And running the tests give an unwanted panic
```
panic: assert: arguments: Cannot call Get(0) because there are 0 argument(s). [recovered]
	panic: assert: arguments: Cannot call Get(0) because there are 0 argument(s).
```

Possibly I'm doing something wrong?

**Comment by evanphx** [comment]
That's not the code that I see generated by the current version of mockery. Could you update or make sure that it's picking up the proper interface? The interface there appears to be one for `CheckWorkers() error`.

**Comment by buchanae** [comment]
I did update mockery this evening. If you add "error" to the interface does
the code match and panic?

Sorry I quickly copied and pasted the example code from a larger code base,
but I will provide a more isolated test case.

**Comment by buchanae** [comment]
I did isolate this into a clean source tree and ensured I was using the latest version of mockery. The generated code did match the previously generated code, but I couldn't reproduce the bug.

Further, if I change the code with the bug to include `dbMock.On("CheckWorkers").Return(nil)` (I added `nil`), the panic goes away.

So, I'm a bit confused about the behavior. I'll dig into it again soon.

**Comment by buchanae** [comment]
Oh, I think I understand that the problem was that I was calling `Return()` with no arguments when the interface defines a return value of `error`.

Not sure why I couldn't reproduce the issue in the isolated codebase though, where I was still calling `Return()` with no arguments.

**Comment by evanphx** [comment]
Ok, sounds like it's just a mismatch in using the mock library.
