### ISSUE TITLE
Error: unknown escape sequence 

### ISSUE THREAD

**Issue by Gyga8K** [vektra/mockery#126]
The program create the mock folder and inside create PostStorage.go document, but the document is in blank.

**OS: Wndows 10
Console: GitBash**

**Comand:** 
mockery -name='PostStorage'

**Result:**

Generating mock for: PostStorage

Error walking PostStorage: mock.go:4:25: unknown escape sequence (and 2 more errors)

**This is the interface:**

```
type PostStorage interface {
	Create(post *Post) error
	Update(post *Post) error
	Delete(post *Post) error
	GetAll() (Posts, error)
	GetById(post *Post) error
	GetBySlug(post *Post) (bool, error)
	GetByTitle(post *Post) (bool, error)
	GetByTag(post *Post) (Posts, error)
	GetByCategoryId(post *Post) (Posts, error)
	GetByStatus(status int) (Posts, error)
	GetByAuthor(post *Post) (Posts, error)
	SearchByTitle(post *Post) (Posts, error)
	SearchByDate(from, until time.Time) (Posts, error)
	SetID(post *Post, id string) error
}

```

**Comment by codeactual** [comment]
@Gyga8K PR #124 may resolve this. It is available on https://github.com/codeactual/mockery in branch [fix_win_import_paths](https://github.com/vektra/mockery/compare/master...codeactual:fix_win_import_paths).

**Comment by codeactual** [comment]
@Gyga8K A fix for this is now in master.
