### ISSUE TITLE
assert: arguments: Cannot call Get(1) because there are 1 argument(s).

### ISSUE THREAD

**Issue by jaytaylor** [vektra/mockery#128]
Hi,

I've generated a mock of the S3API, and immediately hit errors upon attempting to apply mock method overrides:

```bash
$ go test -v ./...
=== RUN   TestS3Mock
--- FAIL: TestS3Mock (0.00s)
panic: assert: arguments: Cannot call Get(1) because there are 1 argument(s). [recovered]
	panic: assert: arguments: Cannot call Get(1) because there are 1 argument(s).

goroutine 20 [running]:
panic(0x3eac80, 0xc4201707f0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc42009e180)
	/usr/local/go/src/testing/testing.go:579 +0x25d
panic(0x3eac80, 0xc4201707f0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/stretchr/testify/mock.Arguments.Get(0xc420170580, 0x1, 0x1, 0x1, 0x3fe580, 0x4e8760)
	/Users/jtaylor/go/src/github.com/stretchr/testify/mock/mock.go:537 +0x19b
github.com/jaytaylor/mockery-example/mocks.(*S3API).ListObjects(0xc4200774c0, 0xc420077500, 0x1, 0x1, 0xc42016ef50)
	/Users/jtaylor/go/src/github.com/jaytaylor/mockery-example/mocks/S3API.go:3491 +0x123
github.com/jaytaylor/mockery-example.TestS3Mock(0xc42009e180)
	/Users/jtaylor/go/src/github.com/jaytaylor/mockery-example/main_test.go:46 +0x2a0
testing.tRunner(0xc42009e180, 0x4e8768)
	/usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x2ec
FAIL	github.com/jaytaylor/mockery-example	0.227s
?   	github.com/jaytaylor/mockery-example/mocks	[no test files]
```

Mockery appears to generate invalid mock code which references parameter fields which flat out don't exist, and ultimately trigger panics.

Full runnable source code: https://github.com/jaytaylor/mockery-example

**Comment by codeactual** [comment]
Hi,

It looks like the `mocks` dir wasn't uploaded, so we can't see the generated `mocks/S3API.go:3491`: https://github.com/jaytaylor/mockery-example/blob/master/main_test.go#L8

Also, what were the CLI flags used?

Thanks.

**Comment by jaytaylor** [comment]
Yep I thought the same, fixing now.

**Comment by jaytaylor** [comment]
Is now fixed.

**Comment by codeactual** [comment]
Thanks for that and the repo in general. I haven't seen someone do that before, very helpful!

I was able to reproduce the error and resolve it by adding a `nil` as the 2nd parameter to the `Return()` call. `mockery` knows that `ListObjects` returns two variables, so it calls `Get(1)` which fails to find the 2nd.

**Comment by jaytaylor** [comment]
@codeactual Thanks, so this is a case of [pebkac](https://en.wikipedia.org/wiki/PEBKAC).  Thanks for your help.  I'll open a PR with more example usages in the README.

https://github.com/vektra/mockery/pull/130
