### ISSUE TITLE
Mockery Walker visiting ignored directories and files

### ISSUE THREAD

**Issue by andymc904** [vektra/mockery#131]
Walker doesn't skip ignored directories.

```go
if strings.HasPrefix(file.Name(), ".") {
	continue
}
```

Should skip directories and files starting with `_` should be ignored
see https://golang.org/pkg/go/build/#Context.Import

**Comment by codeactual** [comment]
> Should skip directories and files starting with _ should be ignored
see https://golang.org/pkg/go/build/#Context.Import

Good point. 

BTW, Github now supports quick PRs via the pencil icon when viewing a specific file. https://github.com/vektra/mockery/blob/master/mockery/walker.go should be right one.

**Comment by evanphx** [comment]
Fixed by #132
