### ISSUE TITLE
proposal: add spinner to cli output while loading files

### ISSUE THREAD

**Issue by tamccall** [vektra/mockery#136]
If there are many files to parse this function can take quite a while to return. Suggestion is to modify code to print spinner to cli so users don't get impatient

https://github.com/vektra/mockery/blob/master/mockery/parse.go#L101-L131

There are packages that provide such functionality. Such as https://github.com/briandowns/spinner

But unsure of the policy on using external packages

**Comment by codeactual** [comment]
I agree with this UX concern, having felt a "what's going on?" impatience while it processes stuff.

An efficient approach might be the `-v`/`-verbose` behavior of many tools, including go's: in verbose mode, print the file/package/etc about to be processed. It answers the "what's going on?" question, offers visual progress, and spares a dependency.

If `-print` is also enabled, a compromise might be that verbose output is not supported or instead directed to `os.Stderr`. Perhaps `os.Stderr` is the place for it generally, I'm not sure what the conventions are.

**Comment by kingofsouth** [comment]
Since the `-print` feature exists any additional program output that we implement will need to be directed to `os.Stderr`

**Comment by kingofsouth** [comment]
One other thought on `-v` option: the work in the package is incredibly middle-loaded. Most of the time is spent is in the `Load` function of the parser (on the order of seconds even for a modestly sized package like this) which is effectively one step, so I'm worried adding the intermediate steps wont really alleviate feelings of impatience. That said, whether or not we add external deps, we should seriously consider wrapping that bit of code with some amount of UX to contend with the long latency of that function

**Comment by codeactual** [comment]
When I'm impatient about program being a slowpoke, I want:

1. To know why.
1. Maybe to know how much longer I have to wait.
1. To somehow avoid it in the future.

`#3` is ideal but I'll settle for `#1` or `#2` if that's all I can get.

As you described, the `Load` bottleneck means insufficient steps for granular `#1` or`#2` feedback. And if it's the only way to collect the necessary data for generation, `#3` is unlikely to happen anytime soon.

The shortcoming of a spinner is that it doesn't give us `#1`. It only communicates that "something is happening." 

This also communicates that something is happening: `Parsing /path/to/some/interface.go ...`

I think this tool's audience just needs a little more info about what's happening so their expectations are informed and maybe a little more tolerant next time. "Parsing X," "Walking the AST of X", etc. -- I think some verb and ellipses are enough to communicate that something is happening (and `#1`). I'm just not convinced they need a visual that only aims to distract.

**Comment by evanphx** [comment]
I'm happy to provide better progress output. I'd be happy to include a spinner that is enabled with a `-progress` flag.

**Comment by kingofsouth** [comment]
@codeactual  @evanphx do we prefer a `-progress` flag or a `-verbose` / `-v` flag? I prefer the latter but that is just me.

**Comment by codeactual** [comment]
I've blabbed enough in this issue. ;)

I'd probably defer to what something like `curl` does, which at least on mac has both `verbose/v` and `progress-bar`, since I don't really have a strong opinion.

Latter seems fine.

**Comment by briandowns** [comment]
@codeactual It was mentioned above that you want to know why a program might be running slow.  The spinner library will allow you to provide feedback to the user.  Number 2 is doable using the same method as well.  I'd be happy to make any (non breaking) adjustments necessary if it means easier use.

```
package main

import (
	"time"

	"github.com/briandowns/spinner"
)

func main() {
	s := spinner.New(spinner.CharSets[9], time.Duration(time.Millisecond*100))
	s.FinalMSG = "Complete!\n"
	s.Start()
	// simulate work
	time.Sleep(time.Second * 5)
	// detect something fishy.
	// set a message for the user
	s.Suffix = " processing runnning slow..."
	// simulat more work
	time.Sleep(time.Second * 5)
	// let the user know things are fine.  ... or not.
	s.Suffix = " normal"
	// simulat work
	time.Sleep(time.Second * 5)
	s.Stop()
}
```

**Comment by codeactual** [comment]
@briandowns I think everyone who's commented wants to "provide feedback." There was just disagreement about the form/function of that feedback.

Evan has [already mentioned](https://github.com/vektra/mockery/issues/136#issuecomment-302897436):

> I'm happy to provide better progress output. I'd be happy to include a spinner that is enabled with a -progress flag.

So if you or @tamccall drop a PR, I bet things can move forward in the direction you've described.

**Comment by tamccall** [comment]
@briandowns I would probably want to get this pr finished before we start working on that. https://github.com/vektra/mockery/pull/138

I wouldn't want to start pulling in external deps without a way to manage that.

**Comment by LandonTClipp** [comment]
Closing historic ticket. Please open a new one if you still have issues.
