### ISSUE TITLE
mockery -all failing on windows OS

### ISSUE THREAD

**Issue by dhawal55** [vektra/mockery#14]
When i try to generate mocks for my project on a windows box, I get the below error:
mockery -all
Error writing XXXX: mock.go:3:27: unknown escape sequence

**Comment by evanphx** [comment]
You'll have to narrow it down and show me one of your files that cause the problem. I don't have anything to go on.

**Comment by paulshir** [comment]
This is an issue and is due to the filepath in windows using a '\' instead of '/'. It means that the generated package imports have a backslash in them and causes the import.process to fail.

To workaround you could try using -fIP.

**Comment by arekkas** [comment]
`-fIP` workaround does not work. @evanphx it doesn't matter which file it is, none of them work.

**Comment by connor4312** [comment]
I'm also getting this, working in cygwin and govendor.

```
{ api } quorum-1 » mockery -case=underscore -name=Connection -print             
Error walking Connection: mock.go:3:24: unknown escape sequence (and 1 more errors)

{ api } quorum-1 » find ../../ -name mock.go                                 
../../vendor/github.com/stretchr/testify/mock/mock.go
```

**Comment by codeactual** [comment]
@connor4312 In case you have time to test a patch, #124 may fix your error.
