### ISSUE TITLE
Regression in mock generation

### ISSUE THREAD

**Issue by curtisallen** [vektra/mockery#141]
It looks like https://github.com/vektra/mockery/pull/133/commits/81f429d47bc8fa3d20e4136c270b6d3a12a44324 introduced a regression. Causing import cycles in generated mocks.

Given 

`foo/foo.go`
```go
package foo

type Data struct {
}

type Foo interface {
	Something() Data
}
```
The generated mock produces an import cycle using e4fa388

```console
mockery -name=Foo -dir=foo -inpkg
```
Generates a mock with
`foo/mock_Foo.go`
```go
import foo "github.com/curtisallen/mockery-bug/foo"
...
// Something provides a mock function with given fields:
func (_m *MockFoo) Something() foo.Data {
	ret := _m.Called()

	var r0 foo.Data
	if rf, ok := ret.Get(0).(func() foo.Data); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(foo.Data)
	}

	return r0
}
```

However using `370e224` the mock generated doesn't have an import cycle. 

I've created a repo demonstrating the bug  https://github.com/curtisallen/mockery-bug
See [correct mock](https://github.com/curtisallen/mockery-bug/blob/master/foo/GOOD370e224_mock_Foo.go)
Import cycle [mock](https://github.com/curtisallen/mockery-bug/blob/master/foo/mock_Foo.go)

cc:/ @kingofsouth

**Comment by kingofsouth** [comment]
I found this same issue at work a few days ago.  I have a change locally to fix it [here](https://github.com/kingofsouth/mockery/tree/inpkg-bug), but I want to write some tests to ensure it doesn't happen again.

**Comment by curtisallen** [comment]
Great thanks!

**Comment by kingofsouth** [comment]
I went ahead and put up a pr for my fix in an attempt to get master back into a good state,

Haven't been able to repro in unit testing yet

**Comment by kingofsouth** [comment]
@evanphx Could https://github.com/vektra/mockery/issues/143 get a review this issue has been open for quite awhile, and the tip of master is currently broken.

**Comment by wolfgangmeyers** [comment]
[smashingpumpkins.zip](https://github.com/vektra/mockery/files/1005141/smashingpumpkins.zip)
I've attached an easy reproduction scenario for this issue, which I believe is the same one I've run into. If not let me know and I'll open up a new one :)

**Comment by kingofsouth** [comment]
@curtisallen https://github.com/vektra/mockery/pull/143 was merged in today. Try getting the newest version from master and see if you are still having issues.

**Comment by curtisallen** [comment]
Thanks, @kingofsouth , yup HEAD works as expected. Closing
