### ISSUE TITLE
Mocking interfaces in main namespace

### ISSUE THREAD

**Issue by warmans** [vektra/mockery#15]
Hi, 

I don't know if this is a stupid question or not but is it possible to generate mocks into a mocks "subpackage"  when your interfaces are in main? 

e.g.

main.go
```go
package main

type Something struct {
}

type MyInterface interface {
     DoSomething() Something //return main.Something
}

func main() {
}
```
Will generate something like:

mocks/MyInterface.go
```go
package mocks

import "github.com/stretchr/testify/mock"
import "github.com/warmans/example" //tries to import main

type MyInterface struct {
   mock.Mock
}

func (m *MyInterface) DoSomething() main.Something {
    //...
    return main.Something
}

```

which means the test looks like this:

main_test.go
```go
package main

import (
    "testing"
    "github.com/warmans/example/mocks" //import the mocks subpackage
)

func TestDoSomethingDoesSomething() {
    mock = new(mocks.MyInterface) //create the mock
}
```

Couple of issues: there is import recursion  which causes a `import cycle not allowed in test` error. Also Go seems to be a bit funny about importing and using main anyway.

I am able to work around the problem by supplying the `inpkg=true` flag but it seems cleaner to have the mocks subpackage.

Thanks

**Comment by evanphx** [comment]
There is simply not way to handle this other than using `inpkg`, other than you don't put everything in the `main` namespace. So either just use `inpkg` or reorg the code to not use `main` (I only put the bare minimum in main).
