### ISSUE TITLE
Add `Code generated by ....` as a comment

### ISSUE THREAD

**Issue by bsdlp** [vektra/mockery#150]
https://github.com/github/linguist/blob/461c27c066ecc9107ed7c0cc9107a7ffa0f50600/lib/linguist/generated.rb#L262-L267

It would be nice if first line of the generated file contained a comment with these words in order to have github recognize that it is an code generated file and thus hide it from diffs, etc.

**Comment by kingofsouth** [comment]
This likely would be fixed by https://github.com/vektra/mockery/pull/140.

I need to make sure that the comment ends up on line 0

**Comment by kingofsouth** [comment]
Have confirmed that the files are not shown in the diff on github. Just need for that PR to be merged.

**Comment by kingofsouth** [comment]
@bsdlp this the change to allow this was merged yesterday. Try updating from master to see if this issue can be closed.
