### ISSUE TITLE
Cannot mock functions that accept funcs as parameters

### ISSUE THREAD

**Issue by dominicbarnes** [vektra/mockery#151]
I'm generating a mock for the ECS API, which has a couple methods that accept a func used for pagination. I've generated the mock using mockery, but I get this panic when I try to write a test with an assertion:

```
panic: cannot use Func in expectations. Use mock.AnythingOfType("func(*ecs.ListClustersOutput, bool) bool")

goroutine 77 [running]:
panic(0x4355a0, 0xc42051b230)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc4200a3d40)
        /usr/local/go/src/testing/testing.go:579 +0x25d
panic(0x4355a0, 0xc42051b230)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/stretchr/testify/mock.(*Mock).On(0xc4204b9a80, 0x4f8ade, 0x11, 0xc4201f9020, 0x2, 0x2, 0x0)
        /Users/dominic/dev/src/github.com/stretchr/testify/mock/mock.go:201 +0x155
github.com/segmentio/ecs-blox.TestClientListClustersPages(0xc4200a3d40)
        /Users/dominic/dev/src/github.com/segmentio/ecs-blox/client_test.go:641 +0xf0
testing.tRunner(0xc4200a3d40, 0x53a048)
        /usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:646 +0x2ec
```

Here is the relevant mock that was generated:

```go
// ListClustersPages provides a mock function with given fields: _a0, _a1
func (_m *ECSAPI) ListClustersPages(_a0 *ecs.ListClustersInput, _a1 func(*ecs.ListClustersOutput, bool) bool) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*ecs.ListClustersInput, func(*ecs.ListClustersOutput, bool) bool) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
```

Based on the error, it sounds like line 3 should look like:

```go
ret := _m.Called(_a0, mock.AnythingOfType("func(*ecs.ListClustersOutput, bool) bool"))
```

But then again, it looks like mockery generated code that attempts to grab a func out of the 1st return value, which doesn't look right either. (but this is probably unrelated to the original error)

**Comment by dominicbarnes** [comment]
Actually, sorry I think this is my fault. I needed to pass the `mock.AnythingOfType` in my `mock.Called()` setup.

**Comment by etsangsplk** [comment]
@dominicbarnes 
Saw this issue. I am going through the same thing. I also use ListClustersPages to iterate through pages of returned results, but ListClustersPages requires a lastPage (of type bool, the argument I bold typed) to signal the cursor to stop, which is the anonymous function that is second parameter which right now is just 
mock.AnythingOfType("func(*ecs.ListClustersOutput, **bool)** bool"))

The tests go into infinite loop becasue there is nothing to signal the cursor to stop.
