### ISSUE TITLE
Embedded interface outputs self-referential import

### ISSUE THREAD

**Issue by mitchellh** [vektra/mockery#154]
In `foo.go`:

```
type A interface {
    A()
}

type B interface {
    A

    B()
}
```

Running

```
//mockery -inpkg -name=B
```

Produces an import of the package A is in, resulting in a compiler error.

**Comment by kingofsouth** [comment]
This is likely just another instance of [this bug](https://github.com/vektra/mockery/issues/141). Try my branch [here](https://github.com/kingofsouth/mockery/tree/inpkg-bug) I believe it will fix your issue

**Comment by kingofsouth** [comment]
Looks like we were merged to master today. Try updating mockery and see if the bug persists.

**Comment by evanphx** [comment]
Yup! Please recheck.

Also, @kingofsouth, THANK YOU SO MUCH! All the PRs were wonderful!
