### ISSUE TITLE
Prologue note creates lint artefacts

### ISSUE THREAD

**Issue by Willyham** [vektra/mockery#155]
With the addition of the prologue note, the generated code no longer passes standard for godoc:

```
   Error  (GOLINT) GOLINT
    Package comment should be of the form "Package mocks ..."

    >>>        1 // Code generated by mockery v1.0.0
               2 package mocks
               3 
               4 import mock "github.com/stretchr/testify/mock"
```

I would suggest changing to:

    Package mocks contains mocks generated by mockery [version]

**Comment by kingofsouth** [comment]
If we want the diff to be suppressed in github. We need to have that comment say `Code generated by`, 

https://github.com/github/linguist/blob/master/lib/linguist/generated.rb#L262-L267
https://github.com/vektra/mockery/issues/150

FWIW my preference would be for github suppression.

**Comment by Willyham** [comment]
Looks like we can achieve both with:

    Package mocks contains generated mocks. Code generated by mockery v....

Not very robust, but neither are likely to change. That work ok?

**Comment by nmiyake** [comment]
The other option would be to simply introduce a newline between the comment and the "package" declaration.

That is, instead of:

```go
// Code generated by mockery v1.0.0
package mocks
```

Have:

```go
// Code generated by mockery v1.0.0

package mocks
```

**Comment by kingofsouth** [comment]
I prefer option 2.

**Comment by Willyham** [comment]
That is definitely better. Will update

**Comment by nathany** [comment]
This could be addressed by `golint` itself.

https://github.com/golang/lint/commit/a5f4a247366d8fc436941822e14fc3eac7727015

That fix in golint has additional requirements on the comment.

```
// Code generated by mockery v1.0.0
```

needs to become

```
// Code generated by mockery v1.0.0 DO NOT EDIT.
```

At that point lint will completely ignore the mocks, whereas the proposal at https://github.com/vektra/mockery/issues/155#issuecomment-304092307 should get the lint passing again.

**Comment by nathany** [comment]
See also: https://github.com/golang/go/issues/13560#issuecomment-276866852 proposal: build: define standard way to recognize machine-generated files

> The comment must match the regular expression (in Go syntax):
> `^// Code generated .* DO NOT EDIT$'

**Comment by uudashr** [comment]
Any progress? I've seen long discussion but no merged PR for the fix

**Comment by jborlum** [comment]
Friendly ping. It would be nice to get some fix merged soonish.

**Comment by LandonTClipp** [comment]
Closing historic ticket. Please open a new one if you still have issues.
