### ISSUE TITLE
Non-deterministic failure of mocked function

### ISSUE THREAD

**Issue by Willyham** [vektra/mockery#159]
In a new package:

```golang
package mocktest

type Fooer interface {
	Foo(int) error
}

//go:generate mockery -name Fooer -case underscore
```
and test:
```golang
func TestFoo(t *testing.T) {
	mockFoo := &mocks.Fooer{}
	mockFoo.On("Foo", mock.Anything).Return(nil).Twice()
	mockFoo.On("Foo", mock.Anything).Return(assert.AnError).Once()

	errs := 0
	wg := sync.WaitGroup{}
	wg.Add(3)

	for i := range []int{0, 1, 2} {
		go func(idx int) {
			err := mockFoo.Foo(idx)
			if err != nil {
				errs++
			}
			wg.Done()
		}(i)
	}

	wg.Wait()
	assert.Equal(t, errs, 1)
}

```

Run with:
```bash
 $ for i in `seq 1 100`; do go test ./mocktest/ -run TestFoo; done
```
Sometimes fails:

```
--- FAIL: TestFoo (0.00s)
        Error Trace:    foo_test.go:37
	Error:		Not equal: 0 (expected)
			        != 1 (actual)
```

From debugging it looks like `_m.Called` actually returns `nil` 3 times. This leads me to believe that there is a race condition around `Repeatability` at some point. Changing to this:

```golang
	mockFoo.On("Foo", mock.MatchedBy(func(i int) bool { return i < 2 })).Return(nil).Twice()
	mockFoo.On("Foo", 2).Return(assert.AnError).Once()
```

Results in no failures. Being more specific about those matches is probably always recommended anyway, but I didn't expect mockery to cause a fail even in the other case.

**Comment by codeactual** [comment]
Interesting.

Does adding `-race` to `go test` reveal anything? 

Also, if there's a race on `Repeatability`, I'm not sure if a `mockery` based fix is possible. That state is managed in the `mock` package of https://github.com/stretchr/testify.

**Comment by Willyham** [comment]
Sorry, forgot to mention that `-race` doesn't report anything. Good point about `testify`, I always forget that these are two separate packages. Haven't looked deep enough to rule out `mockery`, but I think its unlikely to be the root cause, so I'll maybe cross post this in testify.

**Comment by Willyham** [comment]
Solved in testify. :)
