### ISSUE TITLE
Code generated by... comment fails lint

### ISSUE THREAD

**Issue by nathany** [vektra/mockery#160]
related: #150

```
mocks/Sender.go:1:1: package comment should be of the form "Package mocks ..."
```

Just FYI. I'll probably exclude the mocks folder from linting to work around this.

**Comment by nathany** [comment]
```go
go list ./... | grep -v -E '/vendor|mocks' | xargs -L1 golint
```

**Comment by Willyham** [comment]
Dupe of #155  :)

**Comment by nathany** [comment]
This could be addressed by `golint` itself.

https://github.com/golang/lint/commit/a5f4a247366d8fc436941822e14fc3eac7727015

**Comment by nathany** [comment]
So upon testing and looking more closely, that fix in golint has additional requirements on the comment.

```
// Code generated by mockery v1.0.0
```

needs to become

```
// Code generated by mockery v1.0.0 DO NOT EDIT.
```

**Comment by nathany** [comment]
closing and posted to #155 instead.

sorry about that.
