### ISSUE TITLE
"Undeclared name: C" error if parsed files use CGO

### ISSUE THREAD

**Issue by codeactual** [vektra/mockery#161]
`mockery.Parser` uses `golang.org/x/tools/go/loader` which does not yet support CGO in files that are loaded "ad-hoc" (versus being `import`-ed).

Progress on that support can be followed here: https://github.com/golang/go/issues/11627.

### Example

- CLI flags: `CGO_ENABLED=1 mockery -name UsesCgo -dir ./uses_cgo -print`
  - Verified that in `NewParser`, `conf.Build.CgoEnabled` is `true`.
  - `CGO_ENABLED=0` produces the same output.

`./uses_cgo/uses_cgo.go`:

```
package uses_cgo

import "C"

// https://github.com/mattn/go-sqlite3/blob/master/error.go use case from https://github.com/vektra/mockery/issues/91#issuecomment-305032021
const ErrNoMask C.int = 0xff

type UsesCgo interface {
        Do()
}
```

Output:

```
$FAKE_PATH/uses_cgo.go:3:8: could not import C (the loader doesn't cgo-process ad hoc packages like "$FAKE_PATH/uses_cgo.go"; see Go issue 11627)
$FAKE_PATH/uses_cgo.go:6:17: undeclared name: C
$FAKE_PATH/uses_cgo.go:6:17: invalid constant type invalid type
Error walking: couldn't load packages due to errors: $FAKE_PATH/uses_cgo.go
```

**Comment by LandonTClipp** [comment]
Closing historic ticket. Please open a new one if you still have issues.
