### ISSUE TITLE
-all sometimes doesn't generate all interfaces

### ISSUE THREAD

**Issue by decibel** [vektra/mockery#166]
I'm generating mocks on a directory that includes these interfaces:

```
type Decrypter interface {
  ...
}
type Setter interface {
  ...
}
type EncryptedPassworder interface {
  Decrypter
  Setter
}
```

the mockery call is

`//go:generate mockery output ../../mocks -dir ../../encrypted_password -all`

For some reason the only mock that is generated is EncryptedPassworder. I guess that's because you could always cast an EncryptedPassworder to either of the smaller interfaces?

**Comment by codeactual** [comment]
@decibel I wasn't able to reproduce it in `go version go1.8.3 linux/amd64`. Can I get your version and maybe more of `Decrypter/Setter`? In my test they just had one function each and were all in the same file -- are they in one file on your env?

**Comment by decibel** [comment]
Huh, it's now working. I guess it was operator error. Sorry for wasting your time!
