### ISSUE TITLE
Docs on mock object api

### ISSUE THREAD

**Issue by ryanmcnamara** [vektra/mockery#168]
The docs provide examples of some you can do instantiated mocks, but don't provide a comprehensive list of the api. 

In particular, pointing to documentation on the `Mock` type: https://github.com/stretchr/testify/blob/master/mock/mock.go#L164
and the `Call` type: 
https://github.com/stretchr/testify/blob/master/mock/mock.go#L31
would be very valuable

**Comment by codeactual** [comment]
@ryanmcnamara Hi Ryan, you can find those docs here: https://godoc.org/github.com/stretchr/testify/mock

`mock` is part of the https://github.com/stretchr/testify project.

**Comment by ryanmcnamara** [comment]
Yup, makes sense. 

I think a link to that object from here would be helpful though
