### ISSUE TITLE
Name conflict

### ISSUE THREAD

**Issue by renatomariscal** [vektra/mockery#170]
I have multiple packages that declares interfaces with the same name, for example:

`package1.MyInterface`
`package2.MyInterface`

When generated, it keeps only one, as `mocks.MyInterface`
In this case would be nice to:

• At least warn
• Add a flag that enables "Add package name as prefix", generating in the example: `mocks.Package1MyInterface`  and `mocks.Package2MyInterface`

**Comment by SeerUK** [comment]
I think this is definitely a handy feature, even when things aren't clashing. If you don't have some script that automatically generates the mocks with some kind of documentation in then it can be difficult to keep track of where `mocks.Client` came from (e.g. `github.Client` or something).

**Comment by corentone** [comment]
@renatomariscal I've made a PR that allows keeping some path:
https://github.com/vektra/mockery/pull/175

I needed to do that for kubernetes mock generation.
