### ISSUE TITLE
How to generate mock for builtin interfaces?

### ISSUE THREAD

**Issue by sivachandran** [vektra/mockery#173]
I want to generate mock for `net.Conn`. If I do `mockery -name net.Conn` then getting `Unable to find net.Conn in any go files under this path`.

How do I generate mock for interfaces in builtin package?

**Comment by tutukin** [comment]
I'd use "go to definition" feature of my IDE to discover where the interface is defined. Then just use `-dir` option.

**Comment by LandonTClipp** [comment]
Closing historic ticket. Please open a new one if you still have issues.
