### ISSUE TITLE
Cannot mock function that uses iterator pattern 

### ISSUE THREAD

**Issue by etsangsplk** [vektra/mockery#178]
Related to https://github.com/vektra/mockery/issues/151

My code is basically the following link:
https://github.com/aws/aws-sdk-go/blob/d41099e55d33fd32290ab6223bfdf83da8693d68/service/s3/api.go#L3878
As you see:
lastPage bool
lastPage as false will stop the iteration that is returned form within the anonymous function to signal termination, true is keep on looping.
lastPage is the second argument bool, and the return bool.

I am using this as mock in test code:
suite.mockS3.On("ListObjectVersionsPages", mock.AnythingOfType("*s3.ListObjectVersionsInput"), **mock.AnythingOfType("func(*ecs.ListClustersOutput, bool) bool")).Return(nil)**

But mocking  func(*ecs.ListClustersOutput, **bool**) bool does not let me set the value of lastPage,a dn when test executes and get called into real code, it will loop forever.

Is there a way to avoid infinite looping.

**Comment by LandonTClipp** [comment]
Closing historic ticket. Please open a new one if you still have issues.
