### ISSUE TITLE
mocks for interfaces with composition are missing methods

### ISSUE THREAD

**Issue by ernesto-jimenez** [vektra/mockery#18]
## Given the following interface:
```go
package test

import "io"

type ReadCloser interface {
        io.Reader
        Close() error
}
```

## Expected:
```go
type ReadCloser struct {
        mock.Mock
}

func (m *ReadCloser) Read(p []byte) (int, error) {
        ret := m.Called(p)

        r0 := ret.Get(0).(int)
        r1 := ret.Error(1)

        return r0, r1
}
func (m *ReadCloser) Close() error {
        ret := m.Called()

        r0 := ret.Error(0)

        return r0
}
```

## Generated:
```go
type ReadCloser struct {
        mock.Mock
}

func (m *ReadCloser) Close() error {
        ret := m.Called()

        r0 := ret.Error(0)

        return r0
}
```

**Comment by ernesto-jimenez** [comment]
Here is the failing test. `composed.go` is the interface declared in the issue.
```go
func TestGeneratorComposed(t *testing.T) {
        parser := NewParser()
        parser.Parse(filepath.Join(fixturePath, "composed.go"))

        iface, err := parser.Find("ReadCloser")

        gen := NewGenerator(iface)

        err = gen.Generate()
        assert.NoError(t, err)

        expected := `type ReadCloser struct {
        mock.Mock
}

func (m *ReadCloser) Read(p []byte) (int, error) {
        ret := m.Called(p)

        r0 := ret.Get(0).(int)
        r1 := ret.Error(1)

        return r0, r1
}
func (m *ReadCloser) Close() error {
        ret := m.Called()

        r0 := ret.Error(0)

        return r0
}
`

        assert.Equal(t, expected, gen.buf.String())
}
```

**Comment by evanphx** [comment]
Yeah, this is a known issue. I'm not sure how deal with it because it requires being able to parse entire packages to find the other interfaces.

**Comment by mariusgrigoriu** [comment]
Also bumping into this issue

**Comment by jchenry** [comment]
:+1:

**Comment by robdaemon** [comment]
I'm starting to tackle this one - I've made progress on the case that the composed interfaces are contained within the same file, but I'll work on the case where it's in a separate package next. See https://github.com/robdaemon/mockery/tree/composed_interface_support for details.

**Comment by evanphx** [comment]
@robdaemon Great! Thanks!

**Comment by ernesto-jimenez** [comment]
Go 1.5 was released this week

`go/types` package [is now part of the standard library][types] and it should allow mockery to get rid of all the AST manipulation and use higher level functions rather than using `go/ast` directly.

It'll require a refactor, but the package should allow to simplify mockery's code and facilitate handling embedded interfaces. Here go some initial pointers from what I've seen about the package so far:

Getting the complete method set for the interface:
  - [func (t *Interface) Complete() *Interface](https://golang.org/pkg/go/types/#Interface.Complete) - Complete computes the interface's method set.
  - [func (t *Interface) NumMethods() int](https://golang.org/pkg/go/types/#Interface.NumMethods)
  - [func (t *Interface) Method(i int) *Func](https://golang.org/pkg/go/types/#Interface.Method)

Getting method details:
  - [func (obj *Func) Name() string](https://golang.org/pkg/go/types/#Func.Name)
  - [func (obj *Func) Type() Type](https://golang.org/pkg/go/types/#Func.Type) - `(*Func).Type()` is always a *Signature
  - [func (s *Signature) Params() *Tuple](https://golang.org/pkg/go/types/#Signature.Params)
  - [func (s *Signature) Results() *Tuple](https://golang.org/pkg/go/types/#Signature.Results)
  - [func (t *Tuple) Len() int](https://golang.org/pkg/go/types/#Tuple.Len)
  - [func (t *Tuple) At(i int) *Var](https://golang.org/pkg/go/types/#Tuple.At)

```go
package main

import (
	"fmt"
	"go/ast"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"log"
)

func main() {
	// Parse a single source file.
	const input = `
package mocked
import "fmt"
import "net/http"
import "io"
type mocked interface {
	fmt.Stringer
	http.Handler
	SetWriter(w io.Writer) error
}
`
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "mocked.go", input, 0)
	if err != nil {
		log.Fatal(err)
	}

	// Type-check a package consisting of this file.
	// Type information for the imported packages
	// comes from $GOROOT/pkg/$GOOS_$GOOARCH/fmt.a.
	conf := types.Config{Importer: importer.Default()}
	pkg, err := conf.Check("mocked", fset, []*ast.File{f}, nil)
	if err != nil {
		log.Fatal(err)
	}

	mocked := pkg.Scope().Lookup("mocked").Type().(*types.Named)
	name := mocked.Obj().Name()
	iface := mocked.Underlying().(*types.Interface).Complete()
	fmt.Printf("Method set of %s:\n", name)
	for i := 0; i < iface.NumMethods(); i++ {
		fn := iface.Method(i)
		fmt.Println("- method", fn.Name())

		sig := fn.Type().(*types.Signature)
		printParams("  - param", sig.Params())
		printParams("  - result", sig.Results())
	}
	fmt.Println()

}

type namer interface {
	Name() string
}

func printParams(prefix string, t *types.Tuple) {
	for i := 0; i < t.Len(); i++ {
		v := t.At(i)
		switch t := v.Type().(type) {
		case *types.Pointer:
			o := t.Elem().(*types.Named).Obj()
			if o.Pkg() == nil {
				fmt.Println(prefix, "*"+o.Name())
			} else {
				fmt.Println(prefix, "*"+o.Pkg().Name()+"."+o.Name())
			}
		case *types.Named:
			o := t.Obj()
			if o.Pkg() == nil {
				fmt.Println(prefix, o.Name())
			} else {
				fmt.Println(prefix, o.Pkg().Name()+"."+o.Name())
			}
		case namer:
			fmt.Println(prefix, t.Name())
		}
	}
}
```
output
```
Method set of mocked:
- method ServeHTTP
  - param http.ResponseWriter
  - param *http.Request
- method SetWriter
  - param io.Writer
  - result error
- method String
  - result string
```

[types]: https://golang.org/doc/go1.5#go_types

**Comment by ryanwalls** [comment]
Would love to see this implemented.  Running into this as well.

**Comment by simplyianm** [comment]
bump :+1:

**Comment by natdm** [comment]
Is this closed as fixed? It doesn't seem to be working for me.

**Comment by 3tbraden** [comment]
Same here still bumping into this on the latest release [v2.0.0-alpha.13](https://github.com/vektra/mockery/releases/tag/v2.0.0-alpha.13). Any update?
