### ISSUE TITLE
Publish docker image

### ISSUE THREAD

**Issue by pavolloffay** [vektra/mockery#180]
Hi all, 

thanks for the awesome tool! Could you please publish docker images with this binary? It simplifies dev and CI usage.

**Comment by evanphx** [comment]
I'm not sure why that's needed. If you're developing Go it's trivial to install.

**Comment by rogchap** [comment]
Speed is why it's needed; you don't want to have to install mockery on every CI build, but rather have a cached version of the tool on the docker image.

**Comment by LandonTClipp** [comment]
Closing historic ticket. Please open a new one if you still have issues.

**Comment by rogchap** [comment]
It’s not been resolved with an appropriate answer @LandonTClipp; Would like to see a better reason to close, as an “offical” docker image is still required.

**Comment by LandonTClipp** [comment]
Okay, looking back at this I think it'd be a good idea, however I don't have a lot of spare cycles to get this done at the moment. If you could submit code that would be great, then I could integrate with CI etc (which is still on my TODO list).

**Comment by rogchap** [comment]
@LandonTClipp I can help put this together; including helping with CI. I recommend using [goreleaser](https://goreleaser.com/); which I can add as part of my PR.

**Comment by LandonTClipp** [comment]
@rogchap goreleaser looks like a great option, could you add that in a separate PR to your docker PR? I will add any appropriate secrets into Travis.

**Comment by rogchap** [comment]
@LandonTClipp please take a look at #257

**Comment by LandonTClipp** [comment]
@rogchap your goreleaser PR is now working, we can tackle publishing docker images now. I assume this is an option supported by goreleaser?

**Comment by rogchap** [comment]
Great, thanks @LandonTClipp 
Yes, adding docker will be straight forward now.
I also recommend adding a homebrew package. We can use a seperate repo for the tap. (Maybe as a seperate PR)

I noticed that the CI is trying to deploy 4 times because we are running in each Go env and after the first deployment the others fail. The easiest way to fix this is to only run with 1 Go environment (1.14).

**Comment by LandonTClipp** [comment]
Yep I noticed that as well, you were right before, I think we should just
specify a single go version. Now there's a race between the builds to
upload the files to the release.

Regards,

--
Landon Clipp

**Comment by rogchap** [comment]
We can still run the tests on all versions, but I’ll pin the deployment to just Go 1.14. PR incoming.
