### ISSUE TITLE
mockery does not work with type alias

### ISSUE THREAD

**Issue by yiminc** [vektra/mockery#181]
golang 1.9 introduce the type alias feature.
mockery is not able to generate mock for interface that is defined as alias of another interface.

**Comment by cpenner-va** [comment]
Any updates on this?

**Comment by LandonTClipp** [comment]
Closing historic ticket. Please open a new one if you still have issues.

**Comment by LandonTClipp** [comment]
Please use [this feature](https://vektra.github.io/mockery/features/#replace-types) to get around the issue of the golang AST parser not retaining type alias information.
