### ISSUE TITLE
Add "DO NOT EDIT." to generated sources as per convention

### ISSUE THREAD

**Issue by danielbprice** [vektra/mockery#183]
As per https://github.com/golang/go/issues/13560, golint and other tools will now skip files which are generated, assuming the files are marked as such.

mockery doesn't do this, and, at least for me, generated source fails lint.

So:

```
// Code generated by mockery v1.0.0
```

Just needs to be:

```
// Code generated by mockery v1.0.0. DO NOT EDIT.
```

**Comment by maja42** [comment]
I just wanted to create the same issue. It's a bit annoying that the header is not correctly set.

**Comment by AlekSi** [comment]
#188 was merged. @danielbprice please close this issue.

**Comment by danielbprice** [comment]
Thanks!
