### ISSUE TITLE
Generate mock which implements multiple interfaces

### ISSUE THREAD

**Issue by jonathanbp** [vektra/mockery#187]
Is it possible to generate a mock that implements multiple interfaces?

**Comment by AlexanderFadeev** [comment]
Example
```
type Foo interface {}
type Bar interface {}
```
All you need to do is to define ```type FooBar interface {}``` and generate mock for it.

**Comment by jonathanbp** [comment]
Sure, doesn't really answer the question though ;)

**Comment by euskadi31** [comment]
Any news ?

**Comment by LandonTClipp** [comment]
Closing historic ticket. Please open a new one if you still have issues.
