### ISSUE TITLE
Non-pointer struct return turns into pointer in mock

### ISSUE THREAD

**Issue by mitchellh** [vektra/mockery#193]
Given this interface:

```go
type B struct{}

type A interface {
  Call() (B, err)
}
```

The resulting mock has this:

```go
Call() (*B, err)
```

It should not be a pointer. 😉

**Comment by LandonTClipp** [comment]
Closing historic ticket. Please open a new one if you still have issues.

**Comment by ahcarpenter** [comment]
Just ran into this issue today @LandonTClipp
