### ISSUE TITLE
File names for -inpkg=true mocks should have the _test suffix

### ISSUE THREAD

**Issue by ernesto-jimenez** [vektra/mockery#20]
When generating an interface with `-inpkg=true` the generated file name is not suffixed with `_test`, which means the mock is always built.

The expected behaviour would be to add the `_test` suffix so the mock is only built for testing.

**Comment by evanphx** [comment]
The reason not to do that is that it means that you can no longer specify a specific test file `go test blah_test.go` that uses a Mock because go will not import the other test files. For this behavior, we'd need a flag to turn it on, so the user opts into the behavior.
