### ISSUE TITLE
Generated import path contain "vendor" on Windows

### ISSUE THREAD

**Issue by welemon** [vektra/mockery#203]
latest mockery tool generated mock go file wrongly on Windows OS.
The import path shall contain "vendor" folder and cause test phase build error.
For example:
`import bolt "github.com/welemon/vendor/github.com/boltdb/bolt"`
lead to build error
`mocks\db.go:4:8: must be imported as github.com/boltdb/bolt`

This issue does not exist on Mac / Linux.
After quick check, I think the issue is because of "generator.go" line 180
`directories := strings.Split(path, string(filepath.Separator))`
The function is intended to remove the "vendor" and fix the import path.
But `path` var could already contains only slash ('/'), not backslack('\\') on Windows.
Using `filepath.Separator` here will cause the `path` not tokenize correctly.
This also explain why only happen on Windows.

I tested with changing the `filepath.Separator` to slash, will fix the generated mock file.

Please fix this issue so that mockery can work on Windows properly? Thanks.

**Comment by LandonTClipp** [comment]
Hey, thanks for sending in the issue. Please submit a PR and we can get this merged.

**Comment by cretz** [comment]
@LandonTClipp - Is this issue still valid? If so, can you leave it open so others that experience it can see it is a known issue instead of closing it asking for PR?

**Comment by LandonTClipp** [comment]
Yeah that's fine we can keep this open.

**Comment by LandonTClipp** [comment]
Hi, v1 is not supported anymore, closing this ticket. Please open a separate ticket if you still experience this issue. Thanks!
