### ISSUE TITLE
Support Stubs

### ISSUE THREAD

**Issue by bloudraak** [vektra/mockery#204]
Consider the following interface

```
type Logger interface {
	Enabled(level LogLevel) bool
	LogFunc(level LogLevel, eventId EventId, state interface{}, err error, formatter LogFunc)
	Log(level LogLevel, eventId EventId, err error, format string, args ...interface{})
	LogCritical(eventId EventId, err error, format string, args ...interface{})
	LogError(eventId EventId, err error, format string, args ...interface{})
	LogInformation(eventId EventId, err error, format string, args ...interface{})
	LogWarning(eventId EventId, err error, format string, args ...interface{})
	LogDebug(eventId EventId, err error, format string, args ...interface{})
	LogTrace(eventId EventId, err error, format string, args ...interface{})
}
```

I generated a mock for it using 

```
mockery.exe -dir .. -all -case=underscore -inpkg
```

And use it in my tests as follows:

```
logger := &mocks.Logger{}
logger.On("LogInformation", nil, nil, "Scanning '%s'", basePath)
logger.On("LogInformation", nil, nil, "Scanned '%s'", basePath)
loggerFactory := &mocks.LoggerFactory{}
loggerFactory.On("CreateLogger", "Joernaal").Return(logger, nil)
```

Naturally, logging is important, so there is plenty of it in the code. That said, explicitly mocking each call to the logger is can be very tedious and labor intensive. It also makes tests a bit more brittle, especially when you have hundreds or thousands of tests. 

Is there a way to stub the entire class such that all calls to its methods are ignored, and the number of parameters passed doesn't really matter? Some may argue that it defeats some part of the unit test, but a balance must be struck between test coverage and maintainability. 

I was thinking about something like the following which should then ignore any calls to `LogInformation` or `LogDebug`. 

```
logger := &mocks.Logger{}
logger.On("LogInformation").Stub()
logger.On("LogDebug").Stub()
```

If methods returned a value, I could return a default value regardless of the parameters passed. 

```
logger := &mocks.Logger{}
logger.On("Enabled").Return(true).Stub()
```

Or perhaps I could just stub the entire interface. If the method returns something, it can return whatever the default value is for those methods.

```
logger := &mocks.Logger{}
logger.Stub()
```

Any thoughts?

**Comment by bloudraak** [comment]
One approach would be to generate a Stub that follows the same pattern as a Mock, except that failure to call a method doesn't result in unit test failure. It can also be a bit less restrictive on parameters being passed in.

**Comment by LandonTClipp** [comment]
There's not really much need for this as you can emulate stub behavior by simply doing:

```
logger := &mocks.Logger{}
logger.On("LogInformation").Return(nil).Maybe()
logger.On("LogDebug").Return(nil).Maybe()
```
