### ISSUE TITLE
Always Prefixing Generated Mock Prefixes

### ISSUE THREAD

**Issue by bloudraak** [vektra/mockery#205]
Assuming the following interface 

```
type Logger interface {
	Enabled(level LogLevel) bool
	LogFunc(level LogLevel, eventId EventId, state interface{}, err error, formatter LogFunc)
	Log(level LogLevel, eventId EventId, err error, format string, args ...interface{})
	LogCritical(eventId EventId, err error, format string, args ...interface{})
	LogError(eventId EventId, err error, format string, args ...interface{})
	LogInformation(eventId EventId, err error, format string, args ...interface{})
	LogWarning(eventId EventId, err error, format string, args ...interface{})
	LogDebug(eventId EventId, err error, format string, args ...interface{})
	LogTrace(eventId EventId, err error, format string, args ...interface{})
}
```

I noticed that if I generate a mock as follows `MockLogger` will be generated in the same package.

```
mockery.exe -dir .. -all -name Logger -case=underscore -inpkg
```

I do prefer having a `mocks` package with all the mocks since I can exclude the entire directory whenever I build the release binaries. 

```
mockery.exe -dir .. -all -case=underscore
```

I'd still like to prefix all mock structs with `Mock` (or even `Stub`) so that the code is clear in its intent and there is no confusion between the interface and the mock class.

**Comment by LandonTClipp** [comment]
If you're using a `go generate` workflow, you can specify the struct name with the `-structname` flag. Not exactly what you're asking for but close enough.
