### ISSUE TITLE
-inpkg and -output options don't work together

### ISSUE THREAD

**Issue by limscoder** [vektra/mockery#206]
`-inpkg` flag generates the mock file in the same directory as the source file, specifying `-output` has no effect when `-inpkg` is set.

I'd like to have a directory structure like this:

```
- packagename
  - mocks
    mock_client.go
  client.go
```

**Comment by MikeWarren2014** [comment]
Are you able to get `-output` working at all? I'm not able to. 

I'm trying to do something like this : 

`
- %GOPATH%
	- src
		- [my project]
			- testing
				- mocks
					- mock_Store.go // my boss wants the mock here.
		- github.com
			- astaxie
				- beego
					- session
						- session.go // contains the Store that I want to mock`

**Comment by LandonTClipp** [comment]
Hi, v1 is not supported anymore, closing this ticket. Please open a separate ticket if you still experience this issue. Thanks!

Please note that many issues are going to be fixed once the [packages](https://vektra.github.io/mockery/features/#packages-configuration) feature is fully adopted.
