### ISSUE TITLE
"Mocking" a third-party interface

### ISSUE THREAD

**Issue by MikeWarren2014** [vektra/mockery#210]
In the code under test, there are two methods of a `struct` that ultimately depends on a [`Session.Store`](https://github.com/astaxie/beego). When I tried to use mockery to generate a "mock" of that interface, with `mockery -name Store -inpkg %GOPATH%/src/github.com/astaxie/beego/session`, it tells me that it's `Unable to find Store in any go files under this path`. However, I can not only `cd` into that path, from where I was, but say `mockery -name Store -inpkg .`, and it generates the mock there. **I want it near my test code!**

**Comment by snowzach** [comment]
I had the same issue... Use -dir instead of -inpkg
`mockery -dir %GOPATH%/src/github.com/astaxie/beego/session -name Store`

**Comment by zserge** [comment]
How this is going to work with the new modules approach (when dependency sources are not stored in vendor or GOPATH)?

**Comment by qJkee** [comment]
@zserge 
Just instead of `%GOPATH%/src`, use `$APP_PATH`
And final result will be(cd to app location)
`mockery -dir vendor/github.com/astaxie/beego/session -name Store`

**Comment by zserge** [comment]
@qJkee Not sure I understand you. The concept of modules kind of deprecates `vendor` directories, so related modules are fetched somewhere in $GOPATH/pkg/mod and contain hashes in the directory names, thus making it hard to locate.

But it looks like by switching to `golang.org/x/tools/go/packages` resolver `mockery` now allows passing `-dir github.com/whatever/external/package/you/want` and it should just work.

**Comment by qJkee** [comment]
@zserge 
Sorry, a little bit miss xD
Yea, new approach makes it harder, if you are not storing all dependencies in vendor dir.

**Comment by nielskrijger** [comment]
@zserge sadly couldn't get that to work.
I tried a random example:

```bash
$ mockery -dir github.com/go-redis/redis -name Pipeliner
Unable to find Pipeliner in any go files under this path
```
(regardless of doing a `go get github.com/go-redis/redis`)

**Comment by glyn** [comment]
Here's a workaround of sorts: https://github.com/projectriff/riff/blob/b07ffe0366ce7474a99db484c95ab245cbfb9cd1/Makefile#L31-L43

**Comment by zombie-guru** [comment]
I usually create a file in my package that references the interfaces I need and generate using that.

```
package mocksiface

import (
)

type S3API interface {
  s3iface.S3API
}
```

**Comment by tskillian** [comment]
You can do this if you're using go modules. For exampe, here is how you could mock out the DynamoDB interface:

`mockery -dir $(shell go list -m -f '{{ .Dir }}' github.com/aws/aws-sdk-go)/service/dynamodb/dynamodbiface/ -name DynamoDBAPI -output $(ROOT)/mocks`

**Comment by LandonTClipp** [comment]
Closing for the duplicate issue #243
