### ISSUE TITLE
Using Keeptree does not preserve the package name

### ISSUE THREAD

**Issue by brentahughes** [vektra/mockery#211]
When generating a lot of mocks from several interfaces across multiple sub packages the -keeptree flag does not preserve the package name. This means mocks several levels down will have the same package name making import paths require aliases on everything.

It would be nice to have a flag to preserve the package name when using -keeptree or as a bonus a way to preserve the package and add a prefix or postfix to the package name.

**Comment by mattkelly** [comment]
👍 this would be super helpful.

**Comment by LandonTClipp** [comment]
This should be fairly easy to program for, and I don't see why not. PRs are very welcome!
