### ISSUE TITLE
Fails with import errors with modules on Go 1.11

### ISSUE THREAD

**Issue by atombender** [vektra/mockery#213]
If I have a simple file such as this that refers to an imported package:

```
package mypackage
import "github.com/jackc/pgx"
// ...
```

then it fails with:

```
/Users/alex/.go/pkg/mod/github.com/jackc/pgx@v3.1.0+incompatible/batch.go:6:2: could not import github.com/jackc/pgx/pgproto3 (cannot find package "github.com/jackc/pgx/pgproto3" in any of:
	/usr/local/opt/go/libexec/src/github.com/jackc/pgx/pgproto3 (from $GOROOT)
	/Users/alex/.go/src/github.com/jackc/pgx/pgproto3 (from $GOPATH))
```

In other words, it's looking for the source in the old location, not in `$GOPATH/pkg/mod`.

I'm able to reproduce this in a small Go program that uses `golang.org/x/tools/go/loader` to load files, and I can confirm that it does not work with Go modules. (E.g. see [this issue](https://github.com/google/go-cloud/issues/78) for discussion.) Apparently the `golang.org/x/tools/go/loader` library has been superceded by [golang.org/x/tools/go/packages](https://godoc.org/golang.org/x/tools/go/packages), which is module-aware.

**Comment by atombender** [comment]
@evanphx? This is a complete blocker on Go 1.11 with modules.

**Comment by euskadi31** [comment]
Any news ? This prevents us to use mockery. Thx !

**Comment by euskadi31** [comment]
@bliuchak yes, I use Docker...

Dockerfile.generate

```Dockerfile
FROM golang:1.10-alpine
RUN apk --no-cache --update add git make
RUN mkdir -p /go/src/github.com/your-name/your-service
WORKDIR /go/src/github.com/your-name/your-service
RUN go get github.com/vektra/mockery/.../
CMD ["make", "inner-generate"]

```

Makefile

```Makefile
inner-generate:
	@go get ./...
	@go generate ./...

generate-builder:
	@docker build -f Dockerfile.generate -t your-service-generate .

generate: generate-builder
	@# hack for https://github.com/vektra/mockery/issues/213
	@echo "Generate..."
	@docker run --rm --name your-service-generate-running -v $(shell pwd):/go/src/github.com/your-name/your-service your-service-generate

```

**Comment by kasirajanss93** [comment]
It would be nice if you could add support to go mod

**Comment by atombender** [comment]
@evanphx?

**Comment by davisford** [comment]
Has there been a new release with PR #218?  Doing standard install of mockery still has problem for me.

**Comment by atombender** [comment]
@davisford It's merged. This project doesn't do releases or tags, unfortunately, but `go get -u` (or cloning + `go install`) should get you the latest one. If you still have problems, maybe you can create a new issue, and I'll take a look.
