### ISSUE TITLE
Unable to get writer when used with -inpkg option

### ISSUE THREAD

**Issue by wulifu2hao** [vektra/mockery#220]
Hi I encounter problem when using mockery with -inpkg option
how I use it: mockery -name IBookingService -case=underscore -inpkg
error msg: Unable to get writer for IBookingService: open gitlab.myteksi.net/gophers/go/food/external/mock_i_booking_service.go: no such file or directory

I suspect this is due to the recent change ( https://github.com/vektra/mockery/commit/2be70d1c16b905d1ebbb3f1da219b11de416a0e6#diff-9fccd60b1234c112849b2bdd764adae3R159 ): pkg.Path used to be the path of the file containing the interface, but now entry.pkg.Types points to the director of the file of the interface. I might be wrong

**Comment by euskadi31** [comment]
ping @atombender

**Comment by atombender** [comment]
I will take a look, thanks.

**Comment by cicely-zhang** [comment]
Is there a way to get older version of mockery using go get to bypass this issue for now?

**Comment by atombender** [comment]
You should be able to just clone the repo, `git reset --hard ea265755d541b124de6bc248f7744eab9005fd33` (for example), then run `go install .`.

**Comment by atombender** [comment]
@wulifu2hao, @euskadi31, @santoshaitha, @cicely-zhang PR is available if you want to give it a go. Works for me, but there are no tests for the CLI itself, so I'm not as certain as I want to be that it's doing the right thing.

**Comment by euskadi31** [comment]
it's working perfectly ;)

**Comment by santoshaitha** [comment]
Is this PR merged?
