### ISSUE TITLE
Keeptree option , name of structure with first capital letter ?

### ISSUE THREAD

**Issue by julestruong** [vektra/mockery#222]
Hello guys, i'm using `-keeptree` , and the mocks generated seems not right.

Their structure are 

- named with lowercase for the first letter.
- in a nested package named "mocks"

So it is not possible to use it anywhere outside this nested package ?
Is it mandatory to creates tests inside mocks folder ?

**Comment by LandonTClipp** [comment]
No it's not necessary to generate inside the mocks folder. I typically use `--inpackage` to make it in the same package, and `--testonly` to append `_test.go` to the mock files to prevent them from becoming part of your public API. This is sufficient for the vast majority of cases, in my experience.

**Comment by edsonmedina** [comment]
so what's the `--keeptree` option for if it doesn't work?

**Comment by LandonTClipp** [comment]
It does work. If your interface is not exported in the original code, so too will the mocked struct. You can force it to become exported, please refer to the command line help.
