### ISSUE TITLE
throw an error if file with the same name already exists

### ISSUE THREAD

**Issue by ilgooz** [vektra/mockery#223]
I had a file with name _storage.go_ and I executed following command to create mocks:

```
mockery -name=Storage -dir ./articles -output ./articles
```

It deleted my file without an error and I lost it's content...

**Comment by sergii4** [comment]
But if you regenerate file it should overwrite existing. So it should be possible

**Comment by LandonTClipp** [comment]
Definitely need to fix, this is a horrible behavior.

**Comment by LandonTClipp** [comment]
Hi, v1 is not supported anymore. Please open a new ticket if you still experience this issue in the latest version of mockery. I am trying to go through a backlog of issues that were created previous to my time as a maintainer of this project, as most of these problems are v1 which we don't support. Closing this ticket. Thanks!
