### ISSUE TITLE
Add option to use lowercase mock file naming

### ISSUE THREAD

**Issue by gkumar7** [vektra/mockery#224]
The generated file starts with a capital letter, I like to follow the convention to use lowercase names (snake case) for file names. Maybe an option could be added for this?

Thanks!

**Comment by sergii4** [comment]
Do you want to have it by default? Cause under_score case is available. In README.md:

## Caseing

mockery generates files using the caseing of the original interface name.  This
can be modified by specifying `-case=underscore` to format the generated file
name using underscore casing.

**Comment by gkumar7** [comment]
@sergii4 thanks for pointing this out. Must have missed this when first scanning the readme.
