### ISSUE TITLE
Unable to run mockery

### ISSUE THREAD

**Issue by karanbhomiagit** [vektra/mockery#225]
`go get github.com/vektra/mockery/.../`
results in error 
`go/src/github.com/vektra/mockery/mockery/parse.go:35:7: conf.BuildFlags undefined (type packages.Config has no field or method BuildFlags)`

I am unable to run $GOPATH/bin/mockery after this

**Comment by codeactual** [comment]
You may need to update `golang.org/x/tools/go/packages` due to:

https://sourcegraph.com/github.com/golang/tools/-/commit/5fad05c81888302518e9dfb20b55b3e1790c7a11

**Comment by bvisness** [comment]
That worked for me. Just for the record, I had to run the following to update it:

```
go get -u golang.org/x/tools/go/packages
```

**Comment by LandonTClipp** [comment]
x/tools dep was fixed.
