### ISSUE TITLE
go get github.com/vektra/mockery/...: no matching versions for query "latest"

### ISSUE THREAD

**Issue by J7mbo** [vektra/mockery#226]
Running:

> go get github.com/vektra/mockery/.../

Results in:

> go: finding github.com/vektra/mockery/... latest
> go: finding github.com/vektra/mockery latest
> go get github.com/vektra/mockery/...: no matching versions for query "latest"

**Comment by J7mbo** [comment]
This now works, no idea why.... I didn't change anything on my end.

**Comment by tzachshabtay** [comment]
I'm getting the same error. 
Sounds related to: https://github.com/vektra/mockery/issues/226

My workaround: 
`go get github.com/vektra/mockery/cmd/mockery`

**Comment by marianogappa** [comment]
@tzachshabtay not only related to #226; Identical: :trollface: . Which one did you actually mean? Cheers for the workaround.

**Comment by alvery** [comment]
This is still be an issue, could you please update the readme file
