### ISSUE TITLE
can't generate mocks outside GOPATH

### ISSUE THREAD

**Issue by minaevmike** [vektra/mockery#230]
Hi i am using modules and i can't generate mocks using mockery. I create simple example project to demostrate it https://github.com/minaevmike/mockery_test . So calling 
```
go generate ./...                      
/Users/mminaev/go/pkg/mod/github.com/go-openapi/spec@v0.0.0-20180415031709-bcff419492ee/expander.go:29:2: could not import github.com/go-openapi/jsonpointer (cannot find package "github.com/go-openapi/jsonpointer" in any of:
        /usr/local/go/src/github.com/go-openapi/jsonpointer (from $GOROOT)
        /Users/mminaev/go/src/github.com/go-openapi/jsonpointer (from $GOPATH))
/Users/mminaev/go/pkg/mod/github.com/go-openapi/spec@v0.0.0-20180415031709-bcff419492ee/expander.go:30:2: could not import github.com/go-openapi/swag (cannot find package "github.com/go-openapi/swag" in any of:
        /usr/local/go/src/github.com/go-openapi/swag (from $GOROOT)
        /Users/mminaev/go/src/github.com/go-openapi/swag (from $GOPATH))
/Users/mminaev/go/pkg/mod/github.com/go-openapi/spec@v0.0.0-20180415031709-bcff419492ee/ref.go:23:2: could not import github.com/go-openapi/jsonreference (cannot find package "github.com/go-openapi/jsonreference" in any of:
        /usr/local/go/src/github.com/go-openapi/jsonreference (from $GOROOT)
        /Users/mminaev/go/src/github.com/go-openapi/jsonreference (from $GOPATH))
/Users/mminaev/go/pkg/mod/github.com/utrack/clay/v2@v2.3.7/transport/httptransport/opts.go:4:18: could not import github.com/grpc-ecosystem/go-grpc-middleware (go/build: importGo github.com/grpc-ecosystem/go-grpc-middleware: exit status 1
verifying github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0: checksum mismatch
        downloaded: h1:Iju5GlWwrvL6UBg4zJJt3btmonfrMlCDdsejg4CZE7c=
        go.sum:     h1:BWIsLfhgKhV5g/oF34aRjniBHLTZe5DNekSjbAjIS6c=

```
Display a lot of errors.  But main builds successfully. Also if i put this project inside GOPATH and vendor all deps `mockery` works fine.

**Comment by avence12** [comment]
Encounter similar issue after migrating my project to Modules.
It hangs when the project is outside of `$GOPATH`.

**Comment by LandonTClipp** [comment]
Unfortunately due to the lack of versioning during the move to support modules, this is going to be really tricky to fix. The best bet I can see is to pin your mockery at the commit before modules were introduced. If someone could find this and post it here, that'd be super.

**Comment by LandonTClipp** [comment]
Hi, v1 is not supported anymore. Please open a new ticket if you still experience this issue in the latest version of mockery. I am trying to go through a backlog of issues that were created previous to my time as a maintainer of this project, as most of these problems are v1 which we don't support. Closing this ticket. Thanks!
