### ISSUE TITLE
Basic mockery run returning: flag provided but not defined: -compiled

### ISSUE THREAD

**Issue by eoinmcq** [vektra/mockery#231]
As of today(at least) we have been getting the error:

Error parsing file:  unsupported version of go: exit status 2: flag provided but not defined: -compiled

Even cloning the latest repo and using the basic string.go example this is happening.

Apologies if this is a duplicate issue but I can't see anything which I think covers this elsewhere.

Any thoughts on this or has anything changed in dependencies or the like which could have caused this?

Steps:
- git clone https://github.com/vektra/mockery.git
- cd mockery
- make install
-Create String.go file with the following:
   package test
  
  type Stringer interface {
          String() string
  }
-mockery -name=Stringer

**Comment by codeactual** [comment]
Hi. What does the `install` target look like?

**Comment by amisevsk** [comment]
Seems to be related to an old version of go: the `-compiled` argument was added in Go 1.11. The error is coming from `golang.org/x/tools`.

**Comment by eoinmcq** [comment]
Thanks @codeactual @amisevsk I'll have a look at versions then close out when sorted.

**Comment by teodorst** [comment]
Hi! Will you support 1.10.8 ?
