### ISSUE TITLE
failed to mock.On() functon with channel passed as argument

### ISSUE THREAD

**Issue by non5ense** [vektra/mockery#233]
I have a function that takes chan as a last argument. 
`func (g *GeoProxyService) GetTypesAsync(placeId string, lang string, out chan GetCacheResult) `

mockery generates mock for it and in tests it failes to call Mock.On() because channel created in test and mocked channel have different memory addresses.

Output: 
```
mock: Unexpected Method Call
-----------------------------

GetTypesAsync(string,string,chan structs.GetCacheResult)
		0: "ChIJeQAFL4mfSkERViyd4jJva1U"
		1: "ru"
		2: (chan structs.GetCacheResult)(0xc0001b4300)

The closest call I have is: 

GetTypesAsync(string,string,chan structs.GetCacheResult)
		0: "ChIJeQAFL4mfSkERViyd4jJva1U"
		1: "ru"
		2: (chan structs.GetCacheResult)(0xc0001b4000)
```
Is there some kind of recommended workaround for this case?

**Comment by LandonTClipp** [comment]
I don't think this is a mockery issue, this is a testify issue. You'll probably want to raise a ticket with them.
