### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by amuttsch** [vektra/mockery#237]
The last commit is from November 2018 and recent issues and pull requests haven't been answered.

I'm asking because we are using it and thinking about adding a `-go-get-insecure` flag for getting packages from a self signed repository. If the project is dead however, we might switch to https://github.com/golang/mock

**Comment by filinvadim** [comment]
Last working build on commit `ea265755d541b124de6bc248f7744eab9005fd3`
go version go1.10.4 linux/amd64

**Comment by edulopezTriv** [comment]
It looks like it not maintained anymore. I think it would be better to user https://github.com/golang/mock

**Comment by LandonTClipp** [comment]
Hi folks. The project is being continued over at https://github.com/go-mockery/mockery. I will be personally maintaining it so please keep using it! We can't lose this package :)
