### ISSUE TITLE
Generate expectation code automatically

### ISSUE THREAD

**Issue by glymehrvrd** [vektra/mockery#245]
My team is working on writing missing tests for a lot of old code in production, and found writing mocking object's expectation quite a painful work.

Since the code runs correctly in production, when given the correct input condition, the calls to actual object is also correct. So if mockery provides a mode, on which the calls to actual object is recorded and expectation code can be auto-generated, we can save a lot of human resource, avoiding writing test code manually.

For example, I have this code in production
```go
type Car interface {
      func Ignite(int gas) bool
}

type FooCar struct {
}

func (c *FooCar) Ignite(int gas) bool {
    return gas > 0
}
```

Now I need to manually write expectation for mocked car.
```go
mockedCar.On("Ignite", 0).Return(false)
mockedCar.On("Ignite", 50).Return(true)
```

But if mockedCar generated by mockery also knows the actual object, it can invoke the actual object and generate expecation automatically like this
```go
mockedCar = &MockedCar{ActualObj: &FooCar{}}
mockedCar.Gen(Input{"Ignite",0})
mockedCar.Gen(Input{"Ignite",50})
```
results code at output
```go
mockedCar.On("Ignite", 0).Return(false)
mockedCar.On("Ignite", 50).Return(true)
```

**Comment by Willyham** [comment]
I'm not sure that this is possible, as it looks like the final generated code depends on actually executing the original code path. Either way, I think this would be outside the scope of this project.

**Comment by LandonTClipp** [comment]
The ability for a program to know for certain the behavior of a piece of code is an astronomically difficult problem to solve, so what you're asking would be pretty much impossible.

With that being said, if you want a specific function of your mocked object to behave the same as your real object, why not just execute the real object? For a simple piece of code this should be easy.

```go
car := Car{}
mockedCar.On("Ignite", mock.Anything).Return(ignite(gas int) bool {
  return car.Ignite(gas)
})
```
