### ISSUE TITLE
Exclude subdirs when with -all flag

### ISSUE THREAD

**Issue by musinit** [vektra/mockery#255]
Hi! Wonderfull project, thank you for it. But I meet a problem. I need to generate mocks for all interfaces in my my_dir, but I don't need to mock interfaces in subdirs.

**Comment by Willyham** [comment]
Could you instead do `-name *` without `-all` or `-recursive`?

**Comment by musinit** [comment]
In case I write -name * it response with 

>  Unable to find Dockerfile in any go files under this path<
if I set -name=*, it writes 

> Invalid regular expression provided to -name<

So either I am doing something wrong, or it's possible a bug/feature

**Comment by LandonTClipp** [comment]
@musinit `*` is a bash glob character, make sure you are quoting it:

`-name '*'`

**Comment by musinit** [comment]
Sorry, I have the same in that case too..
![image](https://user-images.githubusercontent.com/24373601/82071159-633bf000-96de-11ea-96db-dc7d98c701c5.png)

**Comment by LandonTClipp** [comment]
What if you did `-name '.*'`?  It's a regular expression, and I suppose `'*'` is not valid.

**Comment by nmiyake** [comment]
I can confirm that `--name=".*"` provides the desired behavior:

```
➜ mockery --dir=./pkg --name=".*"
06 Jul 20 14:35 PDT INF Starting mockery dry-run=false version=0.0.0-dev
06 Jul 20 14:35 PDT INF Walking dry-run=false version=0.0.0-dev
06 Jul 20 14:35 PDT INF Generating mock dry-run=false interface=OutputStreamProvider qualified-name=github.com/vektra/mockery/v2/pkg version=0.0.0-dev
06 Jul 20 14:35 PDT INF Generating mock dry-run=false interface=WalkerVisitor qualified-name=github.com/vektra/mockery/v2/pkg version=0.0.0-dev
06 Jul 20 14:35 PDT INF Generating mock dry-run=false interface=namer qualified-name=github.com/vektra/mockery/v2/pkg version=0.0.0-dev
```

As such, this issue can likely be closed (in the abstract, it may be nice to have a different way to do this via flags, but given that the API of the CLI is stable this way to do it is likely sufficient).

**Comment by LandonTClipp** [comment]
Closing this ticket for inactivity. Please feel free to submit a PR to the docs if anything is not clear. Thanks!
