### ISSUE TITLE
---

### ISSUE THREAD

**Issue by LandonTClipp** [vektra/mockery#256]
# Attention!

The new mockery github page is now at: https://github.com/go-mockery/mockery

The vektra/mockery repo has not been updated in almost two years and is being considered by the Golang community to be defunct and dead. Activity is being moved over to the above repository so that the project can be kept alive and additional maintenance/improvement activities continued.

**Comment by evanphx** [comment]
Hi @LandonTClipp, can we talk about this a bit more formally? My email is in my github profile, please send one over.

**Comment by LandonTClipp** [comment]
Sure thing, I just sent you an email.

**Comment by LandonTClipp** [comment]
Hi everyone, Evan got me write access to the repo so we are all good now. I'm deleting all mentions of the fork I made since it's no longer necessary.
