### ISSUE TITLE
Avoid calling packages.Load

### ISSUE THREAD

**Issue by xtonyjiang** [vektra/mockery#258]
(Paraphrased this issue from the now-deleted go-mockery repo)

I've noticed that calls to mockery have a decently high overhead due to calling `packages.Load`, which makes network calls. We can probably avoid the call to `packages.Load` by doing something like what https://github.com/golang/mock/pull/420 does.

**Comment by LandonTClipp** [comment]
Definitely would like to see this implemented!

**Comment by LandonTClipp** [comment]
This has already been optimized by using the [packages](https://vektra.github.io/mockery/features/#packages-configuration) feature. `packages.Load` will only be called once, which confers the performance benefit we're looking for.
