### ISSUE TITLE
`undeclared name` when interface are nested

### ISSUE THREAD

**Issue by sanketplus** [vektra/mockery#264]
Inside a same package, if an interface is referring to another interface, mockery throws name error

a.go
```
package main

import "fmt"

type A interface {
	foo(b B)
}

func main() {
	fmt.Println("vim-go")
}
```

b.go
```
package main

type B interface {
	bar(int)
}
```

Output:
```
$ mockery -all
Error parsing file:  /private/tmp/test/a.go:6:8: undeclared name: B
Error parsing file:  /private/tmp/test/a.go:6:8: undeclared name: B
```

But if I remove B's reference from A then it works 

```
$ cat a.go
package main

import "fmt"

type A interface {
	foo(b int)
}

func main() {
	fmt.Println("vim-go")
}

$ mockery -all
Generating mock for: A in file: mocks/A.go
Generating mock for: B in file: mocks/B.go
```

This is a simplified test scenario which I figured from investigating our large codebase

**Comment by sanketplus** [comment]
If this can be confirmed to be an issue, I can look into this over the weekend and possibly raise a PR

**Comment by LandonTClipp** [comment]
I'm not able to reproduce this:

```go
[lclipp@chit-lcl2 mockery2][0] $ ls
a.go  b.go  go.mod  LICENSE  mockery  README.md
$ ./mockery -all
Generating mock for: A in file: mocks/A.go
Generating mock for: B in file: mocks/B.go
$ cat a.go
package main

import "fmt"

type A interface {
    foo(b B) bool
}

func main() {
    fmt.Println("vim-go")
}
$ cat b.go
package main

type B interface {
    bar(int)
}

```

**Comment by sanketplus** [comment]
This is happening with the master HEAD. Digging in deeper, this error seems to be coming from `golang.org/x/tools/go/packages` can you confirm which version it is for you?

My system has `~/go/pkg/mod/golang.org/x/tools@v0.0.0-20200323144430-8dcfad9e016e/go/packages`

**Comment by sanketplus** [comment]
Another thing I note is I am on go 1.13

**Comment by sanketplus** [comment]
The files were not under GOPATH 🤦 adding the current folder under GOPATH resolves the issue.
