### ISSUE TITLE
What is the difference from golang/mock?

### ISSUE THREAD

**Issue by wolfogre** [vektra/mockery#268]
What is the difference from [golang/mock](https://github.com/golang/mock)?

There is any document to explain it?

**Comment by LandonTClipp** [comment]
The main difference is that testify + mockery is objectively easier and more user-friendly than gomock + mockgen. There are a few minor things that gomock does better, but the API in my opinion is kind of unfortunate and not intuitive to use, especially when considering generating mock objects.

There's no document that describes it, but you can google a few good comparisons.
