### ISSUE TITLE
Add the usage command in the readme

### ISSUE THREAD

**Issue by Crossfire972** [vektra/mockery#269]
Hi,

How to use the preferred docker image could seem obvious,

But adding a usage section might save some time to some people:

```
docker run -v $PWD:/src -w /src --rm vektra/mockery -all
```

I couldn't figure out why running the docker image wouldn't produce any output while the binary was working perfectly.

It looks like the source directory need to be mounted, found the answer in https://github.com/vektra/mockery/pull/260

Thanks

**Comment by Crossfire972** [comment]
Well I don't think i'm doing it right, because the mock files are generated with root permissions:
-rw-r--r-- 1 root root 2.5K May 24 08:02 domain/mocks/EntryRepository.go
-rw-r--r-- 1 root root 2.5K May 24 08:02 domain/mocks/EntryUsecase.go

**Comment by LandonTClipp** [comment]
I can add this usage to the dockerhub page to prevent confusion. As far as the ownership issue, it's expected for them to be owned by root unless you `su` into something else. I'm not sure that's something we'd really be able to change. That's up to you to fix.

**Comment by LandonTClipp** [comment]
Added a short readme to the dockerhub page, hope that helps. Thanks!
