### ISSUE TITLE
I wish there was a way to do a dry run.

### ISSUE THREAD

**Issue by shahzeb1** [vektra/mockery#281]
It would be so cool to do `mockery -all -dry` and then just get a list of all the files / mocks that mockery would generate. 

Thank you for the great tool btw.

**Comment by LandonTClipp** [comment]
Hey @shahzeb1 thanks for the suggestion. I'm not sure a dry run would have a lot of practical benefits. We can keep this request up for a bit to see if other people would like this.

**Comment by LandonTClipp** [comment]
Thinking it over, yeah I understand why dry run would be useful. Adding this to the v2.0.0 project.

**Comment by LandonTClipp** [comment]
@shahzeb1 #286 adds your request. Note that you have to run with debug log levels to see what files would have been written to:

![Screenshot_2020-06-14_23-37-54](https://user-images.githubusercontent.com/11232769/84618696-894cdf80-ae98-11ea-8984-477d863539de.png)

**Comment by LandonTClipp** [comment]
Oof, there's an issues _yet again_ with the deployment workflow. I won't be able to get this published for a few days, but you can pull from the head commit and build it yourself if you'd like.
