### ISSUE TITLE
Invalid mock generated with the same package names

### ISSUE THREAD

**Issue by RossHammer** [vektra/mockery#291]
Using either 1.1.2 or 2.0.0-alpha.13 release builds of mockery we have the following issue

`cloudformation/interface.go`
```go
package cloudformation

import "github.com/aws/aws-sdk-go/service/cloudformation"

type invalid interface {
	String(*cloudformation.CreateStackInput) string
}
```

`main.go`
```go
package main

func main() {}
```

generates a mock like like the following when using `mockery -all -testonly -inpkg`
```go
// Code generated by mockery v1.1.2. DO NOT EDIT.

package cloudformation

import mock "github.com/stretchr/testify/mock"

// mockInvalid is an autogenerated mock type for the invalid type
type mockInvalid struct {
	mock.Mock
}

// String provides a mock function with given fields: _a0
func (_m *mockInvalid) String(_a0 *cloudformation.CreateStackInput) string {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(*cloudformation.CreateStackInput) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
```

You can see the import for cloudformation is missing and in turn the go reports undefined: cloudformation in the mock file.

It seems like when the cloudformation directory is at the root the issue cannot be re-created. When mockery is built from source either via `go get` or cloning and `go install` this issue seems to go away and the import is generated properly. As installing is not supported using `go get` anymore our mocks are no longer generating properly.
```go
package cloudformation

import (
	"github.com/aws/aws-sdk-go/service/cloudformation"
	mock "github.com/stretchr/testify/mock"
)
```

**Comment by LandonTClipp** [comment]
What version of go are you using in `go get` ? I'd say this is a pretty serious issue, let's get this addressed.

**Comment by LandonTClipp** [comment]
I can reproduce this issue as you describe. I'm looking for a possible cause.

**Comment by LandonTClipp** [comment]
So I added some debug messages and discovered that mockery is skipping this explicitly:

```
[ltclipp@landon-virtualbox test_issue]$ ../mockery --inpackage --all --log-level debug
17 Jun 20 19:38 CDT INF Starting mockery dry-run=false version=0.0.0-dev
17 Jun 20 19:38 CDT INF Walking dry-run=false version=0.0.0-dev
17 Jun 20 19:38 CDT DBG parsing dir=/home/ltclipp/git/vektra/mockery/test_issue/cloudformation dry-run=false file=interface.go version=0.0.0-dev
17 Jun 20 19:38 CDT DBG parsing dir=/home/ltclipp/git/vektra/mockery/test_issue/cloudformation dry-run=false file=mock_invalid.go version=0.0.0-dev
17 Jun 20 19:38 CDT DBG parsing dir=/home/ltclipp/git/vektra/mockery/test_issue/cloudformation dry-run=false file=interface.go version=0.0.0-dev
17 Jun 20 19:38 CDT DBG parsing dir=/home/ltclipp/git/vektra/mockery/test_issue/cloudformation dry-run=false file=mock_invalid.go version=0.0.0-dev
17 Jun 20 19:38 CDT DBG parsing dir=/home/ltclipp/git/vektra/mockery/test_issue dry-run=false file=main.go version=0.0.0-dev
17 Jun 20 19:38 CDT DBG creating writer to file dry-run=false interface=invalid path=/home/ltclipp/git/vektra/mockery/test_issue/cloudformation/mock_invalid.go qualified-name=cloudformation/cloudformation version=0.0.0-dev
17 Jun 20 19:38 CDT DBG populating imports dry-run=false interface=invalid qualified-name=cloudformation/cloudformation version=0.0.0-dev
17 Jun 20 19:38 CDT DBG func(*github.com/aws/aws-sdk-go/service/cloudformation.CreateStackInput) string dry-run=false interface=invalid qualified-name=cloudformation/cloudformation version=0.0.0-dev
17 Jun 20 19:38 CDT DBG (cloudformation/cloudformation.invalid).String dry-run=false interface=invalid qualified-name=cloudformation/cloudformation version=0.0.0-dev
17 Jun 20 19:38 CDT DBG found import dry-run=false import=github.com/aws/aws-sdk-go/service/cloudformation interface=invalid qualified-name=cloudformation/cloudformation version=0.0.0-dev
17 Jun 20 19:38 CDT DBG import equals interface package's path, skipping dry-run=false import=github.com/aws/aws-sdk-go/service/cloudformation interface=invalid qualified-name=cloudformation/cloudformation version=0.0.0-dev
17 Jun 20 19:38 CDT DBG found import dry-run=false import=github.com/stretchr/testify/mock interface=invalid qualified-name=cloudformation/cloudformation version=0.0.0-dev
17 Jun 20 19:38 CDT DBG writing out import dry-run=false import=github.com/stretchr/testify/mock interface=invalid qualified-name=cloudformation/cloudformation version=0.0.0-dev
17 Jun 20 19:38 CDT INF Generating mock dry-run=false interface=invalid qualified-name=cloudformation/cloudformation version=0.0.0-dev
```

Although, it's a bit mysterious to me that even though it says it's skipping it, the import is still inserted somehow. That I don't understand.

**Comment by LandonTClipp** [comment]
Additionally, I found the commit that caused this bug: https://github.com/vektra/mockery/commit/d9507cd5

**Comment by RossHammer** [comment]
Awesome thanks for looking into it so quickly. I would try and help more but I can't figure out how to reproduce it from the source code, only the compiled binaries. Here is the version of go I was using
```
❯ go version
go version go1.14.3 darwin/amd64
```

**Comment by LandonTClipp** [comment]
Adding a few logging messages to see if we can catch why this is happening. Making a new build now, will see if this highlights any issues.

**Comment by RossHammer** [comment]
I have discovered how to re-create the issue when building from source! When the formatter runs it can add/remove imports and it will add the import when build locally for some reason. So this line needs to be changed to the following so things are consistent. Still trying to track down how to fix the issue properly.

https://github.com/vektra/mockery/blob/master/pkg/generator.go#L662
```go
opt := &imports.Options{Comments: true, FormatOnly: true}
```

**Comment by RossHammer** [comment]
Well that is a bummer it caused other issues. I guess this ticket should be re-opened for now then.

**Comment by keshamin** [comment]
I faced the same issue. I use the latest docker image to generate mocks. Mocked interface is in package `training` (.../service/training/) and it uses structs from another package named `training` (.../models/training/). The import of `training` that holds models is missing, so the mock code can't be compiled.

**Comment by fterrag** [comment]
@LandonTClipp I'm also running into this issue - any idea for a workaround?

**Comment by gogis79** [comment]
Have you guys fixed that issue yet? Because it's still present in the current version. Yes, running `go generate` locally in the folder properly adds the import, but it's unfeasible in a project with thousands of files and hundreds of directories.
