### ISSUE TITLE
Invalid version in go.mod

### ISSUE THREAD

**Issue by kollektiv** [vektra/mockery#299]
When running `go get github.com/vektra/mockery/cmd/mockery@v2.0.0` with go 1.14

There is an error  `github.com/vektra/mockery@v2.0.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2`

**Comment by LandonTClipp** [comment]
Good catch. We don't officially support using `go get` anymore but I think it's still worth it to fix this.

**Comment by kollektiv** [comment]
I believe mockery should use `/v2` in the module path since it's now version 2.0 and using Go modules.

From https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning, "the go command requires that modules with major version v2 or later use a module path with that major version as the final element"

`go get` is a common way to add a Go tool to a project using the [tools.go method](https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module)

**Comment by LandonTClipp** [comment]
Thanks for the info, it simply slipped my mind to do this when going to v2. 

The reason we do not officially support it is because older versions of golang have issues compiling the code for subtle reasons. Supporting all versions of golang in a binary distribution like this can turn into a real nightmare and I think distracts from spending time of the actual business logic in the project.

I'm open to the idea of doing some kind of quasi-support for this, like to say we will provide whatever necessary structure to the package to support `go get`-ing it, but I don't want to support building from different versions of go.

**Comment by kollektiv** [comment]
> The reason we do not officially support it is because older versions of golang have issues compiling the code for subtle reasons. Supporting all versions of golang in a binary distribution like this can turn into a real nightmare and I think distracts from spending time on the actual business logic in the project.

If the module in go.mod added `/v2`, what kinds of issues would you see in some projects?

For some additional context, the project I have been working on installs module aware tools using `cd /go/bin && GO111MODULE=on go get ...` (ex. golangci-lint). I believe this may work as of go 1.12 which adds support for `GO111MODULE`

Go 1.14 has been stricter about module compatibility so I think this is why I'm running into this error.

> I'm open to the idea of doing some kind of quasi-support for this, like to say we will provide whatever necessary structure to the package to support go get-ing it, but I don't want to support building from versions of go other than the most recent few.

How about supporting Go versions that support Go modules? Go modules is quickly becoming adopted everywhere

Thanks for your work on this too. The new changes are helpful in the project I've been working on

**Comment by tolbier** [comment]
To allow an easy mockery install method , I`ve created this asdf plugin for mockery https://github.com/tolbier/asdf-mockery

as every asdf plugin, very easy to install https://github.com/tolbier/asdf-mockery/blob/master/README.md

```
asdf plugin add mockery https://github.com/tolbier/asdf-mockery.git
asdf install mockery 2.0.0
```

**Comment by LandonTClipp** [comment]
> If the module in go.mod added /v2, what kinds of issues would you see in some projects?

It's not the versioning of this project that's the issue, it's when people try go getting it with old versions of golang. But like you said I think this shouldn't be an issue >= 1.12.

> How about supporting Go versions that support Go modules? Go modules is quickly becoming adopted everywhere

Yeah, I think that's probably fine. Perhaps I am being too stubborn about it. I think for now I will just leave it as officially deprecated but I think I'll do what I reasonably can to accommodate it.  

I have a PR in to fix the versioning, we'll get this fixed shortly.
