### ISSUE TITLE
Verify that a mock has been called

### ISSUE THREAD

**Issue by c-petrini** [vektra/mockery#305]
Hi,
I'm pretty new to Golang and mockery and I'd like to know if there's a way to verify that a mock has been called. 

I'd like to cover two cases:
- where the mocked method doesn't get called
- to verify that is called n times

Is this possible?

Thank you.

**Comment by LandonTClipp** [comment]
Yes this is possible via the `testify.mock` interface. Since mock objects embed the `mock.Mock` object, you just call something like `mockObj.AssertExpectations()`. [See here](https://godoc.org/github.com/stretchr/testify/mock#pkg-index).

**Comment by c-petrini** [comment]
Thank you for super useful info :)
