### ISSUE TITLE
Generated mock is incorrect for interfaces with function arguments with varargs

### ISSUE THREAD

**Issue by nmiyake** [vektra/mockery#319]
Define the following interface:

```go
type Fooer interface {
	Foo(in func(...string))
}
```

Generating a mock for this interface incorrectly replaces the varargs with a slice parameter:

```go
// Fooer is an autogenerated mock type for the Fooer type
type Fooer struct {
	mock.Mock
}

// Foo provides a mock function with given fields: in
func (_m *Fooer) Foo(in func([]string)) {
	_m.Called(in)
}
```

Adding the line `var _ cmd.Fooer = &Fooer{}` to assert that the generated struct implements the mock shows that this is not the case:

```
➜ go build ./...
# github.com/vektra/mockery/v2/mocks
mocks/Fooer.go:15:5: cannot use &Fooer literal (type *Fooer) as type cmd.Fooer in assignment:
        *Fooer does not implement cmd.Fooer (wrong type for Foo method)
                have Foo(func([]string))
                want Foo(func(...string))
```

**Comment by nmiyake** [comment]
This is due to the handling of `case *types.Signature:` in `generator.go`. The `g.renderTypeTuple(ctx, t.Params())` does not have any notion of varargs, which makes the handling here incorrect. To fix this, this switch case will need to be updated to iterate through the params and, if the function signature is a vararg one, manually construct the last parameter (much as is done for the interface functions themselves).

**Comment by LandonTClipp** [comment]
I think we should think about better solutions than using switch statements. You can basically extend this problem recursively infinitely down the parameter tree. What if you have this:

```go
type Fooer interface {
	Foo(in func(in2 func(...string)))
}
```

Without looking too closely at the code, I don't know if this is something that's already handled recursively.

**Comment by LandonTClipp** [comment]
This is an old issue and I'm pretty sure we've solved this. Please view this documentation: https://vektra.github.io/mockery/notes/#variadic-arguments

Feel free to ping me or submit a new issue if this is still causing problems.

**Comment by gaston-haro** [comment]
@LandonTClipp I see the documentation but part of that piece of code is gone from master branch. Specifically `unroll-variadic` flag is not being parsed anymore as the documentation reads.

**Comment by LandonTClipp** [comment]
> @LandonTClipp I see the documentation but part of that piece of code is gone from master branch. Specifically `unroll-variadic` flag is not being parsed anymore as the documentation reads.

Can you show a reproducer? I verified and the mocks are being generated as expected. We also test specifically for this case. I would be very interested to know how you came to this conclusion.
