### ISSUE TITLE
ERR Error parsing error="-: no Go files in

### ISSUE THREAD

**Issue by ls-dac-chartrand** [vektra/mockery#327]
I was running this:

```
cd /path/to/project
mockery --all
```

And it was working fine ie.

```
// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.
```

Today (after an upgrade) I get:

```
mockery --all
14 Aug 20 12:42 EDT INF Starting mockery dry-run=false version=2.2.0
14 Aug 20 12:42 EDT INF Walking dry-run=false version=2.2.0
14 Aug 20 12:42 EDT ERR Error parsing error="-: no Go files in /path/to/project" dry-run=false version=2.2.0
14 Aug 20 12:42 EDT ERR Failed to walk target sources ".". error="-: no Go files in /path/to/project" dry-run=false version=2.2.0
```

Help?
MacOs 10.15.6
Code is on a Mac OS Extended partition (Case-sensitive, Journaled, Encrypted)

**Comment by LandonTClipp** [comment]
Hi sorry about this, I will cut a new release now. There was an issue with 2.2.0, so please use the previous version (or the new version, when I tag it).

**Comment by LandonTClipp** [comment]
Please use https://github.com/vektra/mockery/releases/tag/v2.2.1, thanks!
