### ISSUE TITLE
is there any tips to speedup mockery generation?

### ISSUE THREAD

**Issue by tuananh** [vektra/mockery#328]
I test on a reasonably small project and it's taking over a minute. is there anyway to speed it up?

I use `mockery --all --keeptree` command

```
________________________________________________________
Executed in   75.11 secs   fish           external
   usr time  228.08 secs  389.00 micros  228.08 secs
   sys time   58.53 secs  342.00 micros   58.53 secs
```

**Comment by LandonTClipp** [comment]
There was a PR that attempted to help fix this: https://github.com/vektra/mockery/pull/323. Unfortunately there is not any  advice I can give at the moment.

We tried merging it but it introduced a regression. Hopefully @Helcaraxan can take another look at it and see if there's any way we can fix it.

There is a rather large overhaul that this codebase needs to undergo, which is scheduled for v3. It has accumulated a significant amount of bloat, and was also made with pre-golang-modules assumptions. 

One of the major tasks that needs to be accomplished is switching from walking/loading individual files, to loading packages. This is discussed in the PR, and has also been brought up in various other places.

**Comment by LandonTClipp** [comment]
@tuananh I have a potential solution to this now, view the linked draft PR.
