### ISSUE TITLE
Figure out word wrapping in history / up-next list

### ISSUE THREAD

**Issue by nlowe** [vektra/mockery#332]
Combinations of long track titles / album titles / artist titles / station titles can cause the track string to wrap, hiding other tracks. In this case, there are supposed to be four tracks in the up-next list, but one is pushed off-screen by the wrap of the second track.

![image](https://user-images.githubusercontent.com/794251/91531766-2927e000-e8c2-11ea-8d7c-a9a0e1019ee4.png)

**Comment by nlowe** [comment]
Sorry, wrong repo!

**Comment by LandonTClipp** [comment]
I was about to say, this is a feature of mockery I have never seen before!
