### ISSUE TITLE
Return Value Provider Functions not working as expected

### ISSUE THREAD

**Issue by baid86** [vektra/mockery#333]
As per the documentation to We could use the function object as return value and the return value of the function will be used as but its not working for me
Here is my Mock
```
// Stats provides a mock function with given fields: msg, macs, startTs, endTs
func (_m *Controller) Stats(msg json.RawMessage, macs []string, startTs int64, endTs int64) ([]json.RawMessage, error) {
	ret := _m.Called(msg, macs, startTs, endTs)
	var r0 []json.RawMessage
	if rf, ok := ret.Get(0).(func(json.RawMessage, []string, int64, int64) []json.RawMessage); ok {
		r0 = rf(msg, macs, startTs, endTs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]json.RawMessage)
		}
	}
	var r1 error
	if rf, ok := ret.Get(1).(func(json.RawMessage, []string, int64, int64) error); ok {
		r1 = rf(msg, macs, startTs, endTs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
```

And here is how I am mocking it

```
Mock.On("Stats", mock.AnythingOfType("json.RawMessage"), mock.AnythingOfType("[]string"), mock.AnythingOfType("int64"), mock.AnythingOfType("int64")).Return(
		func(msg json.RawMessage, mac []string, startTs int64, endTs int64) (retVal []json.RawMessage, err error) {
			retVal = []json.RawMessage{json.RawMessage(`{}`)}
			return retVal, err
		})
```

And I am getting following error
`
panic: interface conversion: interface {} is func(json.RawMessage, []string, int64, int64) ([]json.RawMessage, error), not []json.RawMessage
`

**Comment by ridhoperdana** [comment]
don't you need `()` at the end of the function?

**Comment by Wycers** [comment]
I have also been confused for a long time and finally I found that in your case the mocking should be

``` go
Mock.On("Stats", mock.AnythingOfType("json.RawMessage"), mock.AnythingOfType("[]string"), mock.AnythingOfType("int64"), mock.AnythingOfType("int64")).Return(
		func(msg json.RawMessage, mac []string, startTs int64, endTs int64) (retVal []json.RawMessage) {
			retVal = []json.RawMessage{json.RawMessage(`{}`)}
			return retVal
		},
		func(msg json.RawMessage, mac []string, startTs int64, endTs int64) (err error) {
			return err // or something else
		}
)
```

Noticed that it uses `N` functions as arguments of `.Return` if the mocked function has `N` return values.

**Comment by LandonTClipp** [comment]
@Wycers thanks for figuring that out. This is a huge design wart and doesn't make any sense IMO. 

PRs are welcome to fix this, but a part of me feels this cannot be changed as it is technically part of the API. To make the discussion more visible, I am beginning talks with the stretchr/testify folks to make a mockery v3 that is going to re-do pretty much all of this logic.

**Comment by IronSavior** [comment]
I just found mockery and I like the idea, but I was having the same problem as the OP here. I Just posted about that in a [testify issue](https://github.com/stretchr/testify/issues/350#issuecomment-703792499). Posting it here in case this helps OP in the short term and because this could easily be implemented by a code generator like mockery without changing testify and without changing mockery's API. Cross-posted content follows:

Dynamic/computed returns can be achieved without adding a new feature by doing something like this:

```go
type mockClient struct {
	mock.Mock
}

// Perfectly normal testify mock method implementation
func (m *mockClient) Write(context.Context, lib.WriteRequest) (*lib.WriteResponse, error) {
	args := m.Called(ctx)

	return args.Get(0).(*WriteResponse), args.Error(1)
}

// Any function having the same signature as client.Write()
type WriteFn func(context.Context, lib.WriteRequest) (*lib.WriteResponse, error)

// Expect a call to the mock's Write(ctx, req) method where the return value 
// is computed by the given function
func (m *mockClient) OnWrite(ctx, req interface{}, impl WriteFn) *mock.Call {
	call := m.On("Write", ctx, req)
	call.Run(func(CallArgs mock.Arguments) {
		callCtx := CallArgs.Get(0).(context.Context)
		callReq := CallArgs.Get(1).(lib.WriteRequest)

		call.Return(impl(callCtx, callReq))
	})
	return call
}
```

and then consume it in the test:


```go
func TestThing(t *testing.T){
	t.Run("write", func(t *testing.T){
		client := mockClient{}
		client.Test(t)
		thing := Thing{Client: &client}

		// Keeps track of values written to mock client
		records := []lib.Record{}
		
		ctx := mock.Anything
		req := lib.WriteRequest{Value: "expected value"}
		// If the request doesn't match, the mock impl is not called and the test fails
		client.OnWrite(ctx, req, func(_ context.Context, req lib.WriteRequest) (*lib.WriteResponse, error){
			id := len(records) // ID is computed
			records = append(records, req.Record{ID: id, Value: req.Value})
			return &lib.WriteResponse{ID: id}, nil
		}).Once()

		thing.DoSomethingTestable("expected value")

		client.AssertExpectations(t)
		assert.Contains(t, records, lib.Record{ID: 0, Value: "expected value"})
	})
}
```

**Comment by magicgoose** [comment]
At the very least, the example in README could be modified to show what must be done when the function returns more than one value.

**Comment by LandonTClipp** [comment]
@magicgoose agreed. I'm short on time at the moment, do you have any time to do a huge favor and make that more clear in the readme?

**Comment by magicgoose** [comment]
Yep, I can make a PR

**Comment by LandonTClipp** [comment]
Note that the docs now show that the return value provider functions allow specifying a single function, instead of one per return value. 

https://vektra.github.io/mockery/features/#return-value-providers

Closing this ticket as done.
