### ISSUE TITLE
Remove version from comments

### ISSUE THREAD

**Issue by fewstera** [vektra/mockery#334]
Hi,

We're using mockery for a large project. We often get version control changes on all mockery generated files which are just a change to the comment line at the top of the mock file because a different version of mockery has been used. This is rather annoying as we have to make sure each contributor is using the same version.

I believe it would be better to just mention the major version used to generate the mock or omit it completely.

Thank you,

Aidan

**Comment by HarlamovBuldog** [comment]
Huge plus here, that's a big problem for us as well, as we have a lot of mock files in project.

**Comment by LandonTClipp** [comment]
This is a reasonable request. We can't change the default behavior but what I can do is add a configuration variable in the `.mockery.yaml` file called something like `disable_mock_header` that can be toggled. How does that sound? It should be fairly easy to implement.

**Comment by LandonTClipp** [comment]
v2.3.0 adds this feature, let me know how it works for you.
