### ISSUE TITLE
Incomplete CLI help for --keeptree

### ISSUE THREAD

**Issue by andrejtokarcik** [vektra/mockery#341]
The CLI help for the `--keeptree` option contains "Must be used with XX" which should presumably refer to another CLI option. This seems to be a refactoring leftover, perhaps after vektra/mockery@1549900a3e99e3d13c9585005cbe0922b41e5d35.

https://github.com/vektra/mockery/blob/273cb43816d191e0b2318b205da65784b53b8c0a/cmd/mockery.go#L84

**Comment by LandonTClipp** [comment]
Actually, it seems that was in there pre-refactor: https://github.com/vektra/mockery/commit/1549900a3e99e3d13c9585005cbe0922b41e5d35#diff-94af18853d877b5efdeef40c5bf863e63d65f1487dfdd9c7189f1b2458a31f5dL192

Not sure what the original author meant.

**Comment by LandonTClipp** [comment]
`--keeptree` is going to be deprecated soon in favor of the new `packages` config semantics. We won't be fixing this (unless someone really wants to submit a PR).
