### ISSUE TITLE
[macos] mockery seperate import packages

### ISSUE THREAD

**Issue by seon1-kim** [vektra/mockery#345]
There is already a file created with mockery, and when recreated, mockery separate import package list at the top of code.

```
import (
	something "github.com/some/thing"
	something2 "github.com/some/thing2"
)
```

after `mockery -all`
```
import something "github.com/some/thing"
import something2 "github.com/some/thing2"
```

mockery version is `2.4.0-beta`

**Comment by LandonTClipp** [comment]
This does not happen in the latest version of mockery. Closing.
