### ISSUE TITLE
Not able to generate mocks using docker container of mockery

### ISSUE THREAD

**Issue by baid86** [vektra/mockery#356]
I tried to generate the mocks using docker container will following line

`
❯ docker run vektra/mockery --all --log-level trace

28 Dec 20 10:36 UTC INF Starting mockery dry-run=false version=2.4.0
28 Dec 20 10:36 UTC INF Walking dry-run=false version=2.4.0
`

It does not print any error but did not generate any mocks also.   

The folder from which I am running it has .go files and it does have interfaces which Needed to be mocked. 

What am I missing? 
Am I invoking it right way?

**Comment by baid86** [comment]
Looks like the docker version does not works as expected since could generate the mocks via mockery binary.
```
root@e13aac286487 /home/cambium/cnmaestro-agent/src
❯ ./mockery --all
29 Dec 20 05:29 UTC INF Starting mockery dry-run=false version=0.0.0-dev
29 Dec 20 05:29 UTC INF Walking dry-run=false version=0.0.0-dev
29 Dec 20 05:29 UTC INF Generating mock dry-run=false interface=ConfigInterface qualified-name=cns/cnAgent/agent version=0.0.0-dev
29 Dec 20 05:29 UTC INF Generating mock dry-run=false interface=Controller qualified-name=cns/cnAgent/agent version=0.0.0-dev
29 Dec 20 05:29 UTC INF Generating mock dry-run=false interface=LogConfigInterface qualified-name=cns/cnAgent/logging version=0.0.0-dev
```
For the docker version do I need to mount my workspace somewhere?

**Comment by LandonTClipp** [comment]
This is a known issue, I haven't had a chance to look at it yet. PRs are welcome!

**Comment by LandonTClipp** [comment]
Hi, did you mount your local filesystem into the docker container? 

https://hub.docker.com/r/vektra/mockery

**Comment by baid86** [comment]
Thanks, It worked,
