### ISSUE TITLE
How to mock ... args ?

### ISSUE THREAD

**Issue by zacscoding** [vektra/mockery#365]
Hello, I want to setup and assert of `... parameters` in function.

for example, we have below interface and generated mock
```go
// my interface
//go:generate mockery
type Member interface {
	GetMembers(name ...string)
}

// in test, where Mock is generated from above interface
Mock.On("GetMembers", mock.AnythingOfType("????"))
```

then, is it possible to use mock.Anything or others regardless of argument numbers?

**Comment by mblottiere** [comment]
You'll have to know the exact number of expected arguments.

Matching is done like this:
```go
// expected call
member.GetMembers("one")
// mock
memberMock.On("GetMembers", "one")

// With several arguments
members.GetMembers("one", "two")
// you have to provide the same number of arguments
memberMock.On("GetMembers", "one", mock.AnythingOfType("string"))
```

**Comment by Laisky** [comment]
@zacscoding you could try my fork https://github.com/Laisky/mockery

I add `.Catch` to catch by name with any arguments

**Comment by LandonTClipp** [comment]
How to handle this is described in https://vektra.github.io/mockery/notes/#variadic-arguments

Closing this ticket, but feel free to open another one (or just comment back here) if something is not clear.
