### ISSUE TITLE
How to return custom errors in a mocked interface?  

### ISSUE THREAD

**Issue by stewarthector** [vektra/mockery#366]
I have a interface who's method implementation returns several types of Errors, regular errors and and a custom error:

`type RecordNotFoundError struct {
	ID int
}`

The Mocked function is defined as
```
	mockServiceProvider.
		On("CreateUser", &user).
		Return(nil, repository.RecordNotFoundError{})

```

The function signature is:
`func (p *UserRepoProvider) CreateUser(user *models.User) (*models.User, error) `

In the function under test, the code handles the custom error explicitly, for example:

```
	if err != nil {
		if err == err.(*repo.RecordAlreadyExistsError) {
			ctx.JSON(http.StatusBadRequest, gin.H{"User already exists with that email": err.Error()})
			return
		}
                .... handle error cases ....
	}

```

In the unit test, I'm testing that the RecordAlreadyExistsError error is handled correctly and responds with BadRequest.    

Is this type of test possible with mocks generated with Mockery?   This code executes fine at runtime, and so I'd expect the generated Mock code to allow this too.   

The generated mock code checks explicitly that the error type returned matches Error, otherwise panics with:
`"assert: arguments: Error(1) failed because object wasn't correct type: {}"`

```
if s, ok = obj.(error); !ok {
    panic(fmt.Sprintf("assert: arguments: Error(%d) failed because object wasn't correct type: %v", index, args.Get(index)))
	}
```

How can custom errors be returned in expectations? 

Thanks

S

**Comment by LandonTClipp** [comment]
Hi there. The function signature specifies that you must return an error interface. `repository.RecordNotFoundError{}` is not an error interface, thus the assertion fails.

You need to tell the expectation to return an object that is an error interface. See: https://play.golang.org/p/fO4NXJtPd4g for an example.

**Comment by stewarthector** [comment]
Thank you very much Landon!

**Comment by stewarthector** [comment]
Appreciate the help!  :-)
