### ISSUE TITLE
--exported flag not working

### ISSUE THREAD

**Issue by karlc1** [vektra/mockery#367]
I downloaded mockery today using `go get github.com/vektra/mockery/v2/.../`, so I cannot check exact version number, but `--exported` is documented in `mockery --help` output. Anyway, when I run `mockery --exported --all`, none of my unexported interfaces are generated as exported mocks. Instead, the generated code looks exactly the same as if I omit the --exported flag. Am I doing something wrong or is this broken?

**Comment by LandonTClipp** [comment]
It's possible it's not working correctly, if you can find where in the code it's causing this behavior, we can discuss in more specific detail. PRs are always welcome!

**Comment by ijalalfrz** [comment]
@LandonTClipp i have the same issue my interface is private:

```
type elasticsearchRequest interface {
	Do(ctx context.Context, transport esapi.Transport) (resp *esapi.Response, err error)
}
```
then i did ```mockery --exported --name=elasticsearchRequest```
i try to mock it with mockery v2.7 but the exported interface is still in private

**Comment by LandonTClipp** [comment]
We are going to be deprecating the non-`packages` config semantics pretty soon, so I'm going to mark this as "wontfix". The feature you're looking for is supported in `packages`.
