### ISSUE TITLE
Add ability to skip vendor folder when using --all flag

### ISSUE THREAD

**Issue by romandvoskin** [vektra/mockery#377]
It's possible the folder structure I'm working with is not ideal, however because the `vendor` folder is a sibling of the project's package folders, mockery tries to generate mocks for the contents of the `vendor` folder when using `--all`. This seems like a bug.

**Comment by LandonTClipp** [comment]
I believe this behavior won't exist in the new `packages` feature. I'm going to close this as this issue was created before `packages` was implemented. Please give that a try and open a new issue if it doesn't work with the new config semantics.
