### ISSUE TITLE
Methods with ... params generate broken mocks.

### ISSUE THREAD

**Issue by shawnburke** [vektra/mockery#38]
This is a regression sometime since SHA [a43d734f241595](https://github.com/vektra/mockery/commit/a43d734f24159591e48fb964b3b466ea13fa3272). Not sure exactly when.  

The following interface will generate a mock that doesn't compile:

     type MyInterface interface {
	   WriteItems(uuid string, values ...string) error
     }

The old "working" code generated code that probably wasn't mockable, but it wasn't blocking.

This generates:

    func (_m *MyInterface) WriteItems(uuid string, values ...string) error {
	ret := _m.Called(uuid, values)
	var r0 error
	if rf, ok := ret.Get(0).(func(string, ...string) error); ok {
		r0 = rf(uuid, values)
	} else {
		r0 = ret.Error(0)
    	}
	return r0
    }

Which results in:

     mocks/MyInterface.go:14: cannot use values (type []string) as type string in argument to rf

I think Line 14 needs to be:

     		r0 = rf(uuid, values...)

**Comment by shawnburke** [comment]
Fix PR [here](https://github.com/vektra/mockery/pull/39)

**Comment by evanphx** [comment]
Fix merged! Thanks!
