### ISSUE TITLE
Version generated via go get differs from brew install.

### ISSUE THREAD

**Issue by rahul8590** [vektra/mockery#381]
While installing mockery via go get. I see the following 
```
$ go get github.com/vektra/mockery/v2/.../@v2.7.4
$ ~/go/bin/bin/mockery --version 
22 Apr 21 15:12 PDT INF Starting mockery dry-run=false version=v0.0.0-dev
v0.0.0-dev
```
But, when I try to install the same via brew 

```
$brew install mockery
$mockery --version
22 Apr 21 16:00 PDT INF Starting mockery dry-run=false version=2.7.4
2.7.4
```

This is generally not a big deal. But, the same version number gets populated in generated files. For example, 
```
// Code generated by mockery v0.0.0-dev. DO NOT EDIT.
```
which is not accurate.

**Comment by as-beaulieu** [comment]
My team is seeing the same issue. I installed mockery through `go get` and my mocks are hitting our PR's with v0.0.0-dev. The rest of my team pulled through brew, and they're seeing v2.*.*

Except I can't pull through brew. Brew `install` / `upgrade` / `list` all show not found for mockery

```Error: No such keg: /usr/local/Cellar/mockery```

**Comment by as-beaulieu** [comment]
`brew install mockery` gives this result
```
Updating Homebrew...
error: Not a valid ref: refs/remotes/origin/master
fatal: ambiguous argument 'refs/remotes/origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "mockery".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

```

While `brew upgrade mockery` returns this:

```
Error: No available formula or cask with the name "mockery".
```

**Comment by LandonTClipp** [comment]
Closing as I believe this issue has been fixed.
