### ISSUE TITLE
Obtain the arguments of the function call on the mocked variable

### ISSUE THREAD

**Issue by SUMUKHA-PK** [vektra/mockery#384]
Is there a way to obtain the arguments on the function call of the mocked variable?
This soooo helps out during testing.

**Comment by tidbeck** [comment]
One way to do it (probably not the prettiest):
`myArg := myMock.Calls[len(myMock.Calls)-1].Arguments[0].(*MyArgumentType)`

**Comment by LandonTClipp** [comment]
You can use the [`.Run`](https://pkg.go.dev/github.com/stretchr/testify@v1.8.2/mock#Call.Run) method provided by `testify`, or you can use the [`.RunAndReturn`](https://vektra.github.io/mockery/features/#expecter-structs) method from the expecter structs that will call the function you provide with the arguments that were used in the call.
