### ISSUE TITLE
(devel) version with of prebuild binary (release v2.8.0)

### ISSUE THREAD

**Issue by butuzov** [vektra/mockery#388]
Current (2.8.0) release binary file compiled with `(devel)` version. 

```
curl -Ls https://github.com/vektra/mockery/releases/download/v2.8.0/mockery_2.8.0_Darwin_x86_64.tar.gz | tar -zOxf -  mockery > bin/mockery && chmod +x bin/mockery
./bin/mockery --version
> (devel)
```

so it ends up as in mocks

```diff
-// Code generated by mockery v1.0.0. DO NOT EDIT.
+// Code generated by mockery (devel). DO NOT EDIT.
```

**Comment by LandonTClipp** [comment]
Hi, I'll probably need a revert on the version string change. Apologies for the noise.

**Comment by chenrui333** [comment]
@LandonTClipp I just made the revert that PR and it also unblocks the [homebrew version upgrade](https://github.com/Homebrew/homebrew-core/pull/78314)
