### ISSUE TITLE
More type-safe assertions

### ISSUE THREAD

**Issue by jesseduffield** [vektra/mockery#389]
I went looking for an existing issue for this but couldn't find one.

I would like to have my generated mock include more type-safe assertions. For example if my struct has the following method:

```go
func (obj* MyObj) MyFunc(a int, b int) bool
```
I currently do the following:
```go
testObj.On("MyFunc", 1, 2).Return(false)
```

But I would like to do:
```go
testObj.OnMyFunc(1, 2).Return(false)
```

where OnMyFunc is itself typed to take two arguments exactly, and the object returned has a Return method which requires a bool argument.

This would make it harder to make errors when writing tests, and would alert me to more issues at compile time after I've regenerated my mocks.

The context here is that I'm about to start using this package quite heavily but am wary of how the lack of type safety will make refactoring harder in the future.

Let me know if there's anything I could do to help with this. Thanks :)

**Comment by jesseduffield** [comment]
Ah, I see there is a PR up at the moment for this exact thing: https://github.com/vektra/mockery/pull/344

**Comment by g-w** [comment]
I think the proposal is an improvement on what is implemented in #344. It avoids the possible collisions between different mocks (even if they are unlikely) and yields a compacter and more readable syntax. Would you be interested in an patch implementing this feature?

**Comment by Gevrai** [comment]
Created a PR  #396 that would resolve this issue, in a bit of a different way though

**Comment by LandonTClipp** [comment]
Closing this as we now have an `Expecter()` methodology.
