### ISSUE TITLE
Latest release lacks compiled binaries

### ISSUE THREAD

**Issue by heyvito** [vektra/mockery#394]
Hi there! I have some scripts that automatically downloads mockery, but it failed with version 2.9.0, which for some reason lacks precompiled binaries.

Just a heads-up in case that was unintended.

Cheers!

Edit: Version 2.8.0 reports itself as `version=(devel)`

**Comment by LandonTClipp** [comment]
Hi, I'm aware of the issue. Our entire build pipeline broke when travis-ci was shut down. I have to port it over to github actions. I'm not sure when I can do this as I'll be pretty busy for the next few weeks. If anyone wants to pitch in that'd be great.
