### ISSUE TITLE
Exclude specific subfolder from --all

### ISSUE THREAD

**Issue by lordzsolt** [vektra/mockery#395]
Mostly a followup to #255, with the introduction of go modules, dependencies are in the `vendor` subfolder.

With the command `mockery --all`, mocks will be generated for all interfaces of third party dependencies.

It would be great to have some way of excluding this folders (and potentially other ones). 

Is there a way to do this already?

**Comment by vasconcelosvcd** [comment]
+1

**Comment by Trim21** [comment]
+1

**Comment by AntonioYuen** [comment]
+1

**Comment by alec-w** [comment]
I'd also find this feature useful.

Taking a look at the code it looks like the behaviour change would be within https://github.com/vektra/mockery/blob/8174e46cfded8b352b05339478e6263e30cbecc8/pkg/walker.go#L65

I'd have a stab at a PR on this, but an open question is - should the exclude be just for top level directories or any subdirectory matching a given pattern (and if the latter, how to make sure `root1/foo` is included but `root2/foo` is excluded?)?

**Comment by LandonTClipp** [comment]
Thanks for the engagement everyone. Two quick thoughts I have, please refrain from commenting `+1`, we have thumbs up which serve the same purpose! Second, I'm thinking there are two ways of doing this:

1. Have some config that skips certain subpaths (probably the most intuitive)
2. Have a magic hidden file, like `.mockery_skip` that if the walker finds, will skip the entire subdirectory.

I think 2 is a bit more portable and easier to code for. Which of these would people prefer? Or maybe there is a secret third option I'm missing.

**Comment by alec-w** [comment]
I'd vote for option 2, I hadn't even thought of that alternative!

Imagining code to support this would be simpler which is a big plus. Although config might be more intuitive, the exact way in which the subpaths have to be specified would require reading docs more carefully, whereas the `.mockery_skip` usage should be obvious to anyone familiar with things like `.gitignore`.

**Comment by alec-w** [comment]
PR opened for implementing `.mockery_skip`. First time contributing something more than a trivial doc change to OS so any guidance on improving the PR description / approach very welcome 🙂

**Comment by subtle-byte** [comment]
In my mocks generator it is possible to exclude specific subfolder) https://github.com/subtle-byte/mockigo

**Comment by hedhyw** [comment]
**Option 1:**
There are too many configs these days, but this option is more extensible 👍.


**Option 2:**
1. I am not sure about the `.mockery_skip` method, because if we place it in the `/vendor` directory, then it will be deleted after each `go mod vendor` call.
2. This option may not work with generated files if the generator deletes the folder.
3. It is hard to make new functionality.
    > software entities should be open for extension.

_I see that there is already a PR for this #458._

**Option 3:**
I would be happy to have a flag that provides a regular expression for excluding folders 😥.

P.S.: "Add ability to skip vendor folder when using --all flag": #377

**Comment by mohammadne** [comment]
is there any update on this topic?

**Comment by bdandy** [comment]
Probably skipping vendor should be as default behavior

**Comment by lordzsolt** [comment]
I feel like the .mockery_skip is a horrible approach, the way it's described here. I don't want to create 10+ files for each subfolder.

Why not just have a `.mockery.toml` (or yml or whatever) config file, where you can add the parameters you want, and you can also have `included` and `excluded` flags, which is an array of paths to include or exclude?

Considering it's not a huge sausage shell command that you have to write out with all the parameters, it's nice and easy to understand and maintain.

**Comment by lordzsolt** [comment]
As for anyone that got to this thread, and has the same problem, I managed to solve it by removing the `--all` flag, and find the files myself with `go list`.

`go list -f '{{.Dir}}' ./...  | xargs -n1 mockery --all --case underscore --inpackage --disable-version-string --with-expecter --note "NOTE: run 'make update-mocks' to update this file and generate new ones." --dir`

You can also use `grep` to exclude certain stuff, if you would like.

`go list -f '{{.Dir}}' ./... | grep -v "stuff-to-exclude" | xargs -n1 $(shell pwd)/bin/mockery --all --case underscore --inpackage --disable-version-string --with-expecter --note "NOTE: run 'make update-mocks' to update this file and generate new ones." --dir`

**Comment by LandonTClipp** [comment]
Circling back on this, I am in favor of adding a configuration parameter to exclude directories. Please do submit a PR, if it's good then we can get it merged!

**Comment by amirbenun** [comment]
Hey @LandonTClipp,
I opened a PR with the changes you suggested https://github.com/vektra/mockery/pull/596.
Hopefully we can push it forward.
