### ISSUE TITLE
v2.9.0 has wrong version string

### ISSUE THREAD

**Issue by MyChaOS87** [vektra/mockery#397]
```
# go install github.com/vektra/mockery/v2@v2.9.0
# mockery --version                             
21 Jul 21 14:14 CEST INF Starting mockery dry-run=false version=v0.0.0-dev
v0.0.0-dev
```

version reported is v0.0.0-dev
same is put up in generated files

```
// Code generated by mockery v0.0.0-dev. DO NOT EDIT.
```

**Comment by williambanfield** [comment]
I've noticed this as well. It looks like the config package defines a default version string, here: https://github.com/vektra/mockery/blob/master/pkg/config/config.go#L4.

This version variable is then filled in in the `goreleaser` step here:
https://github.com/vektra/mockery/blob/master/.goreleaser.yml#L9

The result is that when getting mockery using `go get`, the version will not be filled in. Looks like this was fixed previously:
https://github.com/vektra/mockery/issues/362
Perhaps the fix this is the same?
