### ISSUE TITLE
Parse multiple interfaces with --name or add an option to ignore some files

### ISSUE THREAD

**Issue by mahdi1008** [vektra/mockery#409]
I want to use mockery on my project, but I want to declare what exact interfaces I need to mock or ignore some exact interfaces and I want to add that command in my project description that everyone could have the same output.

I read docs and issues but i didn't find any provide a solution for this problem. The best solution I came with is having multiple lines of making mocks using --name flag.

**Comment by LandonTClipp** [comment]
I think a naive solution should be fairly simple to code up, just make the `name` variable a string slice and create a for loop over that. PRs welcome!

**Comment by positiveblue** [comment]
Hi, I could really make use of this feature. I wrote a first approach in #418 The main idea is to:

- Take whatever comes as a value of `--name` and split it by the `,` separator.
- Create the right regex for each name value and set it in the walker.
- While processing a new interface, check for each one of the valid regex (`filters`) and if it is a match create the mock.

Let me know if I am missing anything.

**Comment by borisbsv** [comment]
I'd appreciate this feature as well, we generate some 20-ish mocks by chaining a mockery invocation for each one - being able to fit them all in a single command like this or with a config file would be amazing.

**Comment by subtle-byte** [comment]
Probably my mocks generator can be useful here. https://github.com/subtle-byte/mockigo

**Comment by LandonTClipp** [comment]
This functionality is given for free when using the `packages` feature. You can specify the exact interfaces you want mocked. We _don't_ have the ability to do something like:

```yaml
packages:
  github.com/user/project:
    config:
      all: True
    interfaces:
      interfaceName:
        config:
          disable: true
```
But that would be very easy to code up. Feel free to submit a PR if you want that added. We won't be adding this to the non-packages config schema since I plan on deprecating it soon.
