### ISSUE TITLE
Is build tag supported?

### ISSUE THREAD

**Issue by feiyushi** [vektra/mockery#410]
We have a build tag on two go files and both contain a method that's part of the interface. The method has different implementations in both files. When building, only one file will be compiled depending on the build tag.
When I run `mockery --all`, it complains about `ERR Error parsing file` and about missing the method that's in the files.
When I remove the tag in either files, the commands succeeds.

Is there a way to pass the build tag to the mockery so that it recognize which file to look at?

**Comment by LandonTClipp** [comment]
I don't think so, but PRs would be welcome!

**Comment by feiyushi** [comment]
just found out that it's already supported: https://github.com/vektra/mockery/blob/546b33489df53ed09e5714f46872e368ecb4b632/cmd/mockery.go#L66.
didn't look closer. thanks anyway!
