### ISSUE TITLE
Homebrew: Calling bottle :unneeded is deprecated

### ISSUE THREAD

**Issue by SVilgelm** [vektra/mockery#414]
`brew upgrade` reports a warning:
```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the vektra/tap tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/vektra/homebrew-tap/Formula/mockery.rb:9
```

Fix is very trivial, you just need to release new version, `goreleaser` already has a fix https://github.com/goreleaser/goreleaser/issues/2595

**Comment by lookfirst** [comment]
@LandonTClipp how about a new release please?

**Comment by SVilgelm** [comment]
hmm, the problem exists only in the `vektra/homebrew-tap` but the formulae in the `homebrew-core` is correct

**Comment by LandonTClipp** [comment]
We've had a few upgrades since this ticket was create, @SVilgelm are there still issues with this?
