### ISSUE TITLE
incorrect coverage percentage when generate with inpackage

### ISSUE THREAD

**Issue by 1mdc** [vektra/mockery#420]
Generated mock files in packages count toward to the over all coverage. For example, I have 100% coverage, but with mock_ files it becomes 50%. How can we make `go test --cover ...` ignore `mock_...` files?

**Comment by 1mdc** [comment]
I found the answer. I can specify --testonly so it adds suffix _test to the file which will be excluded.

**Comment by khareyash05** [comment]
Hi @hoangong , can you explain a bit deeper? I am using mocks to find coverage, how can i ignore these files
