### ISSUE TITLE
How to generate code with build tags

### ISSUE THREAD

**Issue by 1mdc** [vektra/mockery#421]
Hi, I would like to generated code has a build tag such as: 
```
//go:build ignore
```
so that build ignore mock files. I tried to run with:
```
mockery --all --inpackage --tags="ignore"
```
but it does not generate the tags, may be I misunderstood the --tags flag here?

**Comment by xmlking** [comment]
same issue for me. how do you fix it ?

```go
//go:generate mockery --name=ProfileRepository --case=snake --tags="mock"  --testonly
type ProfileRepository interface {
...
}
```

**Comment by Limero** [comment]
@hoangong @xmlking @CatCanCreate Did you ever solve this? I have the same issue of whatever I pass as tags, the generated output is unchanged.

**Comment by CatCanCreate** [comment]
> @hoangong @xmlking @CatCanCreate Did you ever solve this? I have the same issue of whatever I pass as tags, the generated output is unchanged.

```
❯ cat .mock
//go:build tests
```

```
mockery ... --boilerplate-file=.mock
```

**Comment by Limero** [comment]
> > @hoangong @xmlking @CatCanCreate Did you ever solve this? I have the same issue of whatever I pass as tags, the generated output is unchanged.
> 
> ```
> ❯ cat .mock
> //go:build tests
> ```
> 
> ```
> mockery ... --boilerplate-file=.mock
> ```
> 
> @Limero

That works! Thank you!
