### ISSUE TITLE
Installing `mockery` using `go install` rather than `go get`

### ISSUE THREAD

**Issue by avinash-getmega** [vektra/mockery#424]
With go 1.16, `go get` is being deprecated to install any module.

And using `go install  github.com/vektra/mockery/v2/.../` gives the following error: `go: warning: "github.com/vektra/mockery/v2/..." matched no packages`

Expected behaviour was to install `mockery` using `go install`.

**Comment by breeswish** [comment]
I think you can use `go install github.com/vektra/mockery/v2`.

**Comment by 4k1k0** [comment]
@avinash-getmega 

```shell
go install github.com/vektra/mockery/v2@latest
```

should work.

But yes, the README needs an update.

**Comment by LandonTClipp** [comment]
Thanks I will update the readme!

**Comment by LandonTClipp** [comment]
https://github.com/vektra/mockery/commit/b702d895c7a3b0b79926c2ca556a1e1810e6d779
