### ISSUE TITLE
Generate mock with inpackage but inside the folder mocks

### ISSUE THREAD

**Issue by pararang** [vektra/mockery#430]
I want to generate the mock like this
```
-- root/
  -- main.go
  -- package1/
     -- package1Interface.go
     -- mocks/
        -- package1Interface.go
  -- package2/
     -- package2Interface.go
     -- mocks/
        -- package2Interface.go
```
try using the `mockery --inpackage --all`, but the mock generated is go file (mocks_packageInterface.go) and not created inside new file mocks.

**Comment by pararang** [comment]
temporarily I solved the problem by creating a makefile command to generate mocks in each specific directory like below
```Makefile
mock :
    @mockery --dir=${PWD}/root/package1 --all --output=${PWD}/root/package1/mocks
    @mockery --dir=${PWD}/root/package2 --all --output=${PWD}/root/package2/mocks
```

**Comment by oniharnantyo** [comment]
Is there any other solution or this feature not yet supported?

**Comment by LandonTClipp** [comment]
The configuration semantics used in this issue is deprecated. Please switch to [`packages`](https://vektra.github.io/mockery/v2.31/configuration/#recommended-basic-config), this type of thing is easily describable to mockery using the provided config.

Lmk if you have any questions. Thanks! @oniharnantyo

**Comment by ugurcanerdogan** [comment]
> The configuration semantics used in this issue is deprecated. Please switch to [`packages`](https://vektra.github.io/mockery/v2.31/configuration/#recommended-basic-config), this type of thing is easily describable to mockery using the provided config.
> 
> Lmk if you have any questions. Thanks! @oniharnantyo

Packages configurations are not supoorting this functionality. See: #202

**Comment by LandonTClipp** [comment]
It is incorrect that packages does not support this functionality, please read the docs carefully.

https://vektra.github.io/mockery/v2.51/configuration/#layouts
