### ISSUE TITLE
Incorrect mock for interface where method returns a function with a variadic argument

### ISSUE THREAD

**Issue by danfairs** [vektra/mockery#431]
Our codebase has an interface which looks, broadly, like this:

```
type Logger interface {
	LogMethod(level Level) func(string)
	LogMethodf(level Level) func(message string, a ...interface{})
}
```

mockery (2.9.4) generates an implementation for `LogMethodf` as follows:

```
// LogMethodf provides a mock function with given fields: level
func (_m *Logger) LogMethodf(level observable.Level) func(string, []interface{}) {
	ret := _m.Called(level)

	var r0 func(string, []interface{})
	if rf, ok := ret.Get(0).(func(observable.Level) func(string, []interface{})); ok {
		r0 = rf(level)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(string, []interface{}))
		}
	}

	return r0
}
```

Instances of this mock don't fulful the `Logger` interface above, with the compile error:

```
.Logger does not implement observable.Logger (wrong type for LogMethodf method)
		have LogMethodf(observable.Level) func(string, []interface {})
		want LogMethodf(observable.Level) func(string, ...interface {})
```

I would expect the correct method signature to be generated.

**Comment by alec-w** [comment]
Believe the linked PR may be a way to resolve this - but could do with some thoughts on whether this is the best way to resolve this, feels like a bit of a hack in the internals?

**Comment by christeredvartsen** [comment]
This is still an issue it seems. I'm currently using `v2.29.0`.

**Comment by fatceken** [comment]
same here
Any update on this ?
for workaround I had to change generated code manually which I did not like to do

**Comment by LandonTClipp** [comment]
Duplicate issue: https://github.com/vektra/mockery/issues/707

**Comment by LandonTClipp** [comment]
If anyone wants to take a stab at this, it should be pretty straightforward. My diagnosis is here: https://github.com/vektra/mockery/issues/707#issuecomment-1727986731

**Comment by nicovak** [comment]
I opened a PR - Don't hesitate to have a look and post feedback, thanks!

**Comment by LandonTClipp** [comment]
Fixed in the linked PR.
