### ISSUE TITLE
[Feature Request] Add mock.AnyArgs

### ISSUE THREAD

**Issue by sonalys** [vektra/mockery#433]
Currently, whenever we are just interested in mocking results, and not validating arguments, we have to put mock.Anything in each argument of a `mock.On("funcName", mock.Anything, mock.Anything...)` and whenever we change the signature of a function, we have to go through all the mocked calls of that function and put or remove additional mock.Anything.

I think it would be great to have a configuration or a mock.AnyArgs to all args to be defaulted to mock.Anything, so we dont have errors during tests, while reducing the maintenance cost of refactoring the signatures

**Comment by Laisky** [comment]
why closed? this is a useful feature for function with `args ...interface{}` as arguments.
