### ISSUE TITLE
mockery v2.10.0 cannot generate file on go1.18

### ISSUE THREAD

**Issue by ilovejs** [vektra/mockery#434]
## How to reproduce

mockery version: v2.10.0
**env**: go 1.18
**demo repo**: https://github.com/sgreben/testing-with-gomock
output:
❯ mockery --dir=doer --name=Doer
16 Mar 22 10:48 AEDT INF Starting mockery dry-run=false version=v2.10.0
16 Mar 22 10:48 AEDT INF Walking dry-run=false version=v2.10.0
16 Mar 22 10:48 AEDT FTL Unable to find 'Doer' in any go files under this path dry-run=false version=v2.10.0
> cd doer
❯ mockery --all
16 Mar 22 10:49 AEDT INF Starting mockery dry-run=false version=v2.10.0
16 Mar 22 10:49 AEDT INF Walking dry-run=false version=v2.10.0
❯ ls
doer.go

## Other bugs
in a larger private repo, `internal error`
2022/03/16 10:50:38 internal error: package "net/http" without types was imported from "xxx"

## Possible reason
when downgrade to `go1.16.15` it works for my larger scale project but failed on that demo repo up there
so it's a positive feedback

**Comment by taylor-woodcock** [comment]
Having the same issue with 1.18 `internal error: package "fmt" without types was imported from ...`

**Comment by jcobhams** [comment]
Having similar issue with the error message
`invalid operation: ctx.Value(some_key) (value with invalid type) is not an interface" dry-run=false version=v2.9.4`

Go Version: 1.18

**Comment by yanghp** [comment]
yes, Having the same issue with 1.18 internal error: package "context" without types was imported from ....
running "mockery": exit status 1

**Comment by yanghp** [comment]
> 

update to mockery version:  v2.10.0 is ok

**Comment by DillonStreator** [comment]
Has similar issue with system version overriding user version of mockery
```sh
which mockery
/usr/local/bin/mockery
```
```sh
rm /usr/local/bin/mockery
```
```sh
go install github.com/vektra/mockery/v2@latest
```
```sh
which mockery
/Users/{username}/go/bin/mockery
```
mockery worked again after running this

**Comment by BenShaffer** [comment]
> Has similar issue with system version overriding user version of mockery
> 
> ```shell
> which mockery
> /usr/local/bin/mockery
> ```
> 
> ```shell
> rm /usr/local/bin/mockery
> ```
> 
> ```shell
> go install github.com/vektra/mockery/v2@latest
> ```
> 
> ```shell
> which mockery
> /Users/{username}/go/bin/mockery
> ```
> 
> mockery worked again after running this

@DillonStreator Which go version are you using? Which mockery version was your command using before and after the change?

It's possible that a similar issue existed in a previous version of mockery, but I'm suspect that this issue would be resolved without code changes in this repo.

For reference, I am using Go 1.18 with Mockery 2.10.0 and am able to consistently reproduce the issue in the original post.

**Comment by cfstras** [comment]
This is a bit confusing... The binary downloaded from https://github.com/vektra/mockery/releases/tag/v2.10.0 (darwin_arm64) reports an error:

```
➜  ~/Downloads/mockery_2.10.0_Darwin_arm64/mockery --name Client
23 Mar 22 09:35 CET INF Starting mockery dry-run=false version=v2.10.0
23 Mar 22 09:35 CET INF Walking dry-run=false version=v2.10.0
2022/03/23 09:35:59 internal error: package "net/http" without types was imported from "<snip>"
```

But running `go install` manually works:
```
➜ go install github.com/vektra/mockery/v2@v2.10.0

➜ $GOBIN/mockery --name Client
23 Mar 22 09:37 CET INF Starting mockery dry-run=false version=v2.10.0
23 Mar 22 09:37 CET INF Walking dry-run=false version=v2.10.0
23 Mar 22 09:37 CET INF Generating mock dry-run=false interface=Client qualified-name=<snip> version=v2.10.0
```

Both report the same version, was the release built from the wrong tag?

**Comment by atombender** [comment]
The release is presumably built with Go 1.17, while `go install` builds it using your local Go 1.18.
