### ISSUE TITLE
Make docker images for linux arm64

### ISSUE THREAD

**Issue by jokaorgua** [vektra/mockery#440]
Hello. Could you please build and upload docker images for linux/arm64 arch? 

Thanks

**Comment by LandonTClipp** [comment]
Hi are you asking for arm64 or amd64? (the title and description are different)

**Comment by LandonTClipp** [comment]
Hi there, we would like to support this. The change will require changes to the docker publishing workflow.

https://docs.docker.com/desktop/multi-arch/#build-multi-arch-images-with-buildx

PRs are welcome, I probably won't have time to do this soon.

**Comment by jokaorgua** [comment]
@LandonTClipp could you give a hint on how the docker build is made and pushed to dockerhub right now? I can not find any docker push command in GitHub workflows
