### ISSUE TITLE
Feature: Enable Expecter interface by default in V3

### ISSUE THREAD

**Issue by LandonTClipp** [vektra/mockery#447]

**Comment by vtopc** [comment]
Why not do this in v2? Is it breaking anything?

**Comment by LandonTClipp** [comment]
The expecter interface is already available but we can't enable it by default as that would be a ginormous breaking change.

**Comment by LandonTClipp** [comment]
I guess what I actually meant by this ticket is I wanted it to be the only way mocks are generated. So we can't do that in v2 as that would break everyone not using the expecter interface.
