### ISSUE TITLE
README.md example not working as expected

### ISSUE THREAD

**Issue by brycefisher** [vektra/mockery#45]
I want to mock out a method that needs to respond with different return values and make assertions about its parameters. The [example in the README](https://github.com/vektra/mockery#return-value-provider-functions) looked like it does exactly what I want. However, I was unable to get mockery (or Testify more accurately) to run my lambda function and return its return values.

Here's the closest I could come to following the instructions:
https://github.com/brycefisher/mockerytest

Am I doing something wrong here? It feels like I'm following the directions from the README. Thanks for your help!!

**Comment by evanphx** [comment]
Ok, I see what you did. The example is wrong because it's expecting an argument as well, if you make it just `Passthrough() string` it will work. Otherwise you can also pass in a string like `.On("Passthrough", "whatever")`.

**Comment by evanphx** [comment]
Actually, looking at the example again, it's correct as it's passing `AnythingOfType("string")` as the argument to `passthrough`, which is a magic type defined by `github.com/stretchr/testify/mock`.

**Comment by brycefisher** [comment]
Derrrr --- having more experience with testify mocks now, I see that this was a beginner mistake on my part. Apologies!
