### ISSUE TITLE
Generated Mock Constructors can't be used with Ginkgo

### ISSUE THREAD

**Issue by kgadams** [vektra/mockery#461]
Description
-------------

Generated Mock constructors incompatible with Ginkgo

Version
--------

v2.12.1

Steps to Reproduce
------------------

1. Generate any Mock.
2. Try to instantiate it with:
```
import . "github.com/onsi/ginkgo/v2"

var _ = Describe("fails", func(){
  _ = NewMock(GinkgoT())
})
```

### Expected Behavior

Should build.

### Actual Behavior

Does not build, because `testing.TB` can't be implemented from other packages.

**Comment by LandonTClipp** [comment]
Ginko/v2 uses go1.18 features which mockery does not support at this time.

**Comment by dgunay** [comment]
Why is it necessary to use `testing.TB` instead of just `testing.T`? I can't see any part of the generated code that needs the `B` parts of the interface, only `T`.

**Comment by kgadams** [comment]
Hi, this is not about the generics. This is about the fact that the CTors generated by mockery can't be used with `GinkgoT()`, because the interface you chose to use (`testing.TB`) can not be implemented by other packages.

It would be moch more usable if you would create your own interface in `testify/mock`, looking exactly like `testing.TB`, but minus the `private()` method. Then create CTors that take this interface as argument. This way one could invoke the CTors with the return value of `GinkgoT()`.

**Comment by cfiderer** [comment]
This is how interfaces in Go are meant to be: you (as consumer) define an interface that exactly suits your needs, and any object that fulfills the interface can be used (passed in) there.

So your interface should contain only the subset from `testing.TB` that is actually used in the generated methods:
```
type Cleaner interface {
    Cleanup(func())
}
```
or you could add the `Cleanup(func())` to the (already used) `mock.TestingT` interface.

**Comment by LandonTClipp** [comment]
Okay I see what the issue is. The interface we're using is indeed too broad, so we can probably change it to use what `testify.mock.Mock.Test` is expecting which is their [TestingT](https://pkg.go.dev/github.com/stretchr/testify/mock#TestingT) interface.

Let me know if you think this is doable. If so PRs are welcome, otherwise I'll see if I can get to it in the coming weeks.

**Comment by kgadams** [comment]
Unfortunately this `TestingT` interface does not include the `Cleanup()` method you are using. But something along those lines would solve the problem.

**Comment by LandonTClipp** [comment]
Sure yeah we can basically just make an interface embeds `TestingT` (which will always be a hard requirement) plus anything else in use by mockery, that's very easy to do.

**Comment by LandonTClipp** [comment]
@kgadams I found some spare time and put in a PR for you that should fix the issue. Feel free to post your comments/suggestions/concerns where appropriate: https://github.com/vektra/mockery/pull/466
