### ISSUE TITLE
Fails to parse types in a different file of the same package

### ISSUE THREAD

**Issue by rebecca2000** [vektra/mockery#468]
Description
-------------

In a project with A.go
```
package go_example

type A interface {
	doStuff(b B)
}
```
and B.go
```
package go_example

type B struct {}
```
running `mockery --all` results in error
```
Error parsing file error=".../go-example/A.go:4:12: undeclared name: B"
```
Mockery runs as expected when B is moved to a different package

Version
--------

v2.12.1

### Expected Behavior

A mock is generated for `type A`

### Actual Behavior

`type B` is not recognised

**Comment by LandonTClipp** [comment]
Could you provide the stack trace if mockery provided one?

**Comment by rebecca2000** [comment]
Actually... I revisited this issue and it's a mistake from my side. I will close this now, sorry for taking your time.
