### ISSUE TITLE
Mockery also generates mocks for interfaces inside mock*.go

### ISSUE THREAD

**Issue by tinoquang** [vektra/mockery#471]
Description
-------------

- When using `--inpackage` flag, `mock` files also contain an inteface, sth like this:

> type NewMockPublisherT interface {
	mock.TestingT
	Cleanup(func())
}
- Then in the next run, mockery also generates mock file for this interface, which I think is redundant

Version
--------

v2.12.3

Steps to Reproduce
------------------

1. Generating mocks with `--inpackage` flag
2. Generating mocks one more time

### Expected Behavior

- Only mocks for actual interfaces are generated, not interfaces inside mock files

### Actual Behavior

- New mock files will also be created for interfaces inside previous mock files

**Comment by LandonTClipp** [comment]
I think this is a regression after we introduced `testingT` interfaces inside of the mock files. We'll need to figure out a way to exclude files that contain the preamble comment at the top of mock files.

**Comment by tinoquang** [comment]
What I did temporarily is removing all the mock files first, then generating mocks again (I did it with Makefile). Can we use that approach for this case?

**Comment by tinoquang** [comment]
I see. So currently the finest solution could be igoring files that begin with `Generated with mockery`. Is that what you mean?

**Comment by LandonTClipp** [comment]
This has been fixed in the most recent version. https://github.com/vektra/mockery/pull/472

**Comment by tinoquang** [comment]
Sorry for the late response. I agree that the solution is a bit tricky, haha. I already tried your solution before and realized that we couldn't just check the file header since `loadPackages` function always get all the interfaces inside a pkg (including the mock interface). Good to see it's been fixed
