### ISSUE TITLE
Running under go 1.18 throws 'package without types' error

### ISSUE THREAD

**Issue by pantsmann** [vektra/mockery#475]
Description
-------------

`go generate` runs `mockery --name .*`
When I ran this under go 1.17 there are no problems. After upgrading to go 1.18 I get an error: 
`internal error: package "privaterepo/pkgone" without types was imported from "privaterepo/pkgtwo"`

Version
--------

`mockery --version` outputs:
`07 Jun 22 18:48 MDT INF Starting mockery dry-run=false version=v0.0.0-dev
v0.0.0-dev`

I installed mockery_2.13.0-beta.1_Darwin_x86_64.tar.gz

Steps to Reproduce
------------------

Explained above. Note: I kept go 1.17 on my machine and running `go1.17 generate` has no problem.

### Expected Behavior

mocks to be created

### Actual Behavior

Got an error.  See description

**Comment by LandonTClipp** [comment]
Hi, can you provide a reproducer?

**Comment by bandesz** [comment]
We had the same issue using Go 1.18.2, but after upgrading mockery to v2.13.0, the errors went away.

**Comment by AlexCuse** [comment]
I was seeing this error with an older version as well but it stopped on update.  I am getting invalid mocks generated now (imports "github.com/nats-io/") but I think it is probably due to weirdness of my interface.  

```
import "github.com/nats-io/nats.go"

type Msg = nats.Msg
type MsgHandler = nats.MsgHandler
type Subscription = nats.Subscription

// Connection provides an interface over basic *nats.Conn methods that we need to interact with the broker
type Connection interface {
	// QueueSubscribe subscribes to a NATS subject, equivalent to default Subscribe if queuegroup not supplied.
	QueueSubscribe(string, string, MsgHandler) (*Subscription, error)
	// PublishMsg sends the provided NATS message to the broker.
	PublishMsg(*Msg) error
	// Drain will end all active subscription interest and attempt to wait for in-flight messages to process before closing.
	Drain() error
}
```

**Comment by maja42** [comment]
This happens to me since I updated to go1.20

**Comment by jonmol** [comment]
Having the same problem with go 1.20.1. Created a simple repo for reproduction https://github.com/jonmol/mockery-test

**Comment by LandonTClipp** [comment]
I ran your reproducer and was not able to get the same error:

```
$ go generate generate.go
22 Mar 23 10:16 CDT INF Starting mockery dry-run=false version=v2.20.0
22 Mar 23 10:16 CDT INF Using config:  dry-run=false version=v2.20.0
22 Mar 23 10:16 CDT INF Walking dry-run=false version=v2.20.0
22 Mar 23 10:16 CDT INF Generating mock dry-run=false interface=IFoo qualified-name=github.com/jonmol/mockery-test version=v2.20.0
```

This means that it's almost guaranteed to be an environment issue. Please ensure you run `go mod tidy` on all your repos you're operating on, and also ensure that your entire local golang package cache has been wiped.

**Comment by jonmol** [comment]
`go clean -modcache` fixed it, thanks for pointer @LandonTClipp

**Comment by guettli** [comment]
See FAQ: https://vektra.github.io/mockery/v2.35/notes/#internal-error-package-without-types-was-imported

**Comment by ghost** [comment]
``` make mocks        
which mockery || go install github.com/vektra/mockery/v2@v2.50.0
/Users/gaurav.tiwary/go/bin/mockery
mockery --config .mockery.yaml
22 Apr 25 10:22 IST INF Starting mockery dry-run=false version=v2.50.0
22 Apr 25 10:22 IST INF Using config: .mockery.yaml dry-run=false version=v2.50.0
2025/04/22 10:22:32 internal error: package "bytes" without types was imported from "github.com/atlanhq/horizon-api/internal/pkg/quality-assurance"
make: *** [mocks] Error 1
```
I am getting this issue when i am trying to run `make mocks` for my project my go version is `go version go1.24.2 darwin/arm64` and i am using mockery 2.50. What could be the issue?

**Comment by myway-it** [comment]
The fix in my case was to update to the latest mockery v2 version (v2.53.4).

**Comment by jeremyalv** [comment]
> The fix in my case was to update to the latest mockery v2 version (v2.53.4).

Thanks for this. It resolved the issue in my case.
