### ISSUE TITLE
Warning about using `go install` when it is not used to installed Mockery

### ISSUE THREAD

**Issue by jwair** [vektra/mockery#476]
Description
-------------

A warning is displayed with a big `DEPRECATION WARNING` message about installing Mockery using `go install` while it is not applicable.

This is the error message I am getting
`Using go install to download mockery will likely break after June 1, 2022. Please view PR #456 for details.`

I have installed Mockery using `brew` as described in the README, and I don't have it installed via `go install`
```
bash-3.2$ which mockery
/opt/homebrew/bin/mockery

bash-3.2$ ls $GOPATH/bin/mockery
ls: /Users/ajjwair/go/bin/mockery: No such file or directory
```

Version
--------

v2.12.3

Steps to Reproduce
------------------

1. Ensure you do not have Mockery installed in your `$GOPATH/bin` directory
2. Ensure you have Mockery v.2.12.3 installed in some other way (e.g. brew install mockery)
3. Run any command with Mockery v2.12.3
e.g.
```
bash-3.2$ mockery --version
08 Jun 22 12:49 CDT INF Starting mockery dry-run=false version=v2.12.3
08 Jun 22 12:49 CDT WRN !!! DEPRECATION NOTICE !!! dry-run=false version=v2.12.3
08 Jun 22 12:49 CDT WRN Using go install to download mockery will likely break after June 1, 2022. Please view PR #456 for details. dry-run=false version=v2.12.3
v2.12.3
```

### Expected Behavior

No warning is logged if the deprecation is not applicable to our use case. I.e. if we are not installing Mockery using `go install`.
Warning log messages are seen as issues or 'needs attention' at least, but there is nothing to be done about this one. It is creating unnecessary noise.

### Actual Behavior

A not-applicable deprecation warning is shown. E.g.
```
bash-3.2$ mockery --version
08 Jun 22 12:49 CDT INF Starting mockery dry-run=false version=v2.12.3
08 Jun 22 12:49 CDT WRN !!! DEPRECATION NOTICE !!! dry-run=false version=v2.12.3
08 Jun 22 12:49 CDT WRN Using go install to download mockery will likely break after June 1, 2022. Please view PR #456 for details. dry-run=false version=v2.12.3
v2.12.3
```

**Comment by LandonTClipp** [comment]
There is not an easy way for mockery to tell which method was used so it's logged in every case. Sorry about the noise but you'll only have to deal with it for a bit longer.
