### ISSUE TITLE
Packages with `.` in them are incorrectly imported in mocks

### ISSUE THREAD

**Issue by taylow** [vektra/mockery#481]
Description
-------------

When importing the library `github.com/nats-io/nats.go` and generating mock, the resulting import in the generated mock is missing the `nats.go` part (`github.com/nats-io/`).

Mockery Version
--------

`12.13.1`

Golang Version
--------------

`go1.18 darwin/arm64`

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [x] brew
- [ ] go install
- [x] Other: Another colleague compiled from source and gets the same result

Steps to Reproduce
------------------

1. Add the following import to a file: `nats "github.com/nats-io/nats.go"`
2. Use the package in an interface
3. Generate mocks for said interface
4. Observe that the generated mock import is `nats "github.com/nats-io/"`

### Expected Behavior

I expect to the generated mock to import `nats "github.com/nats-io/nats.go"`

### Actual Behavior

The generated mock imports `nats "github.com/nats-io/"`

**Comment by LandonTClipp** [comment]
There have actually been multiple reports of Nats. The issue is coming from the fact that the package ends in .go and the internal logic is interpreting that as a file path. So if someone could submit a PR to fix it that'd be great.

**Comment by tephromancy** [comment]
Hey, I'm currently working on that issue, it impacts my work and now trying to reproduce the issue in tests. Interestingly, it seems to be more of an issue with package name that the `nats.go` library uses rather than the `.` character in the name...

My testing setup:
<img width="926" alt="image" src="https://user-images.githubusercontent.com/107699825/175779619-93e0f386-df65-4b6b-8ee5-df51bdd693b6.png">

`fixture.go`
```go
package fixture

type DottedModuleType int
```

test interface:
```go
package test

import dottedPackage "github.com/vektra/mockery/fixture.module"

type MyDottedImportInterface interface {
	test(js dottedPackage.DottedModuleType)
}
```

Generated mock (without any issues):
```
// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	fixture "github.com/vektra/mockery/fixture.module"
)

// MyDottedImportInterface is an autogenerated mock type for the MyDottedImportInterface type
type MyDottedImportInterface struct {
	mock.Mock
}

// test provides a mock function with given fields: js
func (_m *MyDottedImportInterface) test(js fixture.DottedModuleType) {
	_m.Called(js)
}

type mockConstructorTestingTNewMyDottedImportInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewMyDottedImportInterface creates a new instance of MyDottedImportInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMyDottedImportInterface(t mockConstructorTestingTNewMyDottedImportInterface) *MyDottedImportInterface {
	mock := &MyDottedImportInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

```

I'm investigating further
