### ISSUE TITLE
mark some interface with mockery_not_gen

### ISSUE THREAD

**Issue by mohammadne** [vektra/mockery#499]
## Description

therse's no issue with the package, this is a feature request.

I want to mark some interfaces that `mockery` understand them and doesn't generate mock code for them when they are explicitly marked to not generate any mock for them.

### Mockery Version

2.14.0

Golang Version

1.18.3

### Expected Behavior

mark interfaces with `//mockery_not_gen`, and don't have any generated code for them

**Comment by LandonTClipp** [comment]
This should be part of the new `packages` feature. We should add a new config variable called `exclude` that specifies interfaces to _not_ generate mocks for.

**Comment by LandonTClipp** [comment]
Closing this issue, the feature we actually implement for this should be in a separate ticket under the `pacakges` config semantics.
