### ISSUE TITLE
mock_ suffix for generated files

### ISSUE THREAD

**Issue by MohammadNE** [vektra/mockery#500]
## Description

whene we use `inpackage` flag for `--all`, the generated files have the `mock_` prefix, I was wonder to know that if it's possible to make `_mock` as suffix for generated files?

### Mockery Version

2.14.0

### Golang Version

1.18.3

### reason

as you know the convention for tests is to write them in `*_test.go` and we have `_test` as suffix and not the prefix, so  I would like to follow the convention.

**Comment by LandonTClipp** [comment]
This functionality can be explicitly controlled by users who use the `packages` feature. Closing this as "completed."
