### ISSUE TITLE
Tests failing on current master

### ISSUE THREAD

**Issue by allentv** [vektra/mockery#502]
Description
-------------

Running `make all` failed

Mockery Version
--------

the latest version

Golang Version
--------------
v 1.19

Installation Method
-------------------

-  Binary Distribution
-  Docker
-  brew
-  go install
- [x] Other: [specify]

Forked this repo and on master branch

Steps to Reproduce
------------------

1. Fork the repo
2. Start docker
3. Run `make all`

### Expected Behavior

All tests pass

### Actual Behavior

Tests are failing. An example of a failure is given below

<img width="838" alt="Screenshot 2022-08-22 at 21 24 15" src="https://user-images.githubusercontent.com/6534992/186012232-6ad4324d-f230-4ee2-b745-2428b83df087.png">

**Comment by iaroslav-ciupin** [comment]
@LandonTClipp is somebody working on this? ☝️
