### ISSUE TITLE
Feature: be able to generate the mock that its interfaces are defined on fields or variables

### ISSUE THREAD

**Issue by MilesLin** [vektra/mockery#505]
Currently, althought we can generate mock when we define an interface with a standard way, for example,
```Go
//go:generate mockery --inpackage --case=underscore --name=myInterface
type myInterface interface {
	getName() string
}
```

Go also allows to define an interface on fields and variables, which seem not to be supported by Mockery yet, for example:
``` Go

type myStruct struct {
	getter interface {
		getName() string
	}
}

func myFunc(myInterface interface {
	getName() string
}){
	name := myInterface.getName()
        ....
}

```

Sometimes, we can use this way to isolate implementation without exporting an interface that is only used in a place.

Any opinions are welcome, and I hope to bring this discussion to see whether mockery can introduce this feature.

**Comment by LandonTClipp** [comment]
We won't be implementing this feature as it's not as easy as you'd think. mockery looks at the top-level scope for named interfaces. Inspecting into inlined interfaces requires us to recurse pretty much arbitrarily deep into all type definitions/function signatures.
