### ISSUE TITLE
Feature Request: Use --case snake by default

### ISSUE THREAD

**Issue by itaranto** [vektra/mockery#507]
Description
-------------

Use `--case snake` by default since it will match Go's style for filenames, having upper-case filenames in Go really looks out of place.

Mockery Version
--------

v2.14.0

Golang Version
--------------

1.19.1

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [ ] brew
- [x] go install
- [ ] Other: [specify]

**Comment by LandonTClipp** [comment]
This feature will be available for free in the `packages` config, you'll be able to name your files and mocks however you want.
