### ISSUE TITLE
Mocks are not work if generated for `internal`

### ISSUE THREAD

**Issue by bdandy** [vektra/mockery#508]
Description
-------------

For project, where mocks are generated recursively with keeptree flag mocks are not working for `internal`
```
mockery -r --keeptree --all --with-expecter --packageprefix mock
```

Mockery Version
--------

v2.14

Golang Version
--------------

1.19

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [ ] brew
- [x] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

1. Create package within internal
2. Generate mocks on top level recursively with `--keeptree`
3. Using generated mocks are not possible

### Expected Behavior

I think when `--keeptree` is used - it shouldn't create internal.

**Comment by Agronis** [comment]
`keeptree` inherently does what you don't want it to do, being that it maintains the directory structure.

If you're attempting to mock something that lives in `internal`, those tests either should exist entirely in `internal` or the mocks should be generated outside of the `internal` structure.

You intentionally can't import `internal` packages into another package that doesn't also live under the same umbrella.

You're seeking a change that circumvents the language design.

**This usually highlights a design problem on the developer's side (respectfully).  If you have a need to access things within `internal` while outside of it, then it likely shouldn't live in `internal`.**

You're better off placing `//go:generate mockery....` inside the `internal` packages you wish to mock, that will specify where & how they should be mocked rather then recursive special handling expectations.
