### ISSUE TITLE
Feature Request: Allow for the generated structs to be of the form <name>Mock

### ISSUE THREAD

**Issue by itaranto** [vektra/mockery#512]
Description
-------------

Allow for the generated structs to be of the form `<name>Mock` instead of `Mock<name>`. Even with the `--all` flag.

Mockery Version
--------

v2.14.0

Golang Version
--------------

go1.19.2

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [ ] brew
- [x] go install
- [ ] Other: [specify]

**Comment by Agronis** [comment]
👍 

Today I have to script out a bunch of `//go:generate...` to accomplish this.

I'd say rather then just giving the ability to swap `Mock` position, provide `--prefix` & `--suffix` args for Struct Names.

**Comment by LandonTClipp** [comment]
This is provided for free in the new `packages` config feature.
