### ISSUE TITLE
Is there a way to mock an anonymous function and call another mock inside it?

### ISSUE THREAD

**Issue by diego-augusto** [vektra/mockery#517]
I am trying to mock a Backoff strategy with the following interface:

```go
type Backoff interface {
	Retry(func() error) error
}
```
and a production code

```go
err = s.serviceX.Retry(func() error {
        data, err = s.serviceY.SomeFunction(queryParams)
	if err != nil {
	        return err
	}
	return nil
})
```

and them in tests, trying...:

```go
serviceX := storeMocks.ServiceXXX(t)
serviceX.On("Retry", mock.AnythingOfType("func() error")).Return(...)

serviceY := storeMocks.ServiceXXX(t)
serviceY.On("SomeFunction", mock.AnythingOfType("string")).Return(...)

```

I'm unsure what the following steps are to call these two functions. The first one is always called. But I'd like to call  `SomeFunction` too.

Currently, I'm not mocking the first function yet, only using a dumb implementation e.g.:

```go
func (c dumbStrategy) Retry(f func() error) error {
	return f()
}

func NewDumbStrategy(err error) Backoff {
	return &dumbStrategy{}
}
```

**Comment by Agronis** [comment]
I'm fairly certain this should work with ease.

I might suggest you use `--with-expecter` when generating the mocks, it provides a direct implementation of the interface so there is no question as to "Am I calling on the correct function?".  Furthermore, it's mockery's preferred implementation.

eg
```
serviceX.EXPECT().Retry(mock.AnythingOfType("func() error")).Return(...)
serviceY.EXPECT().SomeFunction(mock.AnythingOfType("string")).Return(...)
```

Alternatively, might be worth trying..

```
serviceX.EXPECT().Retry(mock.AnythingOfType("func() error")).Return(...).Run(func() error {
    serviceY.EXPECT()....
})
````

Have you debugged to walk the logic as it executes?

**Comment by vaguecoder** [comment]
> The first one is always called. But I'd like to call SomeFunction too.

By this, if you mean you want to call the actual anonymous func that was sent to `Retry` from the mock of `Retry`, you can try using [mock.Matchedby](https://pkg.go.dev/github.com/stretchr/testify/mock#MatchedBy) instead.

A rough example for the same.

### main.go
```go
package main

import (
	"log"
)

type Backoff interface {
	Retry(func() error) error
}

type Client struct{}

func (c *Client) Retry(foo func() error) error {
	return foo()
}

func Operate() error {
	client := Client{}
	foo := func() error {
		return nil
	}
	return client.Retry(foo)
}
func main() {
	if err := Operate(); err != nil {
		log.Fatal(err)
	}
}

```
Removing content of anonymous func for simplifying. But you can add your logic and it can still be called.

### main_test.go
``` go
package main

import (
	"<path-to-mocks>/mocks"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
)

func TestOperate(t *testing.T) {
	retrier := new(mocks.Backoff)

	retrier.On("Retry", mock.MatchedBy(func(foo func() error) bool {
		if err := foo(); err != nil {
			return false
		}

		return true
	})).Return(nil)

	err := Operate()
	assert.NoError(t, err, "unexpected error")
}

```

**Comment by diego-augusto** [comment]
The solution that I found to force call `serviceY`

```go
serviceX.EXPECT().Retry(mock.AnythingOfType("func() error")).Return(nil).Run(
	func(f func() error) {
		f()
	},
)
```

It works, but I'm not sure if is the better way to do that.
