### ISSUE TITLE
Naming convention of generated mock objects

### ISSUE THREAD

**Issue by wolfgangmeyers** [vektra/mockery#52]
I have a scenario like the following:

I defined an interface in a package. Mockery generated a mock object in "mocks" package with the same name.
Typically tests should be written in the same package they are testing - I can't seem to get code coverage to work properly if I don't do it this way. So I tried importing the mock object in the test - but the mock object had imports from my code, resulting in a circular reference. I ended up having to move the mock object into the same package and rename it. It would be nice if mockery could generate mocks so that:

1. the mock for interface Foo becomes mock struct MockFoo
2. the mock is placed in the same package as the interface

I saw an -output argument for mockery, but was unable to get it to output to the current directory:

```
mockery -name=WebUserService -output=.
Generating mock for: WebUserService
Error writing WebUserService: mock.go:1:9: expected 'IDENT', found '.' (and 1 more errors)
```

**Comment by evanphx** [comment]
Use `mockery -inpkg` to tell mockery to put the mocks into the same package as the interface. You can also use `-testonly` so the mock files end with `_test.go`

**Comment by wolfgangmeyers** [comment]
That's exactly what I needed, thanks.
