### ISSUE TITLE
mockery should allow returning values based on some custom logic

### ISSUE THREAD

**Issue by denizgursoy** [vektra/mockery#530]
Description
-------------
In the expect mode, in addition to the Run method there should be a RunAndReturn method which allows users to execute custom logic and then return data based on the logic

Mockery Version
--------

version=v2.16.0

Golang Version
--------------

go1.19.4

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [ ] brew
- [ X ] go install
- [ ] Other: [specify]

### Expected Behavior
I have an interface 

```go
type Executor interface {
	Execute(name string) error
}
```

```go
func Test_Executor(t *testing.T) {
	executor := mocks.NewExecutor(t)
	executor.EXPECT().Execute(mock.Anything).RunAndReturn(func(name string) error {
		if name == "foo" {
			return nil
		}
		return errors.New("invalid data")
	})
	
	executor.Execute("foo") // should return nil
	executor.Execute("bar") // should return errors.New("invalid data")
	
}
```
Thanks....

**Comment by LandonTClipp** [comment]
Good idea. This is already kind-of-sort-of possible using the example in the docs, but I think a more explicit method to do something like this is a good thing.

**Comment by LandonTClipp** [comment]
Closing this in favor of https://github.com/vektra/mockery/issues/537 since that issue has an associated PR and is basically the same thing being discussed here.
