### ISSUE TITLE
Is it possible to return a function that has another function as a parameter?

### ISSUE THREAD

**Issue by diego-augusto** [vektra/mockery#539]
Based on the following code, Is it possible to return a function that has another function as a parameter?

```go
// Interface
type Backoff interface {
	Retry(func() error) error
}

//Mock Setup
myMock := backoffMock.NewBackoff(t)

myMock.EXPECT().Retry(mock.AnythingOfType("func() error")).Return(
        func(f func() error) error {
	        return f()
        },
)

```

I am receiving the following error:

```
cannot use (func(f func() error) error literal) (value of type func(f func() error) error) as error value in argument to myMock.EXPECT().Retry(mock.AnythingOfType("func() error")).Return: missing method Error
```

My goal is to take control of return based on return of `f()` function.

**Comment by diego-augusto** [comment]
If I use `.On` approach works:

```go
boMock.On("Retry", mock.AnythingOfType("func() error")).Return(
	func(f func() error) error {
		err := f()
		return err
	},
)
```

But with `EXPECT` does not.

**Comment by dlwyatt** [comment]
For now, the way to do that is to use `.Call.Return` instead of just `.Return`:

```go
	myMock.EXPECT().Retry(mock.AnythingOfType("func() error")).Call.Return(
		func(f func() error) error {
			return f()
		},
	)
```

**Comment by LandonTClipp** [comment]
> For now, the way to do that is to use .Call.Return instead of just .Return:

@dlwyatt is correct, for now you just need to access the underlying `testify.Call` object. We might have more syntatic sugar to do this in the future but I envision this will basically always work no matter what we do.

**Comment by diego-augusto** [comment]
It worked, ty guys!
