### ISSUE TITLE
Nested interfaces are ignored when generating mocks

### ISSUE THREAD

**Issue by wolfgangmeyers** [vektra/mockery#54]
When generating a mock for io.ReadCloser:

```
// ReadCloser is the interface that groups the basic Read and Close methods.
type ReadCloser interface {
	io.Reader
	io.Closer
}
```

The following mock was generated, without any of the methods defined in io.Reader and io.Closer:

```
type ReadCloser struct {
	mock.Mock
}
```

Not too much work to expand out all of the method definitions myself, but ideally the generator would be able to generate stubs for the nested interfaces.

**Comment by evanphx** [comment]
This is a long standing issue, mockery doesn't go out and find those interfaces mostly because that would require a lot more work. So consider this a limitation for now.

**Comment by arvenil** [comment]
Isn't this the same as https://github.com/vektra/mockery/issues/18 ?

**Comment by robdaemon** [comment]
This isn't the same as #18. 

If you generate a mock for the above presented code, you get an empty mock back:

```go
package mocks

import "github.com/stretchr/testify/mock"

type ReadCloser struct {
	mock.Mock
}
```
