### ISSUE TITLE
Please use godeps or vendoring so we can tell what your dependencies are

### ISSUE THREAD

**Issue by gaffo** [vektra/mockery#55]

**Comment by evanphx** [comment]
The library is supposed to be `go get` able. Are you having an issue with dependencies when using it via `go get`?

**Comment by gaffo** [comment]
No that works

**Comment by muhqu** [comment]
@gaffo you don't need godeps or vendoring to tell what the dependencies are… you can use `go list` instead.
``` bash
$ go list -f '{{ join .Imports "\n" }}' github.com/vektra/mockery/mockery | sort | uniq
bytes
fmt
github.com/vektra/errors
go/ast
go/parser
go/token
golang.org/x/tools/imports
io
os
path/filepath
strings
unicode
```
or 
``` bash
$ go list -f '{{ join .TestImports "\n" }}' github.com/vektra/mockery/mockery | sort | uniq
github.com/stretchr/testify/assert
os
path/filepath
testing
```

or use `go list -json ...` ...

**Comment by gaffo** [comment]
@muhqu if only. that only tells you the names of the deps not the versions. Anyway closing this issue until theres a breaking dep change.
