### ISSUE TITLE
feature request: Way to verify order of mocked methods calls

### ISSUE THREAD

**Issue by despondency** [vektra/mockery#554]
Description
-------------

Idea is that currently there is no way to create an order of calls. Meaning that if I expect a mock to get called first on M1() and then on M2() Once() on both, if I switch their places where they are called in the code the test will pass, even though that logically I've made a mistake since my code should expect first M1() and then M2() and not vice versa.

I am willing to write the code if the feature is accepted. 

Thanks everyone.

**Comment by LandonTClipp** [comment]
testify already provides this functionality for you. You can access the underlying mock object and do the assertions manually using `NotBefore`: https://pkg.go.dev/github.com/stretchr/testify@v1.8.2/mock#Call.NotBefore

The `Mock` object also has the calls that were made in the struct: https://pkg.go.dev/github.com/stretchr/testify@v1.8.2/mock#Mock

I'm open to ideas on making this easier in mockery objects but given this functionality is already provided by testify, I'm inclined to say that this isn't something we should be adding in mockery.

**Comment by Gobd** [comment]
I think slightly modifying the InOrder function from GoMock helps provide this:

```go
func InOrder(calls ...*mock.Call) {
	for i := 1; i < len(calls); i++ {
		calls[i].NotBefore(calls[i-1])
	}
}
```

then pass your mockery calls.
