### ISSUE TITLE
mockery not running on version v2.21.0 failed to read in config

### ISSUE THREAD

**Issue by adehikmatfr** [vektra/mockery#558]
hello I am getting an error like this when running a command in mockery.
golang version : 1.19.4
os: windows

![image](https://user-images.githubusercontent.com/71180979/223016154-1f620924-2ac7-4057-9c01-386ca7cfac70.png)

after I downgraded the mockery version, there was no this issue.

**Comment by LandonTClipp** [comment]
Hi, can you paste the entire warning message?

**Comment by adehikmatfr** [comment]
sure
```
06 Mar 23 10:43 +07 WRN failed to read in config error="Config File \".mockery\" Not Found in \"[C:\\\\gitlab.vitamincode.id\\\\keloola\\\\integration\\\\keloola-integration C:\\\\gitlab.vitamincode.id\\\\keloola\\\\integration C:\\\\gitlab.vitamincode.id\\\\keloola C:\\\\gitlab.vitamincode.id C:\\\\ C:\\\\Users\\\\Administrator]\"" version=v2.21.0
06 Mar 23 10:43 +07 INF Starting mockery dry-run=false version=v2.21.0
06 Mar 23 10:43 +07 INF Using config:  dry-run=false version=v2.21.0
Error: failed to get package from config: failed to read file: : open : The system cannot find the file specified.
```

**Comment by LandonTClipp** [comment]
Hmm it appears it's trying to open a file with no name.... I'll have to dig into this. Strange I did not see this in the testing.

**Comment by LandonTClipp** [comment]
@adehikmatfr are you using a mockery config file or does the `.mockery.yaml` file not exist in your project?

**Comment by adehikmatfr** [comment]
i am not using using a mockery config file or does the .mockery.yaml, but this error also appears when I run mockery --version.

**Comment by LandonTClipp** [comment]
Okay I know what the issue is, frustrated I didn't catch this but it's an easy fix. Thanks for the report.

**Comment by LandonTClipp** [comment]
@adehikmatfr please try 2.21.1 and let me know if you experience the same problem.

**Comment by NickBelhomme** [comment]
```07 Mar 23 10:37 UTC WRN failed to read in config error="Config File \".mockery\" Not Found in \"[/go/internal/app/infrastructure/utils/dbutils /go/internal/app/infrastructure/utils /go/internal/app/infrastructure /go/internal/app /go/internal /go / /home/www]\"" version=v2.21.1
```

We are not using any config files for mockery.

**Comment by idefixcert** [comment]
I tested today with 2.21.1 "warning still exists.

07 Mar 23 12:49 CET WRN failed to read in config error="Config File \".mockery\" Not Found xxxxx version=v2.21.1

**Comment by LandonTClipp** [comment]
I think the warning happened in previous versions, I will double check. As long as it’s not crashing the app that is the important thing. But maybe a warning is too alarming of a message to get if running without config is supported.

**Comment by LandonTClipp** [comment]
@idefixcert v2.21.2 has lowered this message to INFO level since this is not actually something we should warn about.
