### ISSUE TITLE
Mock file name doesn't have "mock_" prefix and "_test" postfix when mocking an remote interface

### ISSUE THREAD

**Issue by HotsauceLee** [vektra/mockery#56]
Hi there,

I'm using your tool to mock an interface from another package, and I want the file name contains "mock_" prefix and "_test" postfix to indicate its purpose. After digging into your [source code](https://github.com/vektra/mockery/blob/master/cmd/mockery/mockery.go#L190), it looks like the generated file cannot have those words in its name unless I use the "-inpkg" option:
```go
func filename(name string) string {
	if *fIP && *fTO {
		return "mock_" + name + "_test.go"
	} else if *fIP {
		return "mock_" + name + ".go"
	}
	return name + ".go"
}
```

Also looks like the generated struct name cannot have "Mock" in front of it too, unless I specify the -inpkg option:
```go
func (g *Generator) mockName() string {
	if g.ip {
		if ast.IsExported(g.iface.Name) {
			return "Mock" + g.iface.Name
		} else {
			first := true
			return "mock" + strings.Map(func(r rune) rune {
				if first {
					first = false
					return unicode.ToUpper(r)
				}
				return r
			}, g.iface.Name)
		}
	}

	return g.iface.Name
}
```

The reason I don't wanna use the -inpkg option and move the mock file back to my package manually  is because I'm doing this in a rake file task, which links to the "mother rakefile" in my workspace for easier dependency management:
```ruby
file "server/mock_librarian_test.go" => "../librarian/librarian.go" do |t|
    sh "mockery -output server/ -case underscore -dir ../librarian -name Librarian -testonly"
    # mockery could not generate file name with "mock" and "test" from a remote
    # interface, so change file name here manually.
    sh "mv server/librarian.go server/mock_librarian_test.go"
end

task :generate => ["server/mock_librarian_test.go", "server/mock_message_producer_test.go", "api_spec.json-bindata.go"]
```

I don't know if this is your business logic or not, but it is pretty common for me to mock some external dependencies during unit testing while keep the names of mock structs and file names informative. So are you guys considering changing the naming conventions in the future? Can I make a pull request on this?

Thanks!

**Comment by evanphx** [comment]
The naming convention of the files can be updated, but the convention of the types can't be changed without add an additional option to control that, since it would break backward compatibility.

Why do yo need Mock added to a type that is in the mocks package? Seems like writing `mock.MockPerson` is just repeating yourself.

Ditto with `_test.go`, if you only import the mocks package from your test, then you don't need it.

**Comment by HotsauceLee** [comment]
Yeah guess it makes more sense if I put mocks in the mock directory. The dir name explains everything. Thanks!
