### ISSUE TITLE
Bug: failed to get package from config

### ISSUE THREAD

**Issue by lruggieri** [vektra/mockery#561]
Description
-------------

Until version 2.20.0, a command like

`mockery --all --recursive --output "mock" --case "underscore" --keeptree --packageprefix "mock" --with-expecter`

produced the desired result: a mock directory with all interfaces mocked.

Since v.2.21.0 (latest on brew atm) the command produces:

`Error: failed to get package from config: failed to read file: : open : no such file or directory`

The reason is that the `packages` variables in Config gets automatically populated, even without specifying anything in the .mockery config file, therefore we end up [in this "alpha feature state"](https://github.com/vektra/mockery/blob/62dcb4b62266acbaa453feac1707ca6d9d2a01f9/cmd/mockery.go#L232) case.

Mockery Version
--------

2.21.0

Golang Version
--------------

1.20.1

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [x] brew
- [ ] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

1. run the command in the description with v2.20.0
2. run the same command with v2.21.0
3. point 2. will result in an error

### Expected Behavior

The 2 commands should be backward compatible.

### Actual Behavior

Version 2.21.1 throws an error, which is not expected.

**Comment by LandonTClipp** [comment]
Are you using 2.21.0 or 2.21.1? I attempted to fix this in 2.21.1.

**Comment by lruggieri** [comment]
I used v2.21.0, the latest available on brew till yesterday.
v2.21.1 seems to indeed fix the issue, and it seems to be available on brew since today.

Thank you ^^

**Comment by LandonTClipp** [comment]
Great, thanks for the report!
