### ISSUE TITLE
v2.21.4 gives error regarding --filename or --structname even though I am not using it

### ISSUE THREAD

**Issue by mohdaqib57** [vektra/mockery#572]
Description
-------------

I am getting this error `FTL Cannot specify --filename or --structname with regex in --name dry-run=false version=v2.21.4`.

However, I dont call for filename and structname since I first use mockery for few years.

This is the command that I execute `mockery --name='(.*)' --case=underscore --dir=src/lib/redis --output=src/lib/redis/mocks`.

The config file I use since v2.21.0 is as below
```
packages:
  github.com/vektra/mockery/v2/pkg:
    config:
      all: True
```

Mockery Version
--------
v2.21.4

Golang Version
--------------

1.19.1 

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [x] brew
- [ ] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

1. Run the mockery command as above `mockery --name='(.*)' --case=underscore --dir=src/lib/redis --output=src/lib/redis/mocks` (change directory for own test)
2. You will get the error

### Expected Behavior

No error

### Actual Behavior

get error `FTL Cannot specify --filename or --structname with regex in --name dry-run=false version=v2.21.4`.

**Comment by LandonTClipp** [comment]
Hi, so you are using `--name` which enters the code into the legacy behavior. The `packages` config should not be specified along with `--name`. What is happening to you is that the code is getting into a split-brain situation. I think I should make this more clear, so I will leave this open to make sure the code will fail under this scenario.
