### ISSUE TITLE
It there ways to make the type mockConstructorTestingTNewUserBiz to be MockConstructorTestingTNewUserBiz

### ISSUE THREAD

**Issue by Jinglever** [vektra/mockery#585]
PLEASE READ
-------------

DO NOT submit tickets without _first_ using the latest version of Golang, clearing your local golang package cache, and re-building mockery using the _latest_ Golang version and the _latest_ version of mockery. Please provide evidence this has been done in your issue. Failure to provide this evidence will likely result in your issue being closed.

Description
-------------

After I generate mocks file, I found that the struct Name like :
```
type mockConstructorTestingTNewUserBiz interface {
	mock.TestingT
	Cleanup(func())
}
```

the head char of  `mockConstructorTestingTNewUserBiz` is lowercase, and I can not use it in other package.
However, I use google/wire to inject dependency, something like:
```
func NewUserHandler(t mocks.MockConstructorTestingTNewUserBiz, rsrc *resource.Resource) (*httphandler.User, error) {
	panic(wire.Build(
		domain.MocksProviderSet,
		httphandler.ProviderSet,
	))
}
```

Mockery Version
--------

v2@v2.20.0

Golang Version
--------------

1.19

```
NOTE: Please upgrade to the latest golang version before submitting tickets!
```

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [ ] brew
- [x] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

1. go install github.com/vektra/mockery/v2@v2.20.0
2. add .mockery.yaml with content:
```
inpackage: False
testonly: False
with-expecter: True
keeptree: True
exported: True
```
3.  mark the interface like:
```
//go:generate mockery --name UserBiz
type UserBiz interface {
...
}
```
4. run: go generate
5. then file mocks/UserBiz.go generated

### Expected Behavior

hope that the content generated should be:
```
type MockConstructorTestingTNewUserBiz interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserBiz creates a new instance of UserBiz. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserBiz(t MockConstructorTestingTNewUserBiz) *UserBiz {
	mock := &UserBiz{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
```

### Actual Behavior

generated content like:
```
type mockConstructorTestingTNewUserBiz interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserBiz creates a new instance of UserBiz. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserBiz(t mockConstructorTestingTNewUserBiz) *UserBiz {
	mock := &UserBiz{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
```

**Comment by LandonTClipp** [comment]
I'm not sure there was ever really a good reason to have this unexported. If you want to submit a PR to make it exported, I don't think that'd be an issue.

**Comment by LandonTClipp** [comment]
In v2.30.1, the interface is no longer an explicit type. Instead it's inlined in the constructor's function signature.
