### ISSUE TITLE
Type aliases to internal packages should not be resolved

### ISSUE THREAD

**Issue by cornelk** [vektra/mockery#586]
Description
-------------

mockery will create imports of internal packages of imported external libraries:

```
// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	context "context"

	internal "go.temporal.io/sdk/internal"
```

Mockery Version
--------

v2.23.1

Golang Version
--------------

v1.20.2

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [ ] brew
- [x] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

```
import (
	"context"

	"go.temporal.io/sdk/client"
)

//go:generate mockery --name=TemporalClient --filename=temporal_client.go

type TemporalClient interface {
	ExecuteWorkflow(ctx context.Context, workflow string) (client.WorkflowRun, error)
}
```

the referenced type is: `WorkflowRun = internal.WorkflowRun`

### Expected Behavior

generated mock imports:

`client "go.temporal.io/sdk/client"`

### Actual Behavior

generated mock imports:

`internal "go.temporal.io/sdk/internal"`

which fails to compile: `use of internal package go.temporal.io/sdk/internal not allowed`

**Comment by LandonTClipp** [comment]
The golang AST parser does not retain information about type aliases. It resolves it to the underlying type. Thus it's impossible for us to resolve this in an automated way. @RangelReale implemented a feature here to get around that issue: https://vektra.github.io/mockery/features/#replace-types
