### ISSUE TITLE
Install broken: golang.org/x/tools/astutil has disappeared

### ISSUE THREAD

**Issue by neocortical** [vektra/mockery#6]
It looks like the golang.org/x/tools/astutil repo has been deleted. This breaks fresh installs of mockery. 

Repro: 
```
go get github.com/vektra/mockery
```

Expected behavior: Mockery is silently installed

Actual behavior: install fails with the following error: 
```
 package github.com/vektra/mockery
	imports code.google.com/p/go.tools/astutil
	imports code.google.com/p/go.tools/imports
	imports golang.org/x/tools/astutil
	imports golang.org/x/tools/astutil
	imports golang.org/x/tools/astutil: cannot find package "golang.org/x/tools/astutil" in any of:
	/usr/local/go/src/pkg/golang.org/x/tools/astutil (from $GOROOT)
	/Users/{username}/go/src/golang.org/x/tools/astutil (from $GOPATH)
```

Attempts to install astutil direct also fail and the golang.org and github locations for the package return 404s.

**Comment by evanphx** [comment]
mockery doesn't import astutils. Did you perhaps edit the code and add that import?

**Comment by neocortical** [comment]
I haven't modified the code. I did notice it's not directly imported; I
think it's a secondary dependency of a package that is. You should be able
to repro by doing a go get -u on mockery.

Typed on a potato.
