### ISSUE TITLE
protobuf comparison

### ISSUE THREAD

**Issue by newhook** [vektra/mockery#600]
I've been using mockery to mock out things that take protobuf structs.

Due to this issue https://github.com/stretchr/testify/issues/758 the whole process is pretty cumbersome. I end up having to do something similar to:

```
storer.EXPECT().Store(mock.Anything, mock.AnythingOfType("[]*sender.ActionRequestData")).
Run(func(ctx context.Context, s []*sender.ActionRequestData) {
	if diff := cmp.Diff(expectedStoreActionRequestData, s, protocmp.Transform()); diff != "" {
		t.Errorf("unexpected difference:\n%v", diff)
	}
}).Return(nil).Once()
```

vs the much more ergonomic:
```
storer.EXPECT().Store(mock.Anything, expectedStoreActionRequestData).Return(nil).Once()
```

 It would be great if there was some flexibility in defining how expected values are compared for equality. For protobuf, we could use `proto.Equal` or possibly

```
if diff := cmp.Diff(expected, have, protocmp.Transform()); diff != "" {
	t.Errorf("unexpected difference:\n%v", diff)
}
```

**Comment by LandonTClipp** [comment]
This isn't really something we could reasonably implement in mockery. Mockery uses testify's argument matching logic to get return values, so we can't really change how that works unless we basically implement our own mocking backend.

**Comment by newhook** [comment]
I believe right now the code uses `assert.ObjectsAreEqual` to compare the expected value with the provided value. Couldn't instead the code have:

`var ObjectsAreEqual = assert.ObjectAreEqual`

and then allow me to define my own?

**Comment by LandonTClipp** [comment]
The only place the code uses the `assert` package is in the tests itself. The mock objects only register expectations directly with the `testify/mock.Mock`, we don't do any fancy argument matching beyond that.

**Comment by newhook** [comment]
Ah, thanks. I didn't realize that the expectations were checked by testify, not mockery.

I agree it doesn't make sense to implement another version of testify/mock.

That said this is a pain :)

**Comment by LandonTClipp** [comment]
I think what you're asking is a reasonable thing. It would be cool to have some sort of "matching function" that testify uses to match arguments. The function itself could just return a hash of the values you find important and testify would just check for matching hashes. But yeah I have no control over testify at the moment.

**Comment by pd93** [comment]
@LandonTClipp I ran into this issue today when trying to migrate some protobuf tests from gomock to mockery v3. With the new version on the horizon, is this something that could be revisited?

Note that since this issue was last discussed, stretchr/testify has added a [`EqualExportedValues`](https://pkg.go.dev/github.com/stretchr/testify/assert#EqualExportedValues) function, so maybe a new backend isn't even needed. See https://github.com/stretchr/testify/issues/758.
