### ISSUE TITLE
filename is not expanded

### ISSUE THREAD

**Issue by gustavosbarreto** [vektra/mockery#603]
Description
-------------

The filename variable from `.mockery.yaml` is not expanded.

Mockery Version
--------

v2.25.1

Golang Version
--------------

1.20

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [ ] brew
- [x] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

1. Create a `.mockery.yaml` file with following content:

```
quiet: False
keeptree: True
disable-version-string: True
with-expecter: True
mockname: "{{.InterfaceName}}"
filename: "{{.MockName}}.go"
outpkg: mocks
```

2. Create a dummy interface:

```go
//go:generate mockery --name Dummy
type Dummy interface {
        Nothing()
}
```

3. Run `go generate`

### Expected Behavior

Is expected a `dummy.go`  file inside `mocks` directory.

### Actual Behavior

The `mocks` directory contents:

```
{{.MockName}}.go
```

**Comment by LandonTClipp** [comment]
Hi, templated variables are not available when using non-`packages` config. I'll update the docs to make this clearer.

**Comment by tommymcguiver** [comment]
You might want to update your default config in the repository .
