### ISSUE TITLE
Outputter.Generate() fails to truncate the file

### ISSUE THREAD

**Issue by kgadams** [vektra/mockery#604]
PLEASE READ
-------------

DO NOT submit tickets without _first_ using the latest version of Golang, clearing your local golang package cache, and re-building mockery using the _latest_ Golang version and the _latest_ version of mockery. Please provide evidence this has been done in your issue. Failure to provide this evidence will likely result in your issue being closed.

Description
-------------

`pkg/outputter.go:291` needs to include flag `os.O_TRUNC`. If the previous version of the file was bigger, I get a bunch of junk at the end.

Mockery Version
--------

v2.25.1

Golang Version
--------------

Should be independent of the golang version (but I am using 1.20.3)

```
NOTE: Please upgrade to the latest golang version before submitting tickets!
```

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [ ] brew
- [x] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

1. [First Step] Generate a mock
2. [Second Step] Append some junk to the file
3. [etc] Regenerate the mock.

### Expected Behavior

I expect the junk in the file to be gone

### Actual Behavior

The junk is still there

**Comment by LandonTClipp** [comment]
Aha yes, I'll get that fixed. Thanks for the report.

**Comment by kgadams** [comment]
Thanks a lot for the quick fix! Very responsive :-)
