### ISSUE TITLE
Package config with recursive option on folder with only sub-folders: index out of range error

### ISSUE THREAD

**Issue by a-pedini** [vektra/mockery#611]
PLEASE READ
-------------

DO NOT submit tickets without _first_ using the latest version of Golang, clearing your local golang package cache, and re-building mockery using the _latest_ Golang version and the _latest_ version of mockery. Please provide evidence this has been done in your issue. Failure to provide this evidence will likely result in your issue being closed.

Description
-------------

I have this configuration:
```
output: ./mocks/pkg
keeptree: true
case: underscore
packages:
  github.com/a-pedini/my-service/pkg: // this is just a dummy name as the repo is private
    config:
      all: true
      recursive: true
      with-expecter: true
```
and I don't have any files directly in the /pkg folders, just subfolders with sub-packages.

When I try to run it with this config I get:
```
docker run --rm -v "/Users/a-pedini/IdeaProjects/my-service":/src -v "/Users/a-pedini/.gvm/pkgsets/go1.20.3/global:/go" -v ":/tmp/.cache" -w /src vektra/mockery:v2.25.0 --config ./.mockery_test.yaml --log-level debug --dry-run
24 Apr 23 23:40 UTC INF Starting mockery dry-run=true version=v2.25.0
24 Apr 23 23:40 UTC INF Using config: ./.mockery_test.yaml dry-run=true version=v2.25.0
24 Apr 23 23:40 UTC DBG package cache is nil dry-run=true version=v2.25.0
24 Apr 23 23:40 UTC DBG discovering sub-packages dry-run=true package-name=github.com/a-pedini/my-service/pkg version=v2.25.0
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/vektra/mockery/v2/pkg/config.(*Config).subPackages(0xc0000a0a80?, {0xa502e0?, 0xc0001493b0?}, {0xc0000eca40, 0x20}, 0xc0000ef600?)
        /home/runner/work/mockery/mockery/pkg/config/config.go:441 +0x826
```
In order to make it work I have to create an empty go file in the /pkg level... I'm guessing that's because without this file, the folder pkg is not a real package? as there was no file with the package pkg header...

would it be possible to consider a folder, that I guess is not technically a package, as the starting point for the recursion? with the dummy file this works well and it is way faster than before, so I think we can also live with that but just checking :P

Mockery Version
--------

v2.25.0 via docker

Golang Version
--------------

1.20.3

```
NOTE: Please upgrade to the latest golang version before submitting tickets!
```

Installation Method
-------------------

- [ ] Binary Distribution
- [x] Docker
- [ ] brew
- [ ] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

1. Create a ./pkg folder
2. Add a subfolder inside ./pkg and add an interface to mock inside this subfolder
3. run mockery to create the mock

### Expected Behavior

Creates the mock in the /mocks/pkg/subfolder directory

### Actual Behavior

Index out of bounds error

**Comment by LandonTClipp** [comment]
I plan on fixing this now, it's a behavior I think we should have (that is, if someone specifies a path, always consider it to be a "package").

**Comment by LandonTClipp** [comment]
This is turning out to be more difficult than I thought. The go package parser doesn't provide any information on where the package is stored on-disk if there are no go files (presumably because there is nothing to download). Even placing `go.mod` in the empty `./pkg` dir is not enough for it to provide module information, there _has_ to be a file.

I think the solution will have to be to clearly document this case in mockery. The good thing is that this can be clearly logged because it happens when the search depth is 0 and there are no go files found.
