### ISSUE TITLE
Debug message: Config File \".mockery\" Not Found in...

### ISSUE THREAD

**Issue by ob1dev** [vektra/mockery#613]
Description
-------------

The issue related to the following thread https://pullanswer.com/questions/mockery-not-running-on-version-v2-21-0-failed-to-read-in-config#, where running mockery still prints a debug statement `Config File \".mockery\" Not Found in...`

Mockery Version
--------

`2.26.1`

Golang Version
--------------

`1.20.3`

Installation Method
-------------------

- [ ] Binary Distribution
- [x] Docker
- [ ] brew
- [ ] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

1. `docker run -t --entrypoint /bin/sh vektra/mockery:latest -c mockery --name=SomeInterface`

### Expected Behavior

Prints out only info statement:
```
26 Apr 23 21:01 UTC DBG failed to read in config error="Config File \".mockery\" Not Found in \"[/go / /root]\"" version=v2.26.1
26 Apr 23 21:01 UTC INF couldn't read any config file version=v2.26.1
26 Apr 23 21:01 UTC INF Starting mockery dry-run=false version=v2.26.1
26 Apr 23 21:01 UTC INF Using config:  dry-run=false version=v2.26.1
26 Apr 23 21:01 UTC FTL Use --name to specify the name of the interface or --all for all interfaces found dry-run=false version=v2.26.1
```

### Actual Behavior

Prints out only info statement:

``` 
26 Apr 23 21:01 UTC INF couldn't read any config file version=v2.26.1
26 Apr 23 21:01 UTC INF Starting mockery dry-run=false version=v2.26.1
26 Apr 23 21:01 UTC INF Using config:  dry-run=false version=v2.26.1
26 Apr 23 21:01 UTC FTL Use --name to specify the name of the interface or --all for all interfaces found dry-run=false version=v2.26.1
```

**Comment by neverbeenthisweeb** [comment]
Hi @LandonTClipp , I am interested to work on this issue.
