### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by matthiasgubler** [vektra/mockery#614]
Description
-------------
When there is no config file present in the current workspace, the user gets to see this debug info:
```
DBG failed to read in config error="Config File \".mockery\" Not Found in \"[/mypaths/proj /mypaths ... /]\"" version=v2.26.1
```

Creating the file mentioned in the message doesn't help, as in reality, it is searching for a `.mockery.yaml` file.

Mockery Version
--------
v2.26.1

Golang Version
--------------
1.20.3

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [X] brew
- [ ] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------
- Run `$ mockery` in a project without a `.mockery.yaml` or `.mockery` file in it.
- Create a `.mockery` file and rerun and get to see the same error

### Expected Behavior
The output should be:
```
DBG failed to read in config error="Config File \".mockery.yaml\" Not Found in \"[/mypaths/proj /mypaths ... /]\"" version=v2.26.1
```

### Actual Behavior
The output is:
```
DBG failed to read in config error="Config File \".mockery\" Not Found in \"[/mypaths/proj /mypaths ... /]\"" version=v2.26.1
```

**Comment by LandonTClipp** [comment]
This is just a bad error message, if you want to submit a PR to fix it that'd be helpful.

The annoying thing is that these messages are logged before the config is actually parsed, so it's hard to set it to the appropriate log level. Sorry about the noise!

**Comment by max-melentyev** [comment]
Is it required to have a config?
This message, even being DBG, is also printed when running with `--quiet`.

**Comment by LandonTClipp** [comment]
It's not required to have a config. I agree the log is confusing, we should just remove that message.

**Comment by LandonTClipp** [comment]
This line has been removed.
