### ISSUE TITLE
Rip out all usage of `github.com/pkg/errors`

### ISSUE THREAD

**Issue by LandonTClipp** [vektra/mockery#616]
Description
-------------

This package has been deprecated and archived, we should not use it anymore. Replace all instances of `pkg/errors` with the golang-standard packages. Use the `%w` wrapping directive from `fmt.Errorf` to add contextual information to errors.

https://github.com/pkg/errors/issues/245

**Comment by amirkhaki** [comment]
What about printing stacktrace?

**Comment by LandonTClipp** [comment]
IMO we shouldn't use things that are archived. I was considering just forking the project but I want to be careful with committing myself to too many things. If someone picks it back up then we should continue to use it... the standard errors library is inferior to pkgs/errors.

**Comment by scraymondjr** [comment]
@LandonTClipp just curious, what is the harm of using an archived project, especially with Go's backwards compatibility guarantees?

**Comment by LandonTClipp** [comment]
@scraymondjr it's the lack of maintenance support if something were to become non-functioning. It's true anyway that the standard errors package provides the error wrapping semantics that pkg/errors gives us. The stack tracing though is still not something the std lib provides. 

I'll defer this for a bit. I did fork `pkg/errors` to my own org at https://github.com/chigopher/errors, but I might want to rip out the wrapping logic and instead preserve the stack tracing.

**Comment by wolfeidau** [comment]
Not sure if you had seen it but I have been using https://github.com/pingcap/errors as they have done quite a bit work in their fork to update / upgrade to support their own projects.

I use this version for some of my projects.

**Comment by cszczepaniak** [comment]
Two cents from a user: it would be nice to not take on a transitive dependency on a public archive _especially_ for something that is mostly subsumed now by the Go standard library. I don't love using things like `Is` and `As` from a public archive when they exist in the stdlib now.

As for stack traces, is there a reason not to just use `debug.Stack` and a thin error wrapper like so?

```go
type stackErr struct {
    cause error
    stack []byte
}

func (e stackErr) Error() string {
    return e.cause.Error()
}

func (e stackErr) Unwrap() {
    return e.cause
}
```
