### ISSUE TITLE
Mockery v2 with `--inpackage` generates import path that conflicts with type name, ignoring aliased import in source file

### ISSUE THREAD

**Issue by geekofalltrades** [vektra/mockery#621]
Description
-------------

I have the following code:

```go
package myclient

import (
	awsclient "github.com/aws/aws-sdk-go/aws/client"
	"github.com/aws/aws-sdk-go/service/ecr"
	"github.com/aws/aws-sdk-go/service/ecr/ecriface"
)

// ecrAPIExtension is an extension of ecriface.ECRAPI that adds getter methods
// for useful exported attributes of ECRAPI implementations.
type ecrAPIExtension interface {
	ecriface.ECRAPI

	GetClient() *awsclient.Client
}

// ecrClient is an implementation of ecrAPIWithClient for production use.
type ecrClient struct {
	*ecr.ECR
}

func (e *ecrClient) GetClient() *awsclient.Client {
	return e.Client
}

// client implements containerregistry.Client to manage ECR.
type client struct {
	ecr ecrAPIExtension
}
```

It defines a `client` type that's implementing an interface defined elsewhere. I am also importing `awsclient "github.com/aws/aws-sdk-go/aws/client"`. It's being aliased to `awsclient` to avoid a name clash with the `client` type.

I run the following mockery command to generate a mock of the `ecrAPIExtension` type:

```
mockery --dir path/to/mypackage/ --all --log-level debug --inpackage
```

The resulting mock has all of the methods of the embedded [`ecriface.ECRAPI`](https://docs.aws.amazon.com/sdk-for-go/api/service/ecr/ecriface/#ECRAPI), so it's very large, and I won't paste the whole file here, but here's the relevant portion:

```go
// Code generated by mockery v2.26.1. DO NOT EDIT.

package containerregistry

import (
	context "context"

	client "github.com/aws/aws-sdk-go/aws/client"

	ecr "github.com/aws/aws-sdk-go/service/ecr"

	mock "github.com/stretchr/testify/mock"

	request "github.com/aws/aws-sdk-go/aws/request"
)

// mockEcrAPIExtension is an autogenerated mock type for the ecrAPIExtension type
type mockEcrAPIExtension struct {
	mock.Mock
}

# etc.
```

It has ignored the `awclient` alias I imported `"github.com/aws/aws-sdk-go/aws/client"` with and is importing it as `client`, instead. This conflicts with my `client` type in the same package.

Mockery Version
--------

v2.26.1

Golang Version
--------------

go version go1.20.4 linux/amd64

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [ ] brew
- [x] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

See Description.

### Expected Behavior

mockery should preserve package import name aliases that avoid name collisions.

### Actual Behavior

mockery ignored package import name aliases, causing a name collision.

**Comment by LandonTClipp** [comment]
This is a shortcoming of the go AST. Please use this feature to get around it: https://vektra.github.io/mockery/features/#replace-types

**Comment by LandonTClipp** [comment]
Actually, I'm doubting if a replace-types would fix this. Please give that a try, if it's not the right solution we can think of something else.

**Comment by geekofalltrades** [comment]
Adding `--replace-type github.com/aws/aws-sdk-go/aws/client=awsclient:github.com/aws/aws-sdk-go/aws/client` did the trick, thanks.

**Comment by LandonTClipp** [comment]
Excellent. If there's an opportunity to have mockery act more intelligently here, I'm open to opinions.
