### ISSUE TITLE
Recursion is broken

### ISSUE THREAD

**Issue by ryanwalls** [vektra/mockery#66]
Just pulled latest this morning (2a87a1b8fa9bcbeeb0d9c952454e026667a7bc75) and recursion is broken despite #61.

**Comment by evanphx** [comment]
@ryanwalls Can you show the command line you're using where it doesn't work? A quick test here shows it working.

**Comment by ryanwalls** [comment]
@evanphx 

```
$GOPATH/bin/mockery -name Simulation -recursive
```

Where the `Simulation` interface is in a subfolder.

**Comment by evanphx** [comment]
I'll need more info because I'm not able to replicate the issue. Here is what I tried that worked fine:

```shell
veritas :: mockery/tmp> cat b/a/blah.go 
package a

type NotifyEvent interface {
	Get() error
}
veritas :: mockery/tmp>             
veritas :: mockery/tmp> find .
.
./b
./b/a
./b/a/blah.go
veritas :: mockery/tmp> mockery -name=NotifyEvent -recursive
Generating mock for: NotifyEvent
```

**Comment by ryanwalls** [comment]
I'm at a loss myself.  Your example works for me.  But in a much larger project, when I use the -recursive flag, it pauses for a few seconds and then says `Unable to find <Some interface> in any go files under this path`

**Comment by evanphx** [comment]
Ok. How many directories deep are we talking?

**Comment by ryanwalls** [comment]
Figured out the cause.  If I remove my `vendor` folder, `-recursive` can find the interface.  With the `vendor` folder in there it cannot.

**Comment by ryanwalls** [comment]
Well... that's not the cause... but it is another clue.

**Comment by ryanwalls** [comment]
My vendor folder has about 8000 files in it.

**Comment by ryanwalls** [comment]
And fyi, previous versions before the latest batch of changes didn't experience this issue.

**Comment by gaffo** [comment]
So I'm seeing similar to this still with the verbose feature turned on. @ryanwalls can you try pulling in my verbosity patch or wait till @evanphx does. See if you are getting parse failures for the files you expect to have the interfaces that aren't recursing. -verbose to mockery turns it on. I think this is still what I'm getting on larger projects. It's complaining about some import which is causing parse errors which is causing the file to be skipped. I'm trying to gather more data in another place.

**Comment by evanphx** [comment]
Please re-open if this is still an issue.

**Comment by lucianomda** [comment]
same issue occurs for me in different relative small projects. When i use -recursive with -name=XXX flags or -all flag running mockery command from project root folder then mockery keeps working and never ends(waited around 15 minutes).
If I use -dir flag with a project subfolder as value then it works, e.g. 
- `mockery -all -dir=subfolder` 
- `mockery -name=AnInterface -recursive -dir=subfolder0`

**Comment by eclipse1985** [comment]
Same issue here
