### ISSUE TITLE
Formatting on configuration.md is broken

### ISSUE THREAD

**Issue by echarrod** [vektra/mockery#663]
Description
-------------
Formatting at https://github.com/vektra/mockery/blob/master/docs/configuration.md is broken, I believe this will be because a code block has not been closed

![image](https://github.com/vektra/mockery/assets/1381991/7e87ccc4-024d-4ac3-b38c-c3ab7941f3e7)

**Comment by LandonTClipp** [comment]
This isn't broken, the docs are rendered via mkdocs so you're not supposed to read these markdown files in GitHub directly.
