### ISSUE TITLE
map[string]func(string) string unhandled by new version of mockery

### ISSUE THREAD

**Issue by IvanMalison** [vektra/mockery#67]
``` go
type Issue interface {
	Broken(unhandled map[string]func(string) string)
}
```
gives

Unable to generated mock for 'Issue': un-namable type: &types.Map{key:(*types.Basic)(0x5984c0), elem:(*types.Signature)(0xc8202ee2a0)} (*types.Map)

**Comment by evanphx** [comment]
Sorry about that! All fixed.
