### ISSUE TITLE
Error: no required module provides package (EDIT: CAN CLOSE BUT PLEASE LOOK AT IT BECAUSE IT MIGHT HELP OTHERS)

### ISSUE THREAD

**Issue by quirell** [vektra/mockery#677]
Description
-------------

I basically followed the docs and I'm getting an error right of the bat.
I'm executing mockery from the backend directory where the mockery config resides and the repository belongs to an organization and is only accessible by vpn if that changes anything. 
Am I doing something wrong ? 
Mockery works when I delete the configuration file.

```
├── frontend
├── backend
│   ├── go.mod
│   ├── .mockery.yml
│   ├── go.sum
│   ├── internal
│   │   ├── domain
│   │   │   └── user

```

Mockery config:
```
packages:
  github.com/my-org/fund-property-management/internal/domain/user:
    config:
      all: True
```

Mockery Version
--------

INF Starting mockery dry-run=false version=v2.32.0

Golang Version
--------------

go version go1.20.5 darwin/arm64

```
NOTE: Please upgrade to the latest golang version before submitting tickets!
```

Installation Method
-------------------

- [ ] Binary Distribution
- [x] Docker
- [x] brew
- [x] go install
- [ ] Other: [specify]
go generate + library in tools.go

Baiscally all possible installation versions

Steps to Reproduce
------------------

execute `mockery`

### Expected Behavior

Mocks should generate successfully 

### Actual Behavior

Get an error
```
ERR encountered error when loading package error="-: no required module provides package github.com/my-org/fund-property-management/internal/domain/user; to add it:\n\tgo get github.com/my-org/fund-property-management/internal/domain/user" dry-run=false version=v2.32.0

```

**Comment by LandonTClipp** [comment]
So if you are able to `go get github.com/whatever`, mockery should also work. It uses the same backend that `go get` does to fetch packages so this isn't necessarily a mockery problem.

If you could provide a reproducer that helps elaborate what you did, that would be useful and maybe we can add it to the docs.
