### ISSUE TITLE
Skip context.Context

### ISSUE THREAD

**Issue by mcdoker18** [vektra/mockery#678]
Description
-------------

I have a lot of interfaces that accepts `context.Context`  as the first parameter of a method.
But I have never check this argument. But anyway I should always pass them to the mock method.

```go
mock.EXPECT().GetUser(mock.Anything, 111).Return(user, nil).Once()
```

I want some parameter in the config that allow the mockery generates mocks without context at all. 

```go
mock.EXPECT().GetUser(111).Return(user, nil).Once()
```

But internally the mock will pass `mock.AnythingOfType(context.Context)` to the `mock.On(...)` method.

**Comment by LandonTClipp** [comment]
I'm not convinced this is really something that's needed at this point. I understand the convenience this would give but for the sake of preventing bloat, I don't want to implement this at the moment. If lots of people want something like this, I can consider it.
