### ISSUE TITLE
Wrong version tagged (v2.23.4 instead of v2.32.4)

### ISSUE THREAD

**Issue by sruehl** [vektra/mockery#687]
@LandonTClipp I think you tagged the wrong version by accident (v2.23.4 instead of v2.32.4)?
Could be a backport fix on purpose but I suspect a typo.

![image](https://github.com/vektra/mockery/assets/1769155/324bff4e-f419-41f6-bca6-b119afd316cb)

**Comment by LandonTClipp** [comment]
Blah, no this is a mistake. Sorry D:

**Comment by LandonTClipp** [comment]
I fixed this, sorry for the delayed update, been remote for the last few days.
