### ISSUE TITLE
Mock generation fails if code contains new Go 1.21.0 built-in function "min"

### ISSUE THREAD

**Issue by maruu** [vektra/mockery#723]
Description
-------------

Mock generation fails if code contains new Go 1.21.0 built-in function "min".

Mockery Version
--------

v2.35.3

Golang Version
--------------

/workspace# go version
go version go1.21.3 linux/amd64

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [ ] brew
- [ ] go install
- [x] Other: Devcontainer feature (which uses pre-built binary from git release (https://github.com/brokeyourbike/devcontainer-features/blob/main/src/mockery-go/install.sh#L47C19-L47C78))

Steps to Reproduce
------------------

1. Add new Go1.21.0 in-built function "min" to any code file in the repository where mockery is executed
2. Run mockery using "mockery" command
3. Observe failure in mockery log output: `"ERR Error parsing file error="/workspace/backend/device.go:182:18: undefined: min" dry-run=false version=v2.35.3"`

Output (discarded some sensitive information):

> 11 Oct 23 08:16 UTC INF Starting mockery dry-run=false version=v2.35.3
> 11 Oct 23 08:16 UTC INF Using config: /workspace/.mockery.yaml dry-run=false version=v2.35.3
> 11 Oct 23 08:16 UTC WRN DEPRECATION: use of the packages config will be the only way to generate mocks in v3. Please migrate your config to use the packages feature. dry-run=false migration=https://vektra.github.io/mockery/v2.35/migrating_to_packages/ url=https://vektra.github.io/mockery/v2.35/features/#packages-configuration version=v2.35.3
> 11 Oct 23 08:16 UTC INF Walking dry-run=false version=v2.35.3
> 11 Oct 23 08:16 UTC ERR Error parsing file error="/workspace/backend/device.go:182:18: undefined: min" dry-run=false version=v2.35.3

.mockery.yaml file:

> with-expecter: true
> all: true
> inpackage: true

### Expected Behavior

Mocks are generated successfully

### Actual Behavior

Mocks are not generated and mockery fails with message `"ERR Error parsing file error="/workspace/backend/device.go:182:18: undefined: min" dry-run=false version=v2.35.3"`

If I comment out the line using the built-in "min" function, the mock generation works just fine.

Code example using the built-in "min" function: https://go.dev/play/p/QrBZeI4b6Wr

**Comment by LandonTClipp** [comment]
I think we just need a new build using the latest Go version. Let me try.

**Comment by LandonTClipp** [comment]
v2.35.4 is going to be built with Go 1.21, try that once it is released.

**Comment by maruu** [comment]
I verified that it works with the new release. Thank you for the quick fix!

Shall I close the ticket?

**Comment by LandonTClipp** [comment]
Excellent, I'll close the ticket.
