### ISSUE TITLE
Recursive: true appears to no longer work with v2.37

### ISSUE THREAD

**Issue by nbam-e** [vektra/mockery#733]
Description
-------------

Prior to v2.37 the following .mockery.yaml file would create mocks for all interfaces  (where "reproduction" is the module name)
```
packages:
  reproduction:
    config:
      all: true
      recursive: true
```

After updating to v2.37, no mocks are generated.

Mockery Version
--------

v2.37

Golang Version
--------------

The one from the latest official mockery docker image (1.21.3).
(The same issue also occurs with the binary from the github release or mockery binary built from source using go 1.21.4)

Installation Method
-------------------

- [x] Binary Distribution
- [x] Docker
- [ ] brew
- [x] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

Minimal reproduction: [repro.zip](https://github.com/vektra/mockery/files/13362245/repro.zip)

1. unzip reproduction 
2. cd repro
3. run run2.37.sh

### Expected Behavior

Mock for interface SomeType in somepkg/someinterface.go should be generated

### Actual Behavior

No mocks are generated  (when using run2.36.sh, the mocks are generated as expected)

**Comment by LandonTClipp** [comment]
Interesting, I'll have to see why the tests didn't catch this. I'll revert the change for now and will investigate what went wrong.

**Comment by LandonTClipp** [comment]
I've reverted the change in 2.37.1. Sorry for the disruption, we'll figure out why this feature broke and hopefully re-release it once we iron out the regression.
