### ISSUE TITLE
Errors are swallowed up, making debugging difficult.

### ISSUE THREAD

**Issue by abourget** [vektra/mockery#74]
in `doWalk` in `walker.go`, I tweaked lines 57...:

```go
		err = p.Parse(path)
		fmt.Println("Parse", path)
		if err != nil {
			fmt.Println("Error:", err)
			continue
		}
```

And running it I now read:

```
Parse store.go
Error: open .#main.go: no such file or directory
```

otherwise, it would say nothing, except it didn't find it..

What would be the best way to resurface errors ?

**Comment by abourget** [comment]
Also, with the current revision, the generated mock files are empty ! Have you seen such a behavior ?

**Comment by abourget** [comment]
in `ouputter.go`, line `53`, there is a `defer f.Close()` .. how can the caller write to a closed file ?

am I missing something ?

**Comment by IvanMalison** [comment]
Yeah this makes development much more difficult.

**Comment by evanphx** [comment]
#75 should have fixed this.
