### ISSUE TITLE
pathlib values undefined

### ISSUE THREAD

**Issue by davidsbond** [vektra/mockery#743]
Description
-------------

While trying to install mockery I am getting the following error:

```
Error: ../../../go/pkg/mod/github.com/vektra/mockery/v2@v2.39.1/pkg/config/config.go:561:33: undefined: pathlib.AlgorithmPreOrderDepthFirst
Error: ../../../go/pkg/mod/github.com/vektra/mockery/v2@v2.39.1/pkg/config/config.go:596:20: undefined: pathlib.ErrWalkSkipSubtree
```

Mockery Version
--------

 v2.39.1

Golang Version
--------------

1.21

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [ ] brew
- [x] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

1. Try to install mockery v2.39.1 via `go install github.com/vektra/mockery/v2`
2. See error

### Expected Behavior

The binary is built & installed

### Actual Behavior

Compilation error as shown above.

**Comment by davidsbond** [comment]
Somehow my go.mod ended up with the incorrect version of pathlib as a transient dependency. After I tweaked that to match the version mockery uses the installation works again

**Comment by LandonTClipp** [comment]
Sounds good, feel free to post other issues if you find them.

**Comment by percivalalb** [comment]
I've also just had this happen to me, it seems that the `retract` section of the `go.mod` file isn't always respected https://github.com/chigopher/pathlib/blob/master/go.mod#L20

For others, I forced the version to match the s[ame version that mockary](https://github.com/vektra/mockery/blob/master/go.mod#L7) also uses.
```
$ go get github.com/chigopher/pathlib@v0.19.1
go: downgraded github.com/chigopher/pathlib v1.0.0 => v0.19.1
```
