### ISSUE TITLE
mockname with problem

### ISSUE THREAD

**Issue by fmirandapagarme** [vektra/mockery#799]
Description
-------------

When I generate the mock file for this interface:

type AckHandler interface {
}

it creates the new instance name like this:

func NewMockackHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockackHandler {

But I would like it to generate it as NewMockAckHandler (with the 'A' in 'Ack' capitalized).

Below is my .mockery.yaml:

mock-build-tags: 'mock'
exclude:
  - vendor
packages:
  github.com/loren/ipsum:
    config:
      recursive: true
      all: true
      inpackage: true
      dir: "{{.InterfaceDirRelative}}"
      mockname: "Mock{{.InterfaceName | camelcase }}"
      filename: "mock_{{.InterfaceName}}.go"
      outpkg: "{{.PackageName}}"

The issue seems to be with mockname. However, according to the documentation [here](https://vektra.github.io/mockery/latest/configuration/#variables), it appears to be configured correctly.

Mockery Version
--------

[v2.43.2]

Go Version
--------------

[1.22.4 linux/amd64]

NOTE: Please upgrade to the latest golang version before submitting tickets!

Installation Method
-------------------

- [x] Binary Distribution
- [ ] Docker
- [ ] brew
- [] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

1. Define the interface AckHandler.
2. Run mockery to generate the mock file.
3. Check the generated method name.

### Expected Behavior

The generated method name should be NewMockAckHandler.

### Actual Behavior

The generated method name is NewMockackHandler.

**Comment by LandonTClipp** [comment]
This works:

```
"Mock{{.InterfaceName | firstupper }}"
```

Take a look at the functions available: https://vektra.github.io/mockery/latest/configuration/#functions

You can see why your example does not work if you look at the docs for the function: https://pkg.go.dev/github.com/huandu/xstrings#ToCamelCase
