### ISSUE TITLE
-inpkg produces wrong qualified symbols in non-main package

### ISSUE THREAD

**Issue by atombender** [vektra/mockery#80]
If I use `-inpkg` and my package name is `things`, and my interface is `Thing`, then it generates a file in the correct package, but referencing the original interface as `things.Thing`:

```
package things

import "github.com/stretchr/testify/mock"

// MockThing is an autogenerated mock type for the Thing type
type MockThing struct {
	mock.Mock
}

// Get provides a mock function with given fields: uid, options
func (_m *Client) Get(uid string, options things.GetOptions) (*things.Item, error) {
	ret := _m.Called(uid, options)
}
[...]
```

But Go doesn't allow you to qualify symbols in a package with its own package name (`things.Item`), and running this through `goimports` will of course cause it to import itself. 

The correct behaviour is to not prefix the symbols that are in the same package.

**Comment by maciejmrowiec** [comment]
+1

Having same issue

**Comment by IvanMalison** [comment]
@atombender you may want to check to see if my pull request #93 has resolved this issue. or if joshk0s pr did so.
