### ISSUE TITLE
Current release of mockery v2.45 image is incompatible with Go v1.23 when running on docker

### ISSUE THREAD

**Issue by khaifazil** [vektra/mockery#813]
Description
-------------

Current release of mockery v2.45 image is not compatible with Go v1.23

<img width="1147" alt="image" src="https://github.com/user-attachments/assets/ede38a62-dd33-4e8c-a2ad-48dfee267336">

`ERR Error parsing file error="err: exit status 1: stderr: go: go.mod requires go >= 1.23 (running go 1.22.6; GOTOOLCHAIN=local)\n" dry-run=false version=v2.45.0`

Mockery Version
--------

Mockery v2.45.0

Go Version
--------------

Go v1.23 is currently used in the application's go.mod

Installation Method
-------------------

- [ ] Binary Distribution
- [x] Docker
- [ ] brew
- [ ] go install
- [ ] Other: [specify]

Steps to Reproduce
------------------

1. Setup application with Go v1.23
2. Setup docker compose file with service using mockery image v2.45.0
3. Generate mocks

### Expected Behavior

Expected: No error returned and mocks generated

### Actual Behavior

Actual: `ERR Error parsing file error="err: exit status 1: stderr: go: go.mod requires go >= 1.23 (running go 1.22.6; GOTOOLCHAIN=local)\n" dry-run=false version=v2.45.0`

**Comment by abhinavnair** [comment]
Hi @LandonTClipp , would it be possible to release a new version of Mockery to Dockerhub for this change in the next 2-3 days? Currently we are unable to use this fix until there is a new version release. Appreciate the help @khaifazil @LandonTClipp 🙂
