### ISSUE TITLE
Mockery v2.45.1 release

### ISSUE THREAD

**Issue by khaifazil** [vektra/mockery#816]
Description
-------------

Hi @LandonTClipp is it possible to do a release of mockery with this PR: https://github.com/vektra/mockery/pull/814 included?

**Comment by abhinavnair** [comment]
Hi @LandonTClipp we are eagerly waiting for this as well. Appreciate the help @khaifazil @LandonTClipp 🙂

**Comment by tattwei46** [comment]
Hi @LandonTClipp pls help with the release 🙏🏻

**Comment by infklinger** [comment]
We are waiting as well

**Comment by LandonTClipp** [comment]
For sure, I will do a release today!

**Comment by xenodus** [comment]
Same here and thanks!

**Comment by LandonTClipp** [comment]
https://github.com/vektra/mockery/releases/tag/v2.45.1 done
