### ISSUE TITLE
Embedded interfaces aren't expanded

### ISSUE THREAD

**Issue by atombender** [vektra/mockery#82]
For example:

```go
type A interface {
  MethodInA()
}
type B interface {
  A
  MethodInB()
}
```

If you run Mockery on `B`, it mocks `MethodInB` but not `MethodInA`.

**Comment by thegrandpoobah** [comment]
Isn't this the same as #18?

**Comment by atombender** [comment]
@thegrandpoobah Yes, and it seems it was fixed recently. I'm on an older version because of the several ugly bugs that were caused by recent releases. Thanks.

**Comment by thegrandpoobah** [comment]
Yeah, I really wish mockery was on gopkg or something so that I wouldn't just pull down random snapshots of the code.

**Comment by atombender** [comment]
We use Glide and pin it to a specific commit. But currently Mockery apparently needs to be installed globally, which does screw that up.
