### ISSUE TITLE
"go:generate" requires sh to work?

### ISSUE THREAD

**Issue by atombender** [vektra/mockery#83]
This works:

```
//go:generate sh -c "mockery -name='Thing'"
```

But this:

```
//go:generate mockery -name='Thing'
```

fails:

```
$ go generate ./...
Unable to find Thing' in any go files under this path
event/eventbus/thing.go:10: running "mockery": exit status 1
```

I've confirmed that the current working directory is correct.

**Comment by xeger** [comment]
This seems like a non-error to me; without a shell process to parse your single quotes, they will be passed directly to the mockery CLI. You're asking to name the class `'Thing'` -- unless the flags package is supposed to strip extraneous single and double quotes? (I would not expect this.)

Try omitting the single quotes, i.e.
```
//go:generate mockery -name=Thing
```

**Comment by atombender** [comment]
Hm, I guess you're right about that!
