### ISSUE TITLE
Generate coded has compile error when argument same as a package name

### ISSUE THREAD

**Issue by atombender** [vektra/mockery#84]
My interface has an argument which is the same as a package name, `event`:

```go
type Connector interface {
	Broadcast(event event.Event) error
}
```

Generated mock:

```go
func (_m *Connector) Broadcast(event event.Event) error {
	ret := _m.Called(event)

	var r0 error
	if rf, ok := ret.Get(0).(func(event.Event) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
```

Fails to compile with:

```
connector.go:52: event.Event undefined (type event.Event has no field or method Event)
```

Solution: The generator should always autogenerate argument names (as it does when your interface doesn't provide a name).

**Comment by evanphx** [comment]
You shouldn't do that actually because you couldn't write code to make that work normally anyway. I don't change the names so that godoc works on the mocks properly.

**Comment by atombender** [comment]
There's no rule in Go that says argument names cannot be the same as package names. It compiles find, both in an interface and in an actual implementation; it justs stops you from being able to refer to the package once you've brought the argument into a scope. "Shouldn't" has nothing to do with it; Mockery generates uncompilable code from compilable code, hence it's a bug.

**Comment by evanphx** [comment]
You're correct in that it would allow this code so long as you didn't try to access the `event` package within the function, but the mock does. I could change it so the name was mangled, but then the generate docs for the mocks would contain the mangled names.

I guess we have to decide if this bug warrants making the docs ugly. Thoughts?

**Comment by atombender** [comment]
I think that correct behaviour (principle of least surprise) trumps good docs, personally. The best solution, though, would be to detect whether a name conflicts in the first place. Should be trivial to look up the names of imports to check?

**Comment by evanphx** [comment]
@atombender I'll change it to mangle, and if you'd like to send a PR to do that detect, I'll merge it! 👍

**Comment by atombender** [comment]
Super. I'm looking at it right now, and I can also do the mangling if you like.

**Comment by evanphx** [comment]
@atombender that would be wonderful! I was hopefully going to get to it in the next few days, but if you do it sooner I'll merge it!

**Comment by atombender** [comment]
I had to add a little more context to the generator (I'm new to `go/types`, but I believe I'm using it correctly). I think the above PR ought to do it.
