### ISSUE TITLE
Upgrade v2.48.0 -> v2.49.0 changes mock signatures any -> interface{}

### ISSUE THREAD

**Issue by yurishkuro** [vektra/mockery#848]
Description
-------------

An upgrade failed our linter stage in CI (https://github.com/jaegertracing/jaeger/pull/6232) because it detected this change in the mocks:

```diff
-func (_m *IndexService) BodyJson(body any) es.IndexService {
+func (_m *IndexService) BodyJson(body interface{}) es.IndexService {
```

I didn't see anything in the changelog about it, is this expected side effect?

Mockery Version
--------

v2.49.0

Go Version
--------------

go1.23.3

Installation Method
-------------------

go install

Steps to Reproduce
------------------

let me know if needed

### Expected Behavior

Stable signatures

### Actual Behavior

any -> interface{}

**Comment by LandonTClipp** [comment]
I'm sorry for the confusion. The introduction of type alias support was a breaking change for some folks. We introduced `resolve-type-alias` that was defaulted to revert to the old behavior. You should see mockery emit a warning about this. 

https://vektra.github.io/mockery/latest/deprecations/#resolve-type-alias

If you set that to `false`, it should fix the issue for you.

**Comment by LandonTClipp** [comment]
I added a note in the changelog with more information.

**Comment by yurishkuro** [comment]
If I have the new property set to false, it warns:
```
WRN DEPRECATION: issue-845-fix must be set to True to remove this warning.
```

If I set it to true it warns:
```
WRN DEPRECATION: resolve-type-alias will be permanently set to False in v3. 
  Please modify your config to set the parameter to False.
```

Feels a bit like lose-lose. Also my config doesn't use `resolve-type-alias`, and the scenario described in the docs for `issue-845-fix` is not applicable.

More importantly, the change in the signatures is still there after regenerating, regarding of the value of set to `issue-845-fix`.

Overall it's not a big deal, I can just accept the any->interface{} changes, but it sounds like an unintended side-effect.

**Comment by LandonTClipp** [comment]
To be clear, these deprecation warnings are two separate issues so it's important to look at them in isolation.

`resolve-type-alias: False` will fix the issue described in this issue. `issue-845-fix` is an unrelated problem that probably does not affect you, but you can resolve with `issue-845-fix: True`. 

These two deprecation warnings are implemented to retain backwards compatibility and are part of my effort towards driving mockery to a v3 release.

**Comment by yurishkuro** [comment]
got it. Yes, setting these flags resolved the issue and all the warnings
```diff
+issue-845-fix: true
+resolve-type-alias: false
```

**Comment by yurishkuro** [comment]
Thanks

**Comment by jmalicevic** [comment]
Hi, thank you for providing the fix. Is the only way to set the flag in `.mockery.yml` or can we doing also via command line?
