### ISSUE TITLE
Regenerating a mock fails when the interface has been changed

### ISSUE THREAD

**Issue by kaipakartik** [vektra/mockery#86]
The same mock gets reused even though the interface has changed. It should regenerate the mock based on the new definition of the interface.

My guess is that there is a cache somewhere that is storing the mocks for the interface.

**Comment by evanphx** [comment]
Can you show me what happens here? You should be able to regenerate the mock anytime you wish. There are no caches of them.

**Comment by kaipakartik** [comment]
I have an interface of type say Stringer

type Stringer interface {
  String() string
}

$GOPATH/bin/mockery -name Stringer -recursive=true   -case=underscore

This will generate the right mock for Stringer

However if I now add another method to the interface
type Stringer interface {
  String() string
 String2() string
}

and run 
$GOPATH/bin/mockery -name Stringer -recursive=true   -case=underscore

The new method is NOT present in the generated mock.

I am running this on my mac.

**Comment by IvanMalison** [comment]
@kaipakartik I can't replicate this issue. Are you sure that this is actually happening?
