### ISSUE TITLE
Interfaces cannot mention types that aren't defined in the same file

### ISSUE THREAD

**Issue by xeger** [vektra/mockery#96]
Because mockery parses each file in a directory independently of others (i.e. using `loader.Config.ParseFiles()` for each distinct source file), it is impossible to generate a mock for interfaces whose methods mention a type that is defined in another file of the same package.

I've created [some test fixtures](https://github.com/xeger/mockery/blob/type-rich-interfaces/mockery/fixtures/requester5.go) to illustrate the problem; to reproduce it, run the following:

```
cd mockery/fixtures
mockery -name Requester5
```

I tried to create a test case, too, but for some reason this problem fails to reproduce when the unit tests parse each file individually. Seems to me like some higher-level functional tests of mockery might be in order.

**Comment by xeger** [comment]
Fixed in https://github.com/xeger/mongoose

**Comment by evanphx** [comment]
This should be fixed as of #93.
