### ISSUE TITLE
tests take 2+ minutes to run

### ISSUE THREAD

**Issue by kevinburke** [vektra/mockery#97]
I'm trying to submit a patch, but it's difficult to determine whether it works, because the `github.com/vektra/mockery/mockery` package tests hang indefinitely for me. I'm on Go 1.7rc3. 

Here's the console output from running `go test -race -timeout=1s ./...` from the mockery directory; I haven't investigated further.

https://gist.github.com/kevinburke/de860ae2d77c7028dd5f4cf34e35beb9

**Comment by kevinburke** [comment]
Never mind; the test suite takes 133 seconds to pass. maybe you could put a warning somewhere? or have a Makefile with `go test -timeout=3m ./...` as the default invocation?

**Comment by evanphx** [comment]
Using `-v` shows the progress, it's just that there are 2 tests that take about a minute. I'm going to at least make those 2 not run when `-short` is used.

**Comment by kevinburke** [comment]
thanks!


--
Kevin Burke
925.271.7005 | kev.inburke.com
